
import { Cocktail, MasterIngredient } from './types';

export const INITIAL_MASTER_DATA: MasterIngredient[] = [
    // --- GIN ---
    { id: 'm-gin-gen', name: 'Gin', category: 'Spirit', subCategory: 'Gin', abv: 40, isGeneric: true, defaultFlavorNotes: 'Juniper-forward, herbal.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-gin-ld', name: 'London Dry Gin', category: 'Spirit', subCategory: 'Gin', abv: 40, isGeneric: true, defaultFlavorNotes: 'Dry, crisp, heavy juniper.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-gin-old', name: 'Old Tom Gin', category: 'Spirit', subCategory: 'Gin', abv: 40, isGeneric: true, defaultFlavorNotes: 'Slightly sweet, malty.', nutritionEstimate: { caloriesPerOz: 70, carbsPerOz: 2 } },
    { id: 'm-gin-plym', name: 'Plymouth Gin', category: 'Spirit', subCategory: 'Gin', abv: 41.2, isGeneric: false, defaultFlavorNotes: 'Earthy, less dry, citrus.', nutritionEstimate: { caloriesPerOz: 67, carbsPerOz: 0 } },
    { id: 'm-gin-hend', name: 'Hendrick\'s Gin', category: 'Spirit', subCategory: 'Gin', abv: 41.4, isGeneric: false, defaultFlavorNotes: 'Rose and cucumber.', nutritionEstimate: { caloriesPerOz: 68, carbsPerOz: 0 } },
    { id: 'm-gin-na', name: 'NA Gin', category: 'Spirit', subCategory: 'Non-Alcoholic', abv: 0, isGeneric: true, defaultFlavorNotes: 'Juniper and botanicals without alcohol.', nutritionEstimate: { caloriesPerOz: 5, carbsPerOz: 1 } },

    // --- WHISKEY ---
    { id: 'm-rye-gen', name: 'Rye Whiskey', category: 'Spirit', subCategory: 'Rye', abv: 45, isGeneric: true, defaultFlavorNotes: 'Spicy, grainy, dry finish.', nutritionEstimate: { caloriesPerOz: 72, carbsPerOz: 0 } },
    { id: 'm-bour-gen', name: 'Bourbon', category: 'Spirit', subCategory: 'Bourbon', abv: 40, isGeneric: true, defaultFlavorNotes: 'Sweet corn, caramel, vanilla.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-scot-blend', name: 'Blended Scotch', category: 'Spirit', subCategory: 'Scotch', abv: 40, isGeneric: true, defaultFlavorNotes: 'Smooth, malty, subtle smoke.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-scot-islay', name: 'Islay Scotch', category: 'Spirit', subCategory: 'Scotch', abv: 43, isGeneric: true, defaultFlavorNotes: 'Peat smoke, iodine, seaweed.', nutritionEstimate: { caloriesPerOz: 69, carbsPerOz: 0 } },
    { id: 'm-irish', name: 'Irish Whiskey', category: 'Spirit', subCategory: 'Whiskey', abv: 40, isGeneric: true, defaultFlavorNotes: 'Smooth, light, fruity.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-applejack', name: 'Applejack', category: 'Spirit', subCategory: 'Brandy', abv: 40, isGeneric: true, defaultFlavorNotes: 'Apple, oak, vanilla.', nutritionEstimate: { caloriesPerOz: 70, carbsPerOz: 0 } },
    { id: 'm-canadian', name: 'Canadian Whisky', category: 'Spirit', subCategory: 'Whiskey', abv: 40, isGeneric: true, defaultFlavorNotes: 'Light, smooth, vanilla.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },

    // --- AGAVE ---
    { id: 'm-teq-bla', name: 'Blanco Tequila', category: 'Spirit', subCategory: 'Tequila', abv: 40, isGeneric: true, defaultFlavorNotes: 'Unaged, agave forward, citrus.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-teq-repo', name: 'Reposado Tequila', category: 'Spirit', subCategory: 'Tequila', abv: 40, isGeneric: true, defaultFlavorNotes: 'Lightly aged, vanilla hint.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-mez-vid', name: 'Mezcal', category: 'Spirit', subCategory: 'Mezcal', abv: 42, isGeneric: false, defaultFlavorNotes: 'Smoke, honey, roast agave.', nutritionEstimate: { caloriesPerOz: 70, carbsPerOz: 0 } },

    // --- RUM & SUGAR CANE ---
    { id: 'm-rum-white', name: 'White Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Light, clean, molasses.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-rum-aged', name: 'Aged Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Oak, vanilla, spice.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0.5 } },
    { id: 'm-rum-jam', name: 'Jamaican Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Funky, ripe banana, spice.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0.5 } },
    { id: 'm-rum-black', name: 'Black Strap Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Dark molasses, coffee, treacle.', nutritionEstimate: { caloriesPerOz: 75, carbsPerOz: 4 } },
    { id: 'm-rum-agric', name: 'Rhum Agricole', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Grassy, vegetal, cane juice.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-rum-over', name: 'Overproof Rum', category: 'Spirit', subCategory: 'Rum', abv: 69, isGeneric: true, defaultFlavorNotes: 'Intense, hot, ester funk.', nutritionEstimate: { caloriesPerOz: 110, carbsPerOz: 0 } },
    { id: 'm-cachaca', name: 'Cachaça', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Grassy, raw cane.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },

    // --- BRANDY & COGNAC ---
    { id: 'm-cognac', name: 'Cognac', category: 'Spirit', subCategory: 'Brandy', abv: 40, isGeneric: true, defaultFlavorNotes: 'Grape, oak, leather.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-pisco', name: 'Pisco', category: 'Spirit', subCategory: 'Brandy', abv: 40, isGeneric: true, defaultFlavorNotes: 'Floral, grape, earthy.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },

    // --- LIQUEURS & AMARI ---
    { id: 'm-am-camp', name: 'Campari', category: 'Spirit', subCategory: 'Amaro', abv: 24, isGeneric: false, defaultFlavorNotes: 'Intense bitter orange.', nutritionEstimate: { caloriesPerOz: 80, carbsPerOz: 8 } },
    { id: 'm-am-aper', name: 'Aperol', category: 'Spirit', subCategory: 'Amaro', abv: 11, isGeneric: false, defaultFlavorNotes: 'Sweet orange, gentian.', nutritionEstimate: { caloriesPerOz: 75, carbsPerOz: 9 } },
    { id: 'm-am-non', name: 'Amaro Nonino', category: 'Spirit', subCategory: 'Amaro', abv: 35, isGeneric: false, defaultFlavorNotes: 'Grappa based, orange, caramel.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 9 } },
    { id: 'm-am-fer', name: 'Fernet-Branca', category: 'Spirit', subCategory: 'Amaro', abv: 39, isGeneric: false, defaultFlavorNotes: 'Menthol, saffron, bitter.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 4 } },
    { id: 'm-am-aver', name: 'Averna', category: 'Spirit', subCategory: 'Amaro', abv: 29, isGeneric: false, defaultFlavorNotes: 'Cola, citrus, caramel.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 10 } },
    { id: 'm-am-cyn', name: 'Cynar', category: 'Spirit', subCategory: 'Amaro', abv: 16.5, isGeneric: false, defaultFlavorNotes: 'Artichoke, savory, vegetal.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 8 } },
    { id: 'm-am-suze', name: 'Suze', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: false, defaultFlavorNotes: 'Gentian, earthy, bitter.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 5 } },
    { id: 'm-am-punt', name: 'Punt e Mes', category: 'Spirit', subCategory: 'Vermouth', abv: 16, isGeneric: false, defaultFlavorNotes: 'Bitter vermouth, orange, quinine.', nutritionEstimate: { caloriesPerOz: 50, carbsPerOz: 6 } },
    { id: 'm-am-picon', name: 'Amer Picon', category: 'Spirit', subCategory: 'Amaro', abv: 21, isGeneric: false, defaultFlavorNotes: 'Bitter orange, gentian.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 6 } },

    { id: 'm-liq-coint', name: 'Cointreau', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Clean orange triple sec.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 7 } },
    { id: 'm-liq-mar', name: 'Maraschino Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 32, isGeneric: true, defaultFlavorNotes: 'Funky cherry, almond.', nutritionEstimate: { caloriesPerOz: 105, carbsPerOz: 10 } },
    { id: 'm-liq-chart', name: 'Green Chartreuse', category: 'Spirit', subCategory: 'Liqueur', abv: 55, isGeneric: false, defaultFlavorNotes: 'Complex herbs, high proof.', nutritionEstimate: { caloriesPerOz: 110, carbsPerOz: 10 } },
    { id: 'm-liq-chart-y', name: 'Yellow Chartreuse', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Honey, saffron, softer herbs.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 11 } },
    { id: 'm-liq-kahl', name: 'Coffee Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: true, defaultFlavorNotes: 'Sweet coffee, vanilla.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 11 } },
    { id: 'm-liq-stger', name: 'St. Germain', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: false, defaultFlavorNotes: 'Elderflower, lychee.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 11 } },
    { id: 'm-liq-bene', name: 'Benedictine', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Honey, herbs, spice.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 10 } },
    { id: 'm-liq-fal', name: 'Falernum', category: 'Spirit', subCategory: 'Liqueur', abv: 11, isGeneric: true, defaultFlavorNotes: 'Lime, ginger, clove, almond.', nutritionEstimate: { caloriesPerOz: 85, carbsPerOz: 12 } },
    { id: 'm-liq-abs', name: 'Absinthe', category: 'Spirit', subCategory: 'Liqueur', abv: 60, isGeneric: true, defaultFlavorNotes: 'Anise, fennel, wormwood.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 2 } },
    { id: 'm-liq-all', name: 'Allspice Dram', category: 'Spirit', subCategory: 'Liqueur', abv: 22, isGeneric: true, defaultFlavorNotes: 'Intense allspice berry.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 9 } },
    { id: 'm-liq-vio', name: 'Crème de Violette', category: 'Spirit', subCategory: 'Liqueur', abv: 22, isGeneric: true, defaultFlavorNotes: 'Floral violet, sweet.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 10 } },
    { id: 'm-liq-cherr', name: 'Cherry Heering', category: 'Spirit', subCategory: 'Liqueur', abv: 24, isGeneric: false, defaultFlavorNotes: 'Rich cherry, spiced.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 11 } },
    { id: 'm-liq-menthe-g', name: 'Crème de Menthe (Green)', category: 'Spirit', subCategory: 'Liqueur', abv: 24, isGeneric: true, defaultFlavorNotes: 'Cool mint, sweet, refreshing.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 14 } },
    { id: 'm-liq-menthe-w', name: 'Crème de Menthe (White)', category: 'Spirit', subCategory: 'Liqueur', abv: 24, isGeneric: true, defaultFlavorNotes: 'Cool mint, sweet, clear.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 14 } },
    { id: 'm-liq-cacao-d', name: 'Crème de Cacao (Dark)', category: 'Spirit', subCategory: 'Liqueur', abv: 25, isGeneric: true, defaultFlavorNotes: 'Rich chocolate, vanilla.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 12 } },
    { id: 'm-liq-cacao-w', name: 'Crème de Cacao (White)', category: 'Spirit', subCategory: 'Liqueur', abv: 25, isGeneric: true, defaultFlavorNotes: 'Light chocolate, sweet.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 12 } },
    { id: 'm-liq-cassis', name: 'Crème de Cassis', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: true, defaultFlavorNotes: 'Blackcurrant, tart, sweet.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 15 } },
    { id: 'm-liq-mure', name: 'Crème de Mûre', category: 'Spirit', subCategory: 'Liqueur', abv: 16, isGeneric: true, defaultFlavorNotes: 'Blackberry, jammy, sweet.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 14 } },
    { id: 'm-liq-banana', name: 'Banana Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 17, isGeneric: true, defaultFlavorNotes: 'Ripe banana, tropical.', nutritionEstimate: { caloriesPerOz: 85, carbsPerOz: 12 } },
    { id: 'm-liq-peach', name: 'Peach Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 15, isGeneric: true, defaultFlavorNotes: 'Sweet peach, stone fruit.', nutritionEstimate: { caloriesPerOz: 85, carbsPerOz: 13 } },
    { id: 'm-liq-raspberry', name: 'Raspberry Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 16, isGeneric: true, defaultFlavorNotes: 'Tart raspberry, berry.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 14 } },
    { id: 'm-liq-triplesec', name: 'Triple Sec', category: 'Spirit', subCategory: 'Liqueur', abv: 30, isGeneric: true, defaultFlavorNotes: 'Orange, citrus, sweet.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 11 } },
    { id: 'm-liq-grandmar', name: 'Grand Marnier', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Cognac base, orange, oak.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 10 } },
    { id: 'm-liq-curacao', name: 'Curaçao', category: 'Spirit', subCategory: 'Liqueur', abv: 25, isGeneric: true, defaultFlavorNotes: 'Bitter orange, citrus.', nutritionEstimate: { caloriesPerOz: 85, carbsPerOz: 10 } },
    { id: 'm-liq-amaretto', name: 'Amaretto', category: 'Spirit', subCategory: 'Liqueur', abv: 28, isGeneric: true, defaultFlavorNotes: 'Almond, marzipan, sweet.', nutritionEstimate: { caloriesPerOz: 110, carbsPerOz: 17 } },
    { id: 'm-liq-midori', name: 'Midori', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: false, defaultFlavorNotes: 'Honeydew melon, sweet.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 13 } },
    { id: 'm-liq-chambord', name: 'Chambord', category: 'Spirit', subCategory: 'Liqueur', abv: 16.5, isGeneric: false, defaultFlavorNotes: 'Black raspberry, honey, cognac.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 13 } },
    { id: 'm-liq-irish-cream', name: 'Irish Cream', category: 'Spirit', subCategory: 'Liqueur', abv: 17, isGeneric: true, defaultFlavorNotes: 'Cream, whiskey, chocolate.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 10 } },
    { id: 'm-liq-drambuie', name: 'Drambuie', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Scotch base, honey, herbs.', nutritionEstimate: { caloriesPerOz: 105, carbsPerOz: 10 } },
    { id: 'm-liq-galliano', name: 'Galliano', category: 'Spirit', subCategory: 'Liqueur', abv: 42.3, isGeneric: false, defaultFlavorNotes: 'Vanilla, anise, herbal.', nutritionEstimate: { caloriesPerOz: 110, carbsPerOz: 12 } },
    { id: 'm-liq-limoncello', name: 'Limoncello', category: 'Spirit', subCategory: 'Liqueur', abv: 28, isGeneric: true, defaultFlavorNotes: 'Lemon zest, bright, sweet.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 17 } },
    { id: 'm-liq-sambuca', name: 'Sambuca', category: 'Spirit', subCategory: 'Liqueur', abv: 42, isGeneric: true, defaultFlavorNotes: 'Anise, licorice, sweet.', nutritionEstimate: { caloriesPerOz: 105, carbsPerOz: 11 } },
    { id: 'm-liq-sloe-gin', name: 'Sloe Gin', category: 'Spirit', subCategory: 'Liqueur', abv: 26, isGeneric: true, defaultFlavorNotes: 'Sloe berry, tart, almond.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 10 } },

    // --- VERMOUTH & WINE ---
    { id: 'm-ver-sweet', name: 'Sweet Vermouth', category: 'Spirit', subCategory: 'Vermouth', abv: 16, isGeneric: true, defaultFlavorNotes: 'Spiced wine, caramel.', nutritionEstimate: { caloriesPerOz: 45, carbsPerOz: 4 } },
    { id: 'm-ver-dry', name: 'Dry Vermouth', category: 'Spirit', subCategory: 'Vermouth', abv: 16, isGeneric: true, defaultFlavorNotes: 'Crisp, herbal, dry.', nutritionEstimate: { caloriesPerOz: 35, carbsPerOz: 1 } },
    { id: 'm-ver-lill', name: 'Lillet Blanc', category: 'Spirit', subCategory: 'Vermouth', abv: 17, isGeneric: false, defaultFlavorNotes: 'Honey, orange, quinine.', nutritionEstimate: { caloriesPerOz: 45, carbsPerOz: 4 } },
    { id: 'm-sherry', name: 'Sherry', category: 'Spirit', subCategory: 'Wine', abv: 15, isGeneric: true, defaultFlavorNotes: 'Nutty, oxidative.', nutritionEstimate: { caloriesPerOz: 40, carbsPerOz: 2 } },
    { id: 'm-port', name: 'Port', category: 'Spirit', subCategory: 'Wine', abv: 20, isGeneric: true, defaultFlavorNotes: 'Sweet red fruit.', nutritionEstimate: { caloriesPerOz: 50, carbsPerOz: 4 } },

    // --- MIXERS ---
    { id: 'm-mix-simp', name: 'Simple Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Pure sweetness.', nutritionEstimate: { caloriesPerOz: 50, carbsPerOz: 14 } },
    { id: 'm-mix-honey', name: 'Honey Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Floral honey.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 17 } },
    { id: 'm-mix-agave', name: 'Agave Nectar', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Earthy sweetness.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 16 } },
    { id: 'm-mix-orgeat', name: 'Orgeat', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Almond, rose water.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 16 } },
    { id: 'm-mix-gren', name: 'Grenadine', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Pomegranate tartness.', nutritionEstimate: { caloriesPerOz: 55, carbsPerOz: 14 } },
    { id: 'm-mix-pass', name: 'Passion Fruit Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Tropical tang.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 15 } },
    { id: 'm-mix-lem', name: 'Lemon Juice', category: 'Mixer', subCategory: 'Citrus', abv: 0, isGeneric: true, defaultFlavorNotes: 'Sour acidity.', nutritionEstimate: { caloriesPerOz: 8, carbsPerOz: 2 } },
    { id: 'm-mix-lim', name: 'Lime Juice', category: 'Mixer', subCategory: 'Citrus', abv: 0, isGeneric: true, defaultFlavorNotes: 'Tart, tropical.', nutritionEstimate: { caloriesPerOz: 8, carbsPerOz: 2 } },
    { id: 'm-mix-grap', name: 'Grapefruit Juice', category: 'Mixer', subCategory: 'Citrus', abv: 0, isGeneric: true, defaultFlavorNotes: 'Bitter, sour.', nutritionEstimate: { caloriesPerOz: 12, carbsPerOz: 3 } },
    { id: 'm-mix-pine', name: 'Pineapple Juice', category: 'Mixer', subCategory: 'Juice', abv: 0, isGeneric: true, defaultFlavorNotes: 'Sweet, foaming.', nutritionEstimate: { caloriesPerOz: 16, carbsPerOz: 4 } },
    { id: 'm-mix-ging', name: 'Ginger Beer', category: 'Mixer', subCategory: 'Soda', abv: 0, isGeneric: true, defaultFlavorNotes: 'Spicy carbonation.', nutritionEstimate: { caloriesPerOz: 12, carbsPerOz: 3 } },
];

export const INITIAL_RECIPES_DATA: Cocktail[] = [
    // === ANCESTRALS (PRE-1900) ===
    { 
        id: 'old-fashioned', 
        name: 'Old Fashioned', 
        category: 'Ancestrals', 
        ingredients: ['2 oz Bourbon or Rye', '0.25 oz Simple Syrup', '2 dashes Angostura Bitters'], 
        instructions: ['Stir ingredients in rocks glass.', 'Add large ice cube.', 'Garnish with orange peel.'], 
        description: 'The original "Whiskey Cocktail" defined in 1806, evolved by the 1880s.', 
        history: 'Defined in 1806 as "spirits, sugar, water, and bitters", the Old Fashioned gained its current name in the 1880s when drinkers revolted against complex modern cocktails, asking for a drink the "old fashioned way". The Pendleton Club in Louisville often claims its invention, but the formula predates it by decades.',
        creator: 'Pendennis Club (Disputed)', 
        dateAdded: '1880-01-01', 
        flavorProfile: { Sweet: 3, Sour: 0, Bitter: 4, Boozy: 8, Herbal: 2, Fruity: 1, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'sazerac', 
        name: 'Sazerac', 
        category: 'Ancestrals', 
        ingredients: ['2 oz Rye Whiskey', '0.25 oz Simple Syrup', '4 dashes Peychaud\'s Bitters', 'Absinthe (Rinse)'], 
        instructions: ['Rinse glass with absinthe.', 'Stir rye, sugar, bitters with ice.', 'Strain into rinsed glass.', 'Express lemon peel.'], 
        description: 'New Orleans official cocktail. Originally Cognac, switched to Rye after phylloxera.', 
        history: 'Often cited as the first branded cocktail, created by Antoine Amédée Peychaud in New Orleans using his proprietary bitters. Originally made with Sazerac de Forge et Fils cognac, the recipe switched to American Rye Whiskey around 1870 when the phylloxera epidemic decimated French vineyards. The absinthe rinse became a necessity after the spirit was banned in 1912, though traditionally it was mixed in.',
        creator: 'Antoine Amédée Peychaud', 
        dateAdded: '1838-01-01', 
        flavorProfile: { Sweet: 3, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 5, Fruity: 0, Spicy: 4, Smoky: 0 } 
    },
    { 
        id: 'improved-whiskey', 
        name: 'Improved Whiskey Cocktail', 
        category: 'Ancestrals', 
        ingredients: ['2 oz Rye Whiskey', '0.25 oz Maraschino Liqueur', '1 dash Angostura Bitters', '1 dash Absinthe'], 
        instructions: ['Stir with ice.', 'Strain into rocks glass with ice.', 'Lemon peel.'], 
        description: 'Jerry Thomas\'s "Improved" version of the Old Fashioned.', 
        history: 'In the late 19th century, bartenders tried to differentiate themselves by "improving" the basic Old Fashioned formula with imported European liqueurs like Maraschino and Absinthe. Jerry Thomas immortalized this style in his 1876 guide, marking a bridge between the primitive sling and the complex cocktail era.',
        creator: 'Jerry Thomas', 
        dateAdded: '1876-01-01', 
        flavorProfile: { Sweet: 3, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 3, Fruity: 1, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'monte-carlo', 
        name: 'Monte Carlo', 
        category: 'Ancestrals', 
        ingredients: ['2 oz Rye Whiskey', '0.5 oz Benedictine', '2 dashes Angostura Bitters'], 
        instructions: ['Stir with ice.', 'Strain into coupe or over large rock.', 'Lemon twist.'], 
        description: 'A Manhattan variation from David Embury\'s "The Fine Art of Mixing Drinks".', 
        history: 'Featured in David Embury\'s 1948 classic "The Fine Art of Mixing Drinks", this cocktail swaps the sweet vermouth of a Manhattan for the herbal, honeyed complexity of Bénédictine. It represents a simpler time of two-bottle cocktails that still offer profound depth.',
        creator: 'David Embury', 
        dateAdded: '1948-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 6, Fruity: 0, Spicy: 2, Smoky: 0 } 
    },

    // === SPIRIT-FORWARD CLASSICS ===
    { 
        id: 'martini', 
        name: 'Dry Martini', 
        category: 'Spirit-Forward', 
        ingredients: ['2.5 oz Gin', '0.5 oz Dry Vermouth', '1 dash Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Lemon twist or olive.'], 
        description: 'Evolved from the Martinez. The ultimate test of temperature and dilution.', 
        history: 'The Martini\'s evolution is legendary, likely starting as the sweet Martinez (Gin + Sweet Vermouth) before drying out as London Dry Gin became available. By the mid-20th century, the ratio shifted from 2:1 to 5:1 or drier. H.L. Mencken called it "the only American invention as perfect as the sonnet."',
        creator: 'Knickerbocker Hotel (Disputed)', 
        dateAdded: '1910-01-01', 
        flavorProfile: { Sweet: 0, Sour: 0, Bitter: 2, Boozy: 9, Herbal: 5, Fruity: 0, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'manhattan', 
        name: 'Manhattan', 
        category: 'Spirit-Forward', 
        ingredients: ['2 oz Rye Whiskey', '1 oz Sweet Vermouth', '2 dashes Angostura Bitters'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Cherry garnish.'], 
        description: 'Created at the Manhattan Club for a banquet hosted by Lady Randolph Churchill.', 
        history: 'Legend states it was created in 1874 at the Manhattan Club for a party hosted by Jennie Jerome (Winston Churchill\'s mother), though records show she was in France at the time. Regardless, it became the first cocktail to use vermouth as a modifier, changing mixology forever.',
        creator: 'Manhattan Club', 
        dateAdded: '1874-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 3, Boozy: 7, Herbal: 2, Fruity: 1, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'negroni', 
        name: 'Negroni', 
        category: 'Spirit-Forward', 
        ingredients: ['1 oz Gin', '1 oz Campari', '1 oz Sweet Vermouth'], 
        instructions: ['Stir with ice.', 'Strain over large rock.', 'Orange peel.'], 
        description: 'Count Camillo Negroni asked to strengthen his Americano with gin.', 
        history: 'In 1919 at Caffe Casoni in Florence, Count Camillo Negroni asked bartender Fosco Scarselli to strengthen his favorite Americano (Campari, Vermouth, Soda) by replacing the soda water with gin. The bartender added an orange garnish to signify it was a different drink, and a classic was born.',
        creator: 'Fosco Scarselli', 
        dateAdded: '1919-01-01', 
        flavorProfile: { Sweet: 5, Sour: 0, Bitter: 8, Boozy: 6, Herbal: 6, Fruity: 2, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'boulevardier', 
        name: 'Boulevardier', 
        category: 'Spirit-Forward', 
        ingredients: ['1.5 oz Bourbon', '1 oz Sweet Vermouth', '1 oz Campari'], 
        instructions: ['Stir with ice.', 'Strain over large rock.', 'Orange twist.'], 
        description: 'The signature drink of Erskine Gwynne, editor of "The Boulevardier" magazine.', 
        history: 'Often called a "Whiskey Negroni," this drink actually appeared in Harry\'s ABC of Mixing Cocktails in 1927, credited to Erskine Gwynne, an American expatriate writer and socialite who ran a magazine in Paris called "The Boulevardier".',
        creator: 'Harry\'s New York Bar (Paris)', 
        dateAdded: '1927-01-01', 
        flavorProfile: { Sweet: 5, Sour: 0, Bitter: 7, Boozy: 7, Herbal: 5, Fruity: 2, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'vieux-carre', 
        name: 'Vieux Carré', 
        category: 'Spirit-Forward', 
        ingredients: ['1 oz Rye Whiskey', '1 oz Cognac', '1 oz Sweet Vermouth', '1 tsp Benedictine', '2 dashes Peychaud\'s', '2 dashes Angostura'], 
        instructions: ['Stir with ice.', 'Strain over ice in rocks glass.', 'Lemon twist.'], 
        description: 'A tribute to the French Quarter, created at the Hotel Monteleone.', 
        history: 'Created in 1938 by Walter Bergeron, head bartender at the Hotel Monteleone\'s Carousel Bar. The name translates to "Old Square," the French term for the French Quarter. It represents the melting pot of New Orleans, combining American Rye, French Cognac and Benedictine, and Italian Vermouth.',
        creator: 'Walter Bergeron', 
        dateAdded: '1938-01-01', 
        flavorProfile: { Sweet: 5, Sour: 0, Bitter: 3, Boozy: 7, Herbal: 5, Fruity: 2, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'martinez', 
        name: 'Martinez', 
        category: 'Spirit-Forward', 
        ingredients: ['1.5 oz Old Tom Gin', '1.5 oz Sweet Vermouth', '1 tsp Maraschino Liqueur', '2 dashes Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into coupe.', 'Orange twist.'], 
        description: 'The "Missing Link" between the Manhattan and the Martini.', 
        history: 'Widely considered the precursor to the Martini. The first printed recipe appeared in O.H. Byron\'s 1884 guide. It uses Old Tom Gin (sweeter than London Dry) and Sweet Vermouth, bridging the gap between the whiskey-based Manhattan and the dry gin Martini.',
        creator: 'Jerry Thomas', 
        dateAdded: '1887-01-01', 
        flavorProfile: { Sweet: 6, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 4, Fruity: 2, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'brooklyn', 
        name: 'Brooklyn', 
        category: 'Spirit-Forward', 
        ingredients: ['2 oz Rye Whiskey', '1 oz Dry Vermouth', '0.25 oz Maraschino Liqueur', '0.25 oz Amer Picon (or substitute)'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.'], 
        description: 'One of the five borough cocktails, famously hard to source ingredients for.', 
        history: 'Created by Jacob Grohusko at Baracca\'s in Wall Street around 1908. It is one of the five borough cocktails but fell into obscurity because Amer Picon became impossible to find in the US. Modern bartenders often substitute Amaro CioCiaro or Bigallet China-China.',
        creator: 'Jacob Grohusko', 
        dateAdded: '1908-01-01', 
        flavorProfile: { Sweet: 2, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 3, Fruity: 1, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'hanky-panky', 
        name: 'Hanky Panky', 
        category: 'Spirit-Forward', 
        ingredients: ['1.5 oz Gin', '1.5 oz Sweet Vermouth', '2 dashes Fernet-Branca'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Orange twist.'], 
        description: 'Created for Sir Charles Hawtrey at the Savoy.', 
        history: 'Invented by Ada Coleman, the legendary head bartender at the Savoy Hotel\'s American Bar. She made it for actor Sir Charles Hawtrey, who requested something with a "kick in it." Upon tasting it, he exclaimed, "By Jove! That is the real hanky-panky!"',
        creator: 'Ada Coleman', 
        dateAdded: '1903-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 5, Boozy: 7, Herbal: 5, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'bijou', 
        name: 'Bijou', 
        category: 'Spirit-Forward', 
        ingredients: ['1 oz Gin', '1 oz Sweet Vermouth', '1 oz Green Chartreuse', '1 dash Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Cherry and lemon twist.'], 
        description: 'Named for the jewels: Gin (Diamond), Vermouth (Ruby), Chartreuse (Emerald).', 
        history: 'Bijou means "Jewel" in French. Created by Harry Johnson in 1900, the drink is said to represent three jewels: Gin for diamonds, Sweet Vermouth for rubies, and Green Chartreuse for emeralds. It is a powerful, herbal cocktail that regained popularity during the cocktail renaissance.',
        creator: 'Harry Johnson', 
        dateAdded: '1900-01-01', 
        flavorProfile: { Sweet: 6, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 8, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'tipperary', 
        name: 'Tipperary', 
        category: 'Spirit-Forward', 
        ingredients: ['1.5 oz Irish Whiskey', '1 oz Sweet Vermouth', '0.5 oz Green Chartreuse'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Orange twist.'], 
        description: 'An Irish Whiskey Bijou, celebrating the song "It\'s a Long Way to Tipperary".', 
        history: 'Appearing in Hugo Ensslin\'s 1916 "Recipes for Mixed Drinks", this cocktail was named after the WWI marching song "It\'s a Long Way to Tipperary". It applies the herbal complexity of the Bijou template to Irish Whiskey.',
        creator: 'Hugo Ensslin', 
        dateAdded: '1916-01-01', 
        flavorProfile: { Sweet: 5, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 6, Fruity: 1, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'vesper', 
        name: 'Vesper', 
        category: 'Spirit-Forward', 
        ingredients: ['3 oz Gin', '1 oz Vodka', '0.5 oz Lillet Blanc'], 
        instructions: ['Shake (per Bond) or Stir (per quality) with ice.', 'Strain into goblet.', 'Lemon peel.'], 
        description: 'Invented by James Bond in Casino Royale.', 
        history: 'Invented by author Ian Fleming for his character James Bond in the 1953 novel "Casino Royale". Bond named it after Vesper Lynd, the original bond girl. He famously ordered it "shaken, not stirred," causing decades of bartender anguish as shaking bruises the gin and clouds the drink.',
        creator: 'Ian Fleming', 
        dateAdded: '1953-01-01', 
        flavorProfile: { Sweet: 2, Sour: 0, Bitter: 2, Boozy: 9, Herbal: 3, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },

    // === MODERN CLASSICS (2000-Present) ===
    { 
        id: 'gold-rush', 
        name: 'Gold Rush', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Bourbon', '0.75 oz Lemon Juice', '0.75 oz Honey Syrup'], 
        instructions: ['Shake with ice.', 'Strain into rocks glass with ice.'], 
        description: 'A Bee\'s Knees with Bourbon, created at the original Milk & Honey.', 
        history: 'Created by T.J. Siegal at the original Milk & Honey in NYC around 2001. Siegal essentially swapped the gin in a Bee\'s Knees for bourbon, creating a modern classic that feels like it has existed for a century. It is the precursor to the Penicillin.',
        creator: 'T.J. Siegal (Milk & Honey)', 
        dateAdded: '2001-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 1, Fruity: 1, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'penicillin', 
        name: 'Penicillin', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Blended Scotch', '0.75 oz Lemon Juice', '0.75 oz Honey-Ginger Syrup', '0.25 oz Islay Scotch (Float)'], 
        instructions: ['Shake first 3 ingredients.', 'Strain over ice.', 'Float Islay scotch on top.', 'Candied ginger.'], 
        description: 'The most famous modern classic. A medicinal, smoky, spicy cure-all.', 
        history: 'Created by Sam Ross at Milk & Honey in 2005. It started as a riff on the Gold Rush, splitting the sweetener between honey and ginger and using Scotch. The genius addition of an Islay Scotch float created a "medicinal" nose, earning its name. It is arguably the most successful cocktail of the 21st century.',
        creator: 'Sam Ross (Milk & Honey)', 
        dateAdded: '2005-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 1, Fruity: 0, Spicy: 4, Smoky: 5 } 
    },
    { 
        id: 'paper-plane', 
        name: 'Paper Plane', 
        category: 'Modern Classics', 
        ingredients: ['0.75 oz Bourbon', '0.75 oz Aperol', '0.75 oz Amaro Nonino', '0.75 oz Lemon Juice'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'Named after M.I.A.\'s song "Paper Planes". A Last Word riff.', 
        history: 'Created by Sam Ross in 2008 for the opening menu of The Violet Hour in Chicago. It is structurally a Last Word riff (equal parts), swapping gin/lime/maraschino/chartreuse for bourbon/lemon/aperol/nonino. Ross named it while listening to M.I.A.\'s hit song "Paper Planes" on repeat.',
        creator: 'Sam Ross (The Violet Hour)', 
        dateAdded: '2008-01-01', 
        flavorProfile: { Sweet: 5, Sour: 5, Bitter: 3, Boozy: 5, Herbal: 2, Fruity: 4, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'naked-and-famous', 
        name: 'Naked and Famous', 
        category: 'Modern Classics', 
        ingredients: ['0.75 oz Mezcal', '0.75 oz Yellow Chartreuse', '0.75 oz Aperol', '0.75 oz Lime Juice'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'The "bastard love child" of the Last Word and Paper Plane.', 
        history: 'Created by Joaquin Simo at Death & Co in 2011. Simo described it as "the bastard love child of the Last Word and the Paper Plane, conceived in the mountains of Oaxaca." It uses the equal-parts template to tame the aggressive smokiness of Mezcal with herbal Chartreuse and bitter Aperol.',
        creator: 'Joaquin Simo (Death & Co)', 
        dateAdded: '2011-01-01', 
        flavorProfile: { Sweet: 5, Sour: 5, Bitter: 3, Boozy: 5, Herbal: 5, Fruity: 2, Spicy: 0, Smoky: 5 } 
    },
    { 
        id: 'oaxacan-old-fashioned', 
        name: 'Oaxacan Old Fashioned', 
        category: 'Modern Classics', 
        ingredients: ['1.5 oz Reposado Tequila', '0.5 oz Mezcal', '1 tsp Agave Nectar', '2 dashes Angostura Bitters'], 
        instructions: ['Stir ingredients with ice.', 'Strain over large rock.', 'Flamed orange peel.'], 
        description: 'The drink that kickstarted the Mezcal craze in the US.', 
        history: 'Created by Phil Ward at Death & Co in 2007. At the time, Mezcal was virtually unknown in the US. By using it as a modifier (split base) with Reposado Tequila, Ward introduced the spirit\'s smoky complexity to the American palate in a familiar Old Fashioned format.',
        creator: 'Phil Ward (Death & Co)', 
        dateAdded: '2007-01-01', 
        flavorProfile: { Sweet: 3, Sour: 0, Bitter: 2, Boozy: 8, Herbal: 2, Fruity: 0, Spicy: 1, Smoky: 6 } 
    },
    { 
        id: 'division-bell', 
        name: 'Division Bell', 
        category: 'Modern Classics', 
        ingredients: ['1 oz Mezcal', '0.75 oz Aperol', '0.5 oz Maraschino Liqueur', '0.75 oz Lime Juice'], 
        instructions: ['Shake with ice.', 'Strain into coupe.', 'Grapefruit twist.'], 
        description: 'A smoky variation of the Last Word, named after the Pink Floyd album.', 
        history: 'Created by Phil Ward at his bar Mayahuel in NYC (2009). Named after the Pink Floyd album, this drink helped cement the combination of Mezcal, Lime, and Maraschino as a modern staple. It leans drier and smokier than the Naked and Famous.',
        creator: 'Phil Ward (Mayahuel)', 
        dateAdded: '2009-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 3, Boozy: 6, Herbal: 2, Fruity: 2, Spicy: 0, Smoky: 6 } 
    },
    { 
        id: 'white-negroni', 
        name: 'White Negroni', 
        category: 'Modern Classics', 
        ingredients: ['1.5 oz Gin', '1 oz Lillet Blanc', '0.75 oz Suze'], 
        instructions: ['Stir with ice.', 'Strain over large rock.', 'Lemon twist.'], 
        description: 'A gentian-forward, clear riff on the Negroni created in Bordeaux.', 
        history: 'Invented in 2001 by Wayne Collins in Bordeaux, France, for Nick Blacknell (a gin director at Plymouth). They wanted a Negroni but lacked Campari and Sweet Vermouth, so they improvised with local French ingredients: Lillet Blanc and Suze.',
        creator: 'Wayne Collins', 
        dateAdded: '2001-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 7, Boozy: 6, Herbal: 6, Fruity: 2, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'black-manhattan', 
        name: 'Black Manhattan', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Rye Whiskey', '1 oz Averna', '1 dash Angostura Bitters', '1 dash Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into coupe.', 'Cherry.'], 
        description: 'Replaces Vermouth with Amaro Averna.', 
        history: 'Created by Todd Smith at Bourbon & Branch in San Francisco (2005). This was one of the first drinks to swap vermouth for a full ounce of Amaro, paving the way for the "Reverse Manhattan" style. Averna provides a caramel, herbal depth that pairs perfectly with Rye.',
        creator: 'Todd Smith (Bourbon & Branch)', 
        dateAdded: '2005-01-01', 
        flavorProfile: { Sweet: 5, Sour: 0, Bitter: 4, Boozy: 7, Herbal: 4, Fruity: 1, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'red-hook', 
        name: 'Red Hook', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Rye Whiskey', '0.5 oz Punt e Mes', '0.5 oz Maraschino Liqueur'], 
        instructions: ['Stir with ice.', 'Strain into coupe.', 'Cherry.'], 
        description: 'A Brooklyn variation that became a modern classic.', 
        history: 'Created by Enzo Errico at Milk & Honey in 2003. It is a riff on the Brooklyn cocktail (which is itself a riff on the Manhattan). By using Punt e Mes (a bitter vermouth) and Maraschino, Errico created a drink that is brooding, bitter, and boozy.',
        creator: 'Enzo Errico (Milk & Honey)', 
        dateAdded: '2003-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 4, Boozy: 8, Herbal: 3, Fruity: 2, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'greenpoint', 
        name: 'Greenpoint', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Rye Whiskey', '0.5 oz Yellow Chartreuse', '0.5 oz Sweet Vermouth', '1 dash Angostura Bitters', '1 dash Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into coupe.', 'Lemon twist.'], 
        description: 'Named after the Brooklyn neighborhood.', 
        history: 'Another Brooklyn neighborhood variation, created by Michael McIlroy at Milk & Honey in 2006. It swaps the Maraschino/Amer Picon of the original Brooklyn for Yellow Chartreuse and Sweet Vermouth, adding a honeyed herbal note.',
        creator: 'Michael McIlroy (Milk & Honey)', 
        dateAdded: '2006-01-01', 
        flavorProfile: { Sweet: 5, Sour: 0, Bitter: 2, Boozy: 8, Herbal: 6, Fruity: 1, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'bentons-old-fashioned', 
        name: 'Benton\'s Old Fashioned', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Bacon-Washed Bourbon', '0.25 oz Maple Syrup', '2 dashes Angostura Bitters'], 
        instructions: ['Stir with ice.', 'Strain over large rock.', 'Orange twist.'], 
        description: 'Famous for using fat-washing technique with Benton\'s bacon.', 
        history: 'A watershed moment in molecular mixology, created by Don Lee at PDT (Please Don\'t Tell) in 2008. Lee used fat-washing to infuse Four Roses Bourbon with the smoky, savory flavor of Benton\'s Country Ham fat, pairing it with maple syrup for a breakfast-in-a-glass profile.',
        creator: 'Don Lee (PDT)', 
        dateAdded: '2008-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 1, Fruity: 0, Spicy: 1, Smoky: 3 } 
    },
    { 
        id: 'gin-basil-smash', 
        name: 'Gin Basil Smash', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Gin', '0.75 oz Lemon Juice', '0.75 oz Simple Syrup', '12 Basil Leaves'], 
        instructions: ['Muddle basil aggressively.', 'Shake with ice.', 'Double strain over ice.'], 
        description: 'Bright green and peppery.', 
        history: 'Created by Joerg Meyer at Le Lion in Hamburg, Germany (2008). Meyer promoted the drink heavily on social media, making it one of the first "viral" cocktails. It requires aggressive muddling of the basil to release the chlorophyll, turning the drink a vibrant radioactive green.',
        creator: 'Joerg Meyer (Le Lion)', 
        dateAdded: '2008-01-01', 
        flavorProfile: { Sweet: 4, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 8, Fruity: 0, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'revolver', 
        name: 'Revolver', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Bourbon', '0.5 oz Coffee Liqueur', '2 dashes Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Flamed orange peel.'], 
        description: 'High-rye bourbon meets coffee.', 
        history: 'Created by Jon Santer in San Francisco around 2004. A simple but effective riff on the Manhattan template, swapping vermouth for coffee liqueur (originally Tia Maria). The flamed orange peel garnish is essential, providing a burnt citrus oil nose that bridges the whiskey and coffee.',
        creator: 'Jon Santer (Bruno\'s)', 
        dateAdded: '2004-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 3, Boozy: 7, Herbal: 0, Fruity: 0, Spicy: 1, Smoky: 0 } 
    },

    // === SOURS & DAISIES ===
    { 
        id: 'whiskey-sour', 
        name: 'Whiskey Sour', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Bourbon', '0.75 oz Lemon Juice', '0.75 oz Simple Syrup', '1 Egg White (optional)'], 
        instructions: ['Dry shake (if egg).', 'Shake with ice.', 'Strain into rocks glass.', 'Angostura drops.'], 
        description: 'First written record in 1862. The grandfather of all sours.', 
        history: 'First printed in Jerry Thomas\'s 1862 guide, though sailors had been drinking spirits with citrus and sugar to fight scurvy for a century prior. The egg white addition came later, creating a silky texture. It is the fundamental template for almost all shaken cocktails.',
        creator: 'Jerry Thomas', 
        dateAdded: '1862-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 1, Boozy: 5, Herbal: 0, Fruity: 1, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'daiquiri', 
        name: 'Daiquiri', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz White Rum', '1 oz Lime Juice', '0.75 oz Simple Syrup'], 
        instructions: ['Shake with ice.', 'Double strain into coupe.'], 
        description: 'Named after the beach/mine in Cuba. Popularized by Hemingway and JFK.', 
        history: 'Invented by American mining engineer Jennings Cox in Cuba around 1898 when he ran out of gin. He mixed the local Bacardi rum with lime and sugar. It remained a local specialty until Admiral Lucius Johnson brought it to the Army & Navy Club in DC in 1909.',
        creator: 'Jennings Cox', 
        dateAdded: '1898-01-01', 
        flavorProfile: { Sweet: 5, Sour: 7, Bitter: 0, Boozy: 5, Herbal: 0, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'margarita', 
        name: 'Margarita', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Blanco Tequila', '1 oz Lime Juice', '0.75 oz Cointreau', 'Salt Rim'], 
        instructions: ['Shake with ice.', 'Strain into salt-rimmed rocks glass over ice.'], 
        description: 'A Tequila Daisy ("Margarita" is Spanish for Daisy).', 
        history: 'The origin is hotly disputed, but it is almost certainly a variation of the "Daisy" cocktail (Spirit, Citrus, Curacao/Grenadine, Soda). "Margarita" is the Spanish word for Daisy. It likely evolved during Prohibition when Americans flocked to Mexico for alcohol.',
        creator: 'Disputed', 
        dateAdded: '1938-01-01', 
        flavorProfile: { Sweet: 4, Sour: 7, Bitter: 1, Boozy: 6, Herbal: 2, Fruity: 3, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'tommys-margarita', 
        name: 'Tommy\'s Margarita', 
        category: 'Modern Classics', 
        ingredients: ['2 oz Blanco Tequila', '1 oz Lime Juice', '0.5 oz Agave Nectar'], 
        instructions: ['Shake with ice.', 'Strain over ice.', 'No salt rim (typically).'], 
        description: 'Replaces Triple Sec with Agave Nectar for a purer agave profile.', 
        history: 'Created by Julio Bermejo at Tommy\'s Mexican Restaurant in San Francisco in 1990. Bermejo removed the orange liqueur (Cointreau) found in the classic Margarita and replaced it with agave nectar, arguing that a tequila drink should be sweetened by the plant it comes from.',
        creator: 'Julio Bermejo (Tommy\'s Mexican Restaurant)', 
        dateAdded: '1990-01-01', 
        flavorProfile: { Sweet: 4, Sour: 7, Bitter: 0, Boozy: 6, Herbal: 3, Fruity: 2, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'sidecar', 
        name: 'Sidecar', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Cognac', '0.75 oz Cointreau', '0.75 oz Lemon Juice', 'Sugared Rim'], 
        instructions: ['Shake with ice.', 'Strain into sugar-rimmed coupe.'], 
        description: 'Definitive Brandy sour.', 
        history: 'Likely created at Harry\'s New York Bar in Paris or Buck\'s Club in London around the end of WWI. The legend goes it was named for an eccentric army captain who was driven to the bar in the sidecar of a motorcycle. It is essentially a Brandy Daisy.',
        creator: 'Harry\'s New York Bar (Paris)', 
        dateAdded: '1922-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 0, Fruity: 3, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'gimlet', 
        name: 'Gimlet', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Gin', '0.75 oz Lime Juice', '0.75 oz Simple Syrup'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'Originally made with Rose\'s Lime Cordial to prevent scurvy.', 
        history: 'Named after Surgeon Admiral Sir Thomas Gimlette of the Royal Navy, who added lime cordial to the sailors\' daily gin ration to prevent scurvy. The original used Rose\'s Lime Cordial (preserved with sugar), but modern versions typically use fresh lime and syrup.',
        creator: 'Royal Navy', 
        dateAdded: '1928-01-01', 
        flavorProfile: { Sweet: 4, Sour: 7, Bitter: 1, Boozy: 5, Herbal: 4, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'bees-knees', 
        name: 'Bee\'s Knees', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Gin', '0.75 oz Lemon Juice', '0.75 oz Honey Syrup'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'Prohibition classic using honey to mask bathtub gin.', 
        history: 'A Prohibition-era classic credited to Frank Meier at the Ritz Paris (1921). The phrase "the bee\'s knees" was 1920s slang for "the best." The honey and lemon were originally used to mask the harsh flavor of poor-quality bathtub gin available at the time.',
        creator: 'Frank Meier (Ritz Paris)', 
        dateAdded: '1921-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 3, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'last-word', 
        name: 'The Last Word', 
        category: 'Sours & Daisies', 
        ingredients: ['0.75 oz Gin', '0.75 oz Green Chartreuse', '0.75 oz Maraschino Liqueur', '0.75 oz Lime Juice'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'A Detroit Athletic Club original that was forgotten until rediscovered in 2004.', 
        history: 'Created at the Detroit Athletic Club in 1915 by Frank Fogarty. It fell into complete obscurity after WWII until Murray Stenson found the recipe in a 1951 cocktail book and put it on the menu at the Zig Zag Café in Seattle in 2004, sparking the cocktail renaissance.',
        creator: 'Frank Fogarty', 
        dateAdded: '1915-01-01', 
        flavorProfile: { Sweet: 6, Sour: 5, Bitter: 1, Boozy: 6, Herbal: 8, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'corpse-reviver-2', 
        name: 'Corpse Reviver #2', 
        category: 'Sours & Daisies', 
        ingredients: ['0.75 oz Gin', '0.75 oz Lillet Blanc', '0.75 oz Cointreau', '0.75 oz Lemon Juice', 'Absinthe (Rinse)'], 
        instructions: ['Shake with ice.', 'Strain into rinsed coupe.'], 
        description: '"Four of these in swift succession will unrevive the corpse again." - Harry Craddock.', 
        history: 'Part of a family of "hair of the dog" hangover cures. The #2 is the most famous, appearing in the Savoy Cocktail Book (1930). Harry Craddock famously noted, "Four of these taken in swift succession will unrevive the corpse again."',
        creator: 'Harry Craddock (Savoy)', 
        dateAdded: '1930-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 3, Fruity: 3, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'aviation', 
        name: 'Aviation', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Gin', '0.5 oz Maraschino Liqueur', '0.25 oz Crème de Violette', '0.75 oz Lemon Juice'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'Famed for its sky-blue color, though the violette was often omitted for decades.', 
        history: 'First published in Hugo Ensslin\'s 1916 "Recipes for Mixed Drinks". For decades, the Crème de Violette was omitted because it was unavailable in the US, turning the drink into a simple gin sour. The reintroduction of Violette in 2007 restored its signature sky-blue hue.',
        creator: 'Hugo Ensslin', 
        dateAdded: '1916-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 2, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'pisco-sour', 
        name: 'Pisco Sour', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Pisco', '1 oz Lime Juice', '0.75 oz Simple Syrup', '1 Egg White', 'Angostura Bitters'], 
        instructions: ['Dry shake.', 'Shake with ice.', 'Strain into coupe.', 'Bitters on foam.'], 
        description: 'Created by an American bartender in Lima, Peru.', 
        history: 'Invented by Victor Morris, an American bartender working in Lima, Peru, in the 1920s. It adapts the Whiskey Sour template to the local Peruvian grape brandy, Pisco. The Angostura bitters are applied as a garnish on the foam to provide aroma and mask the "wet dog" smell of egg white.',
        creator: 'Victor Morris', 
        dateAdded: '1920-01-01', 
        flavorProfile: { Sweet: 5, Sour: 7, Bitter: 1, Boozy: 5, Herbal: 1, Fruity: 4, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'clover-club', 
        name: 'Clover Club', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Gin', '0.75 oz Lemon Juice', '0.5 oz Raspberry Syrup', '1 Egg White'], 
        instructions: ['Dry shake.', 'Shake with ice.', 'Strain into coupe.'], 
        description: 'Named for the Philadelphia men\'s club.', 
        history: 'A pre-Prohibition classic dating back to 1896, named after a gentlemen\'s club in Philadelphia that met at the Bellevue-Stratford Hotel. It was once considered a "manly" drink before falling out of favor and being relegated to "girly drink" status—a reputation it has rightfully shaken off.',
        creator: 'George Boldt', 
        dateAdded: '1896-01-01', 
        flavorProfile: { Sweet: 5, Sour: 5, Bitter: 0, Boozy: 5, Herbal: 2, Fruity: 6, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'white-lady', 
        name: 'White Lady', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Gin', '0.75 oz Cointreau', '0.75 oz Lemon Juice', 'Egg White (optional)'], 
        instructions: ['Shake with ice.', 'Strain into coupe.'], 
        description: 'Originally made with Crème de Menthe, evolved to the gin sour we know.', 
        history: 'Harry MacElhone originally created this in 1919 with Creme de Menthe, but later changed the recipe to Gin/Cointreau/Lemon in 1929 at his bar in Paris. It is essentially a Gin Sidecar.',
        creator: 'Harry MacElhone', 
        dateAdded: '1919-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 2, Fruity: 3, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'southside', 
        name: 'Southside', 
        category: 'Sours & Daisies', 
        ingredients: ['2 oz Gin', '0.75 oz Lime Juice', '0.75 oz Simple Syrup', '6 Mint Leaves'], 
        instructions: ['Shake with ice.', 'Double strain into coupe.', 'Mint leaf.'], 
        description: 'Allegedly Al Capone\'s drink of choice. A gin Mojito served up.', 
        history: 'There are two origin stories: One claims it came from the Southside Sportsmen\'s Club on Long Island; the other claims it was the preferred drink of Al Capone\'s gang on the South Side of Chicago, using mint and citrus to mask the harshness of smuggled gin.',
        creator: '21 Club', 
        dateAdded: '1920-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 5, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },

    // === HIGHBALLS & FIZZES ===
    { 
        id: 'tom-collins', 
        name: 'Tom Collins', 
        category: 'Highballs & Fizzes', 
        ingredients: ['2 oz Old Tom Gin (or London Dry)', '1 oz Lemon Juice', '0.5 oz Simple Syrup', 'Soda Water'], 
        instructions: ['Build in highball glass with ice.', 'Top with soda.', 'Stir.'], 
        description: 'Based on the "Great Tom Collins Hoax" of 1874.', 
        history: 'Born from the "Great Tom Collins Hoax" of 1874, a viral prank where people would tell a friend that a man named Tom Collins was insulting them at a nearby bar. The agitated friend would rush to the bar asking for "Tom Collins," and the bartender would hand them this sour cocktail.',
        creator: 'Jerry Thomas', 
        dateAdded: '1876-01-01', 
        flavorProfile: { Sweet: 4, Sour: 5, Bitter: 0, Boozy: 4, Herbal: 2, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'gin-tonic', 
        name: 'Gin & Tonic', 
        category: 'Highballs & Fizzes', 
        ingredients: ['2 oz Gin', '4 oz Tonic Water'], 
        instructions: ['Build in glass with ice.', 'Squeeze lime wedge.'], 
        description: 'Created by the British East India Company to make quinine palatable.', 
        history: 'In the 1800s, British officers in India took quinine powder to prevent malaria. It was bitter, so they dissolved it in water and sugar (tonic) and added their daily gin ration. Winston Churchill famously said, "The gin and tonic has saved more Englishmen’s lives, and minds, than all the doctors in the Empire."',
        creator: 'British Army', 
        dateAdded: '1850-01-01', 
        flavorProfile: { Sweet: 3, Sour: 2, Bitter: 5, Boozy: 4, Herbal: 4, Fruity: 1, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'moscow-mule', 
        name: 'Moscow Mule', 
        category: 'Highballs & Fizzes', 
        ingredients: ['2 oz Vodka', '0.5 oz Lime Juice', '4 oz Ginger Beer'], 
        instructions: ['Build in copper mug with ice.', 'Garnish with lime.'], 
        description: 'Marketing invention to sell Smirnoff Vodka and Cock \'n Bull Ginger Beer.', 
        history: 'Created in 1941 at the Cock \'n Bull pub in LA. It was a marketing stunt between John Martin (Smirnoff owner, trying to sell vodka to whiskey-loving Americans) and Jack Morgan (pub owner, who had a surplus of house-made ginger beer). The copper mugs were added just because a girlfriend of theirs inherited a copper factory.',
        creator: 'Wes Price', 
        dateAdded: '1941-01-01', 
        flavorProfile: { Sweet: 4, Sour: 4, Bitter: 0, Boozy: 4, Herbal: 0, Fruity: 1, Spicy: 6, Smoky: 0 } 
    },
    { 
        id: 'dark-n-stormy', 
        name: 'Dark \'n\' Stormy', 
        category: 'Highballs & Fizzes', 
        ingredients: ['2 oz Black Rum (Goslings)', '0.5 oz Lime Juice', '4 oz Ginger Beer'], 
        instructions: ['Build in highball.', 'Float rum on top.'], 
        description: 'The national drink of Bermuda. Trademarked by Gosling\'s.', 
        history: 'Originating in Bermuda after WWI, this is one of the few trademarked cocktails in the world. Legally, a Dark \'n\' Stormy must be made with Gosling\'s Black Seal Rum. The name allegedly comes from a sailor who observed the muddy color resembled storm clouds.',
        creator: 'Gosling\'s', 
        dateAdded: '1920-01-01', 
        flavorProfile: { Sweet: 5, Sour: 4, Bitter: 0, Boozy: 5, Herbal: 0, Fruity: 1, Spicy: 6, Smoky: 0 } 
    },
    { 
        id: 'paloma', 
        name: 'Paloma', 
        category: 'Highballs & Fizzes', 
        ingredients: ['2 oz Blanco Tequila', '0.5 oz Lime Juice', '4 oz Grapefruit Soda', 'Salt Rim'], 
        instructions: ['Build in salt-rimmed glass with ice.', 'Top with soda.'], 
        description: 'More popular in Mexico than the Margarita.', 
        history: 'While Americans drink Margaritas, the Paloma ("Dove") is the most popular tequila cocktail in Mexico. Its origin is murky, but it is often attributed to Don Javier Delgado Corona of La Capilla bar in Tequila, Mexico, in the 1950s.',
        creator: 'Don Javier Delgado Corona', 
        dateAdded: '1950-01-01', 
        flavorProfile: { Sweet: 4, Sour: 5, Bitter: 2, Boozy: 5, Herbal: 2, Fruity: 4, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'french-75', 
        name: 'French 75', 
        category: 'Highballs & Fizzes', 
        ingredients: ['1 oz Gin', '0.5 oz Lemon Juice', '0.5 oz Simple Syrup', 'Champagne'], 
        instructions: ['Shake gin, lemon, syrup.', 'Strain into flute.', 'Top with champagne.'], 
        description: 'Named after the French 75mm field gun used in WWI. "Hits with precision."', 
        history: 'Named after the rapid-fire 75 millimeter field gun used by the French during World War I. The combination of gin and champagne was said to hit with the kick of the artillery piece. It was popularized in Harry MacElhone\'s "Harry\'s ABC of Mixing Cocktails".',
        creator: 'Harry MacElhone', 
        dateAdded: '1915-01-01', 
        flavorProfile: { Sweet: 4, Sour: 5, Bitter: 0, Boozy: 6, Herbal: 2, Fruity: 2, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'ramos-gin-fizz', 
        name: 'Ramos Gin Fizz', 
        category: 'Highballs & Fizzes', 
        ingredients: ['2 oz Gin', '0.5 oz Lemon Juice', '0.5 oz Lime Juice', '1 oz Simple Syrup', '1 oz Heavy Cream', '1 Egg White', '3 drops Orange Flower Water', 'Soda Water'], 
        instructions: ['Dry shake vigorously (2 mins).', 'Add ice, shake again.', 'Strain into tall glass.', 'Top with soda.'], 
        description: 'Famous for requiring a line of "shaker boys" to shake for 12 minutes.', 
        history: 'Invented by Henry C. Ramos at the Imperial Cabinet Saloon in New Orleans in 1888. It became so popular that during Mardi Gras, Ramos employed a line of 20 "shaker boys" who would pass the shaker down the line, shaking it for up to 12 minutes to achieve the legendary meringue-like stiffness.',
        creator: 'Henry C. Ramos', 
        dateAdded: '1888-01-01', 
        flavorProfile: { Sweet: 6, Sour: 4, Bitter: 0, Boozy: 4, Herbal: 3, Fruity: 2, Spicy: 0, Smoky: 0 } 
    },
    
    // === TIKI & TROPICAL ===
    { 
        id: 'mai-tai', 
        name: 'Mai Tai', 
        category: 'Tiki & Tropical', 
        ingredients: ['2 oz Aged Rum (Jamaican/Agricole Blend)', '0.75 oz Lime Juice', '0.5 oz Orange Curacao', '0.25 oz Orgeat', '0.25 oz Rich Syrup'], 
        instructions: ['Shake with crushed ice.', 'Pour unstrained into glass.', 'Float mint sprig and spent lime shell.'], 
        description: 'Means "Out of this world" in Tahitian. The single most bastardized drink in history.', 
        history: 'Created by Victor "Trader Vic" Bergeron in 1944 for friends visiting from Tahiti. Upon tasting it, one exclaimed "Maita\'i roa ae!" (Out of this world! The best!), giving the drink its name. It is widely considered the holy grail of Tiki drinks.',
        creator: 'Trader Vic', 
        dateAdded: '1944-01-01', 
        flavorProfile: { Sweet: 6, Sour: 6, Bitter: 0, Boozy: 7, Herbal: 1, Fruity: 4, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'jungle-bird', 
        name: 'Jungle Bird', 
        category: 'Tiki & Tropical', 
        ingredients: ['1.5 oz Black Strap Rum', '0.75 oz Campari', '1.5 oz Pineapple Juice', '0.5 oz Lime Juice', '0.5 oz Demerara Syrup'], 
        instructions: ['Shake with ice.', 'Strain over fresh ice.'], 
        description: 'A rare Tiki drink that utilizes bitter Campari.', 
        history: 'Created in 1978 at the Aviary Bar in the Kuala Lumpur Hilton. It was originally served as a welcome drink in a porcelain bird vessel. It is unique in the Tiki canon for its use of Campari, bridging the gap between tropical and bitter aperitif styles.',
        creator: 'Jeffrey Ong (Aviary Bar, KL)', 
        dateAdded: '1978-01-01', 
        flavorProfile: { Sweet: 6, Sour: 4, Bitter: 5, Boozy: 6, Herbal: 2, Fruity: 7, Spicy: 0, Smoky: 0 } 
    },
    { 
        id: 'zombie', 
        name: 'Zombie', 
        category: 'Tiki & Tropical', 
        ingredients: ['1.5 oz Gold Rum', '1.5 oz Dark Rum', '1 oz 151 Proof Rum', '0.75 oz Lime Juice', '0.5 oz Falernum', '0.5 oz Grapefruit Juice', '1 tsp Cinnamon Syrup', '1 tsp Grenadine', '1 dash Angostura'], 
        instructions: ['Blend with 6oz crushed ice.', 'Pour into tall glass.'], 
        description: 'The drink that started the Tiki craze. Limit 2 per customer.', 
        history: 'Invented by Donn Beach in 1934. Legend says he made it for a hungover businessman to help him get through a meeting. The man returned days later saying he felt like the "living dead"—a zombie. It was so potent that Don the Beachcomber limited customers to two per night.',
        creator: 'Donn Beach', 
        dateAdded: '1934-01-01', 
        flavorProfile: { Sweet: 7, Sour: 5, Bitter: 2, Boozy: 10, Herbal: 3, Fruity: 5, Spicy: 4, Smoky: 0 } 
    },
    { 
        id: 'painkiller', 
        name: 'Painkiller', 
        category: 'Tiki & Tropical', 
        ingredients: ['2 oz Pusser\'s Rum', '4 oz Pineapple Juice', '1 oz Orange Juice', '1 oz Cream of Coconut'], 
        instructions: ['Shake with ice.', 'Pour over crushed ice.', 'Grate nutmeg on top.'], 
        description: 'The BVI\'s answer to the Piña Colada.', 
        history: 'Created in the 1970s at the Soggy Dollar Bar in the British Virgin Islands (named because sailors had to swim to shore, getting their dollars soggy). It is structurally similar to a Piña Colada but uses Pusser\'s Rum and adds orange juice and nutmeg.',
        creator: 'Soggy Dollar Bar', 
        dateAdded: '1971-01-01', 
        flavorProfile: { Sweet: 8, Sour: 2, Bitter: 0, Boozy: 5, Herbal: 0, Fruity: 9, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'jet-pilot', 
        name: 'Jet Pilot', 
        category: 'Tiki & Tropical', 
        ingredients: ['1 oz Jamaican Rum', '0.75 oz Gold Rum', '0.75 oz 151 Rum', '0.5 oz Lime Juice', '0.5 oz Grapefruit Juice', '0.5 oz Cinnamon Syrup', '0.5 oz Falernum', '1 dash Angostura', 'Absinthe (Rinse/Dash)'], 
        instructions: ['Blend with crushed ice.', 'Garnish with cherry and mint.'], 
        description: 'A riff on the Test Pilot, complex and dangerous.', 
        history: 'A classic from the "Space Age" era of Tiki, created by Steve Crane at the Luau in Beverly Hills (1958). It was designed as a counter-strike to Donn Beach\'s "Test Pilot," upping the complexity and alcohol content.',
        creator: 'Steve Crane (Luau)', 
        dateAdded: '1958-01-01', 
        flavorProfile: { Sweet: 6, Sour: 5, Bitter: 2, Boozy: 9, Herbal: 4, Fruity: 4, Spicy: 6, Smoky: 0 } 
    },
    { 
        id: 'three-dots', 
        name: 'Three Dots and a Dash', 
        category: 'Tiki & Tropical', 
        ingredients: ['1.5 oz Rhum Agricole', '0.5 oz Blended Aged Rum', '0.5 oz Lime Juice', '0.5 oz Orange Juice', '0.5 oz Honey Syrup', '0.25 oz Falernum', '0.25 oz Allspice Dram', 'Angostura'], 
        instructions: ['Flash blend with crushed ice.', 'Garnish with 3 cherries and a pineapple stick.'], 
        description: 'Morse code for "V" (Victory) in WWII.', 
        history: 'Created by Donn Beach during World War II. The garnish of three cherries (dots) and a pineapple stick (dash) represents the Morse code letter "V" for Victory. It is one of the few Donn Beach originals that showcases Rhum Agricole.',
        creator: 'Donn Beach', 
        dateAdded: '1945-01-01', 
        flavorProfile: { Sweet: 6, Sour: 5, Bitter: 2, Boozy: 7, Herbal: 3, Fruity: 5, Spicy: 7, Smoky: 0 } 
    },
    { 
        id: 'chartreuse-swizzle', 
        name: 'Chartreuse Swizzle', 
        category: 'Modern Classics', 
        ingredients: ['1.5 oz Green Chartreuse', '1 oz Pineapple Juice', '0.75 oz Lime Juice', '0.5 oz Falernum'], 
        instructions: ['Build in glass with crushed ice.', 'Swizzle vigorously.', 'Top with more ice and mint.'], 
        description: 'A modern tribute to the swizzle, showcasing Chartreuse.', 
        history: 'Created by Marco Dionysos at Smuggler\'s Cove in San Francisco (2003). It is a modern classic that proves Green Chartreuse can work as a base spirit in a tropical context, pairing its herbal intensity with pineapple and falernum.',
        creator: 'Marco Dionysos', 
        dateAdded: '2003-01-01', 
        flavorProfile: { Sweet: 6, Sour: 5, Bitter: 1, Boozy: 7, Herbal: 9, Fruity: 5, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'saturn', 
        name: 'Saturn', 
        category: 'Tiki & Tropical', 
        ingredients: ['1.5 oz Gin', '0.5 oz Lemon Juice', '0.5 oz Passion Fruit Syrup', '0.25 oz Orgeat', '0.25 oz Falernum'], 
        instructions: ['Flash blend with crushed ice.', 'Pour into coupe.'], 
        description: 'A rare Gin-based Tiki classic. Won the 1967 IBA World Championship.', 
        history: 'Created by J. "Popo" Galsini in 1967, winning the IBA World Cocktail Championship. It is named after the Saturn rocket that took Apollo astronauts to space. It stands out in the Tiki genre for using Gin instead of Rum, creating a lighter, more floral tropical drink.',
        creator: 'J. "Popo" Galsini', 
        dateAdded: '1967-01-01', 
        flavorProfile: { Sweet: 7, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 3, Fruity: 7, Spicy: 2, Smoky: 0 } 
    },
    { 
        id: 'singapore-sling', 
        name: 'Singapore Sling', 
        category: 'Tiki & Tropical', 
        ingredients: ['1.5 oz Gin', '0.5 oz Cherry Heering', '0.25 oz Cointreau', '0.25 oz Benedictine', '4 oz Pineapple Juice', '0.5 oz Lime Juice', 'Grenadine', 'Angostura'], 
        instructions: ['Shake with ice.', 'Strain into tall glass.'], 
        description: 'Created at the Raffles Hotel Long Bar.', 
        history: 'Invented by Ngiam Tong Boon at the Long Bar in Raffles Hotel, Singapore, around 1915. It was originally designed as a socially acceptable punch for women to drink in public, disguised as fruit juice by its pink color.',
        creator: 'Ngiam Tong Boon', 
        dateAdded: '1915-01-01', 
        flavorProfile: { Sweet: 7, Sour: 4, Bitter: 1, Boozy: 5, Herbal: 3, Fruity: 8, Spicy: 1, Smoky: 0 } 
    },
    { 
        id: 'navy-grog', 
        name: 'Navy Grog', 
        category: 'Tiki & Tropical', 
        ingredients: ['1 oz Light Rum', '1 oz Gold Rum', '1 oz Dark Rum', '0.75 oz Lime Juice', '0.75 oz Grapefruit Juice', '1 oz Honey Syrup', 'Soda Water'], 
        instructions: ['Shake with ice.', 'Strain over ice cone.'], 
        description: 'Frank Sinatra\'s favorite Tiki drink.', 
        history: 'One of Donn Beach\'s "Holy Trinity" of heavy rum drinks. It was a favorite of Frank Sinatra, who often visited Don the Beachcomber\'s Palm Springs location. The signature ice cone (with a straw hole through the middle) is a hallmark of proper service.',
        creator: 'Donn Beach', 
        dateAdded: '1941-01-01', 
        flavorProfile: { Sweet: 5, Sour: 6, Bitter: 1, Boozy: 9, Herbal: 1, Fruity: 3, Spicy: 0, Smoky: 0 } 
    },

    // === ZERO-PROOF ===
    { 
        id: 'virgin-mojito', 
        name: 'Virgin Mojito', 
        category: 'Zero-Proof', 
        ingredients: ['8 Mint Leaves', '0.75 oz Lime Juice', '0.75 oz Simple Syrup', '4 oz Soda Water'], 
        instructions: ['Muddle mint lightly with syrup.', 'Add lime and ice.', 'Top with soda.', 'Stir.'], 
        description: 'All the refreshment, none of the buzz.', 
        history: 'Also known as the "Nojito," this mocktail preserves the core refreshing elements of the Cuban classic—lime, mint, and sugar—proving that alcohol is not necessary for a balanced, herbal, and refreshing drink.',
        creator: 'Classic', 
        dateAdded: '2025-01-01', 
        flavorProfile: { Sweet: 4, Sour: 4, Bitter: 0, Boozy: 0, Herbal: 6, Fruity: 1, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 60, carbs: 15, abv: 0 } 
    },
    { 
        id: 'shirley-temple', 
        name: 'Shirley Temple', 
        category: 'Zero-Proof', 
        ingredients: ['4 oz Ginger Ale', '0.5 oz Grenadine', '0.25 oz Lime Juice'], 
        instructions: ['Build in tall glass over ice.', 'Stir.', 'Garnish with cherry.'], 
        description: 'Created for the child actress at Chasen\'s, Beverly Hills.', 
        history: 'Invented in the 1930s at Chasen\'s in Beverly Hills for child actress Shirley Temple, so she could have a fancy drink while dining with her parents. Temple herself reportedly disliked the drink, calling it "too sweet." It remains the most famous mocktail in history.',
        creator: 'Chasen\'s', 
        dateAdded: '1930-01-01', 
        flavorProfile: { Sweet: 7, Sour: 2, Bitter: 0, Boozy: 0, Herbal: 0, Fruity: 4, Spicy: 2, Smoky: 0 }, 
        nutrition: { calories: 90, carbs: 22, abv: 0 } 
    },
    { 
        id: 'phony-negroni', 
        name: 'Phony Negroni', 
        category: 'Zero-Proof', 
        ingredients: ['1 oz NA Gin', '1 oz NA Bitter (e.g. Giffard)', '1 oz NA Sweet Vermouth'], 
        instructions: ['Stir with ice.', 'Strain over rock.', 'Orange peel.'], 
        description: 'Convincing alcohol-free aperitif.', 
        history: 'A product of the modern "Sober Curious" movement. With the rise of high-quality non-alcoholic spirits like Lyre\'s, Seedlip, and Giffard, the NA Negroni (often called the "Phony Negroni") has become a standard for those seeking complex bitterness without the ethanol.',
        creator: 'Modern Classic', 
        dateAdded: '2025-01-01', 
        flavorProfile: { Sweet: 4, Sour: 0, Bitter: 6, Boozy: 0, Herbal: 5, Fruity: 2, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 45, carbs: 10, abv: 0 } 
    },
    { 
        id: 'arnold-palmer', 
        name: 'Arnold Palmer', 
        category: 'Zero-Proof', 
        ingredients: ['3 oz Iced Tea', '3 oz Lemonade'], 
        instructions: ['Build in tall glass over ice.', 'Stir.'], 
        description: 'The golfer\'s favorite refresher.', 
        history: 'Named after the legendary golfer who was known to request a mix of iced tea and lemonade at country clubs. He once ordered it at a bar in Palm Springs, a woman nearby overheard and said "I\'ll have that Arnold Palmer drink," and the name stuck.',
        creator: 'Arnold Palmer', 
        dateAdded: '1960-01-01', 
        flavorProfile: { Sweet: 5, Sour: 4, Bitter: 2, Boozy: 0, Herbal: 3, Fruity: 1, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 50, carbs: 12, abv: 0 } 
    },
    
    // === LOW-ABV / SESSION (5-15% ABV) ===
    { 
        id: 'garibaldi', 
        name: 'Garibaldi', 
        category: 'Low-ABV', 
        ingredients: ['1.5 oz Campari', '4 oz Fluffy Orange Juice'], 
        instructions: ['Build in highball glass.', 'Add ice.', 'Stir gently to keep foam.'], 
        description: 'Named after the unifier of Italy. Perfected by Dante NYC.', 
        history: 'Named after Giuseppe Garibaldi, a general who contributed to the unification of Italy. The red Campari represents the North, and the oranges represent Sicily in the South. The drink was revived and perfected by Dante in NYC, who use high-speed juicers to make the orange juice "fluffy".',
        creator: 'Dante NYC', 
        dateAdded: '2015-01-01', 
        flavorProfile: { Sweet: 5, Sour: 3, Bitter: 5, Boozy: 2, Herbal: 3, Fruity: 6, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 150, carbs: 15, abv: 6 } 
    },
    { 
        id: 'bicyclette', 
        name: 'Bicyclette', 
        category: 'Low-ABV', 
        ingredients: ['2 oz Campari', '2 oz Dry White Wine', 'Soda Water'], 
        instructions: ['Build in wine glass over ice.', 'Top with splash of soda.', 'Lemon twist.'], 
        description: 'A French favorite, supposedly causing older men to wobble on their bicycles.', 
        history: 'A popular aperitif in France and Italy. The name "Bicyclette" allegedly comes from older Italian men who would drink these at cafes before wobbling home on their bicycles. It is a lighter, wine-based alternative to the Americano.',
        creator: 'Classic', 
        dateAdded: '1950-01-01', 
        flavorProfile: { Sweet: 3, Sour: 2, Bitter: 6, Boozy: 3, Herbal: 4, Fruity: 2, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 130, carbs: 8, abv: 9 } 
    },
    { 
        id: 'aperol-spritz', 
        name: 'Aperol Spritz', 
        category: 'Low-ABV', 
        ingredients: ['2 oz Aperol', '3 oz Prosecco', '1 oz Soda Water'], 
        instructions: ['Build in wine glass with ice.', 'Orange slice.'], 
        description: 'The drink of Venetian summers.', 
        history: 'Originating in the Veneto region of Italy, the Spritz dates back to the Austrian Empire when soldiers would dilute Italian wine with a "spritz" (spray) of water. The addition of Aperol became popular in the 1950s, creating the iconic sunset-colored drink we know today.',
        creator: 'Padua, Italy', 
        dateAdded: '1950-01-01', 
        flavorProfile: { Sweet: 5, Sour: 2, Bitter: 3, Boozy: 3, Herbal: 2, Fruity: 4, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 160, carbs: 12, abv: 9 } 
    },
    { 
        id: 'port-tonic', 
        name: 'Port & Tonic', 
        category: 'Low-ABV', 
        ingredients: ['2 oz White Port', '4 oz Tonic Water'], 
        instructions: ['Build in highball over ice.', 'Stir.', 'Lemon wheel and mint.'], 
        description: 'The national refresher of Portugal.', 
        history: 'Also known as "Porto Tonico," this is the standard aperitif in Portugal, particularly in Porto. Using Dry White Port (which is less sweet than Ruby), it offers a nutty, complex alternative to the Gin & Tonic with significantly less alcohol.',
        creator: 'Classic', 
        dateAdded: '1950-01-01', 
        flavorProfile: { Sweet: 4, Sour: 1, Bitter: 2, Boozy: 3, Herbal: 1, Fruity: 3, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 140, carbs: 12, abv: 6 } 
    },
    { 
        id: 'michelada', 
        name: 'Michelada', 
        category: 'Low-ABV', 
        ingredients: ['12 oz Light Mexican Beer', '1 oz Lime Juice', '2 dashes Hot Sauce', '2 dashes Worcestershire', 'Tajin Rim'], 
        instructions: ['Rim glass with Tajin.', 'Add lime and sauces.', 'Add ice and beer.', 'Stir.'], 
        description: '"Mi chela helada" (My cold beer).', 
        history: 'A contraction of "Mi chela helada" (My cold beer). It is a Mexican "Cerveza Preparada". Origins are anecdotal, but one story points to Michel Ésper at Club Deportivo Potosino in the 1960s, who always ordered his beer with lime, salt, and ice.',
        creator: 'Classic', 
        dateAdded: '1960-01-01', 
        flavorProfile: { Sweet: 1, Sour: 5, Bitter: 2, Boozy: 2, Herbal: 0, Fruity: 1, Spicy: 6, Smoky: 0 }, 
        nutrition: { calories: 140, carbs: 12, abv: 4 } 
    },
    { 
        id: 'bamboo', 
        name: 'Bamboo', 
        category: 'Low-ABV', 
        ingredients: ['1.5 oz Dry Sherry', '1.5 oz Dry Vermouth', '1 dash Angostura', '1 dash Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into coupe.', 'Lemon twist.'], 
        description: 'Created for the railroad tycoon Cornelius Vanderbilt.', 
        history: 'Created by Louis Eppinger at the Grand Hotel in Yokohama, Japan, in the 1890s. It was popularized in the US when served to railroad tycoon Cornelius Vanderbilt. It is essentially a Martini without the Gin, using Sherry for a nutty, saline profile.',
        creator: 'Louis Eppinger', 
        dateAdded: '1890-01-01', 
        flavorProfile: { Sweet: 2, Sour: 1, Bitter: 2, Boozy: 4, Herbal: 3, Fruity: 2, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 90, carbs: 4, abv: 15 } 
    },
    { 
        id: 'adonis', 
        name: 'Adonis', 
        category: 'Low-ABV', 
        ingredients: ['1.5 oz Fino Sherry', '1.5 oz Sweet Vermouth', '2 dashes Orange Bitters'], 
        instructions: ['Stir with ice.', 'Strain into coupe.', 'Orange peel.'], 
        description: 'Named after the first Broadway musical to run for over 500 performances.', 
        history: 'Created in 1884 to celebrate the success of the Broadway musical "Adonis," which was the first show to run for more than 500 performances. It is a lower-ABV relative of the Bamboo, using Sweet Vermouth instead of Dry for a richer, more herbal profile.',
        creator: 'Waldorf-Astoria', 
        dateAdded: '1884-01-01', 
        flavorProfile: { Sweet: 4, Sour: 1, Bitter: 2, Boozy: 4, Herbal: 3, Fruity: 2, Spicy: 1, Smoky: 0 }, 
        nutrition: { calories: 100, carbs: 7, abv: 15 } 
    },
    { 
        id: 'sherry-cobbler', 
        name: 'Sherry Cobbler', 
        category: 'Low-ABV', 
        ingredients: ['3 oz Amontillado Sherry', '0.5 oz Simple Syrup', '2 Orange Slices'], 
        instructions: ['Muddle orange and syrup.', 'Add sherry and ice.', 'Shake.', 'Pour over crushed ice.'], 
        description: 'The drink that popularized the drinking straw in the 1830s.', 
        history: 'One of the most popular drinks of the 19th century (mentioned in Dickens\' Martin Chuzzlewit). It is credited with popularizing the drinking straw and the use of crushed ice. The name "Cobbler" likely refers to the cobblestone-like appearance of the ice pebbles.',
        creator: 'Classic', 
        dateAdded: '1830-01-01', 
        flavorProfile: { Sweet: 5, Sour: 2, Bitter: 1, Boozy: 4, Herbal: 1, Fruity: 5, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 130, carbs: 15, abv: 12 } 
    },
    { 
        id: 'americano', 
        name: 'Americano', 
        category: 'Low-ABV', 
        ingredients: ['1.5 oz Campari', '1.5 oz Sweet Vermouth', 'Soda Water'], 
        instructions: ['Build in rocks glass with ice.', 'Top with soda.', 'Orange twist.'], 
        description: 'Originally the "Milano-Torino". James Bond\'s very first drink order.', 
        history: 'Originally called the "Milano-Torino" (Campari from Milan, Vermouth from Turin). It was renamed the Americano because it was popular with American tourists escaping Prohibition. It was the first drink ordered by James Bond in the novel Casino Royale.',
        creator: 'Gaspare Campari', 
        dateAdded: '1860-01-01', 
        flavorProfile: { Sweet: 4, Sour: 1, Bitter: 6, Boozy: 3, Herbal: 4, Fruity: 2, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 120, carbs: 12, abv: 10 } 
    },
    { 
        id: 'spaghett', 
        name: 'Spaghett', 
        category: 'Low-ABV', 
        ingredients: ['1 bottle Miller High Life', '1 oz Aperol', 'Splash Lemon Juice'], 
        instructions: ['Take sip of beer.', 'Pour Aperol and lemon into bottle.'], 
        description: 'A cult sensation from Baltimore.', 
        history: 'A modern cult classic created by Reed Kaestner at Wet City in Baltimore (2016). It is essentially an "Aperol Spritz for beer drinkers," turning the "Champagne of Beers" (Miller High Life) into a poor man\'s spritz. It became a viral sensation in the bartending community.',
        creator: 'Reed Kaestner (Wet City)', 
        dateAdded: '2016-01-01', 
        flavorProfile: { Sweet: 3, Sour: 2, Bitter: 3, Boozy: 3, Herbal: 2, Fruity: 2, Spicy: 0, Smoky: 0 }, 
        nutrition: { calories: 170, carbs: 16, abv: 6 } 
    }
];