
import { Cocktail, MasterIngredient } from './types';

export const INITIAL_MASTER_DATA: MasterIngredient[] = [
    // --- GIN ---
    { id: 'm-gin-gen', name: 'Gin', category: 'Spirit', subCategory: 'Gin', abv: 40, isGeneric: true, defaultFlavorNotes: 'Juniper-forward, herbal.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-gin-ld', name: 'London Dry Gin', category: 'Spirit', subCategory: 'Gin', abv: 40, isGeneric: true, defaultFlavorNotes: 'Dry, crisp, heavy juniper.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-gin-old', name: 'Old Tom Gin', category: 'Spirit', subCategory: 'Gin', abv: 40, isGeneric: true, defaultFlavorNotes: 'Slightly sweet, malty.', nutritionEstimate: { caloriesPerOz: 70, carbsPerOz: 2 } },
    { id: 'm-gin-plym', name: 'Plymouth Gin', category: 'Spirit', subCategory: 'Gin', abv: 41.2, isGeneric: false, defaultFlavorNotes: 'Earthy, less dry, citrus.', nutritionEstimate: { caloriesPerOz: 67, carbsPerOz: 0 } },
    { id: 'm-gin-hend', name: 'Hendrick\'s Gin', category: 'Spirit', subCategory: 'Gin', abv: 41.4, isGeneric: false, defaultFlavorNotes: 'Rose and cucumber.', nutritionEstimate: { caloriesPerOz: 68, carbsPerOz: 0 } },
    { id: 'm-gin-na', name: 'NA Gin', category: 'Spirit', subCategory: 'Non-Alcoholic', abv: 0, isGeneric: true, defaultFlavorNotes: 'Juniper and botanicals without alcohol.', nutritionEstimate: { caloriesPerOz: 5, carbsPerOz: 1 } },

    // --- WHISKEY ---
    { id: 'm-rye-gen', name: 'Rye Whiskey', category: 'Spirit', subCategory: 'Rye', abv: 45, isGeneric: true, defaultFlavorNotes: 'Spicy, grainy, dry finish.', nutritionEstimate: { caloriesPerOz: 72, carbsPerOz: 0 } },
    { id: 'm-bour-gen', name: 'Bourbon', category: 'Spirit', subCategory: 'Bourbon', abv: 40, isGeneric: true, defaultFlavorNotes: 'Sweet corn, caramel, vanilla.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-scot-blend', name: 'Blended Scotch', category: 'Spirit', subCategory: 'Scotch', abv: 40, isGeneric: true, defaultFlavorNotes: 'Smooth, malty, subtle smoke.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-scot-islay', name: 'Islay Scotch', category: 'Spirit', subCategory: 'Scotch', abv: 43, isGeneric: true, defaultFlavorNotes: 'Peat smoke, iodine, seaweed.', nutritionEstimate: { caloriesPerOz: 69, carbsPerOz: 0 } },
    { id: 'm-irish', name: 'Irish Whiskey', category: 'Spirit', subCategory: 'Whiskey', abv: 40, isGeneric: true, defaultFlavorNotes: 'Smooth, light, fruity.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-applejack', name: 'Applejack', category: 'Spirit', subCategory: 'Brandy', abv: 40, isGeneric: true, defaultFlavorNotes: 'Apple, oak, vanilla.', nutritionEstimate: { caloriesPerOz: 70, carbsPerOz: 0 } },

    // --- AGAVE ---
    { id: 'm-teq-bla', name: 'Blanco Tequila', category: 'Spirit', subCategory: 'Tequila', abv: 40, isGeneric: true, defaultFlavorNotes: 'Unaged, agave forward, citrus.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-teq-repo', name: 'Reposado Tequila', category: 'Spirit', subCategory: 'Tequila', abv: 40, isGeneric: true, defaultFlavorNotes: 'Lightly aged, vanilla hint.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-mez-vid', name: 'Mezcal', category: 'Spirit', subCategory: 'Mezcal', abv: 42, isGeneric: false, defaultFlavorNotes: 'Smoke, honey, roast agave.', nutritionEstimate: { caloriesPerOz: 70, carbsPerOz: 0 } },

    // --- RUM & SUGAR CANE ---
    { id: 'm-rum-white', name: 'White Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Light, clean, molasses.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-rum-aged', name: 'Aged Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Oak, vanilla, spice.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0.5 } },
    { id: 'm-rum-jam', name: 'Jamaican Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Funky, ripe banana, spice.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0.5 } },
    { id: 'm-rum-black', name: 'Black Strap Rum', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Dark molasses, coffee, treacle.', nutritionEstimate: { caloriesPerOz: 75, carbsPerOz: 4 } },
    { id: 'm-rum-agric', name: 'Rhum Agricole', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Grassy, vegetal, cane juice.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-rum-over', name: 'Overproof Rum', category: 'Spirit', subCategory: 'Rum', abv: 69, isGeneric: true, defaultFlavorNotes: 'Intense, hot, ester funk.', nutritionEstimate: { caloriesPerOz: 110, carbsPerOz: 0 } },
    { id: 'm-cachaca', name: 'Cachaça', category: 'Spirit', subCategory: 'Rum', abv: 40, isGeneric: true, defaultFlavorNotes: 'Grassy, raw cane.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },

    // --- BRANDY & COGNAC ---
    { id: 'm-cognac', name: 'Cognac', category: 'Spirit', subCategory: 'Brandy', abv: 40, isGeneric: true, defaultFlavorNotes: 'Grape, oak, leather.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },
    { id: 'm-pisco', name: 'Pisco', category: 'Spirit', subCategory: 'Brandy', abv: 40, isGeneric: true, defaultFlavorNotes: 'Floral, grape, earthy.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 0 } },

    // --- LIQUEURS & AMARI ---
    { id: 'm-am-camp', name: 'Campari', category: 'Spirit', subCategory: 'Amaro', abv: 24, isGeneric: false, defaultFlavorNotes: 'Intense bitter orange.', nutritionEstimate: { caloriesPerOz: 80, carbsPerOz: 8 } },
    { id: 'm-am-aper', name: 'Aperol', category: 'Spirit', subCategory: 'Amaro', abv: 11, isGeneric: false, defaultFlavorNotes: 'Sweet orange, gentian.', nutritionEstimate: { caloriesPerOz: 75, carbsPerOz: 9 } },
    { id: 'm-am-non', name: 'Amaro Nonino', category: 'Spirit', subCategory: 'Amaro', abv: 35, isGeneric: false, defaultFlavorNotes: 'Grappa based, orange, caramel.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 9 } },
    { id: 'm-am-fer', name: 'Fernet-Branca', category: 'Spirit', subCategory: 'Amaro', abv: 39, isGeneric: false, defaultFlavorNotes: 'Menthol, saffron, bitter.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 4 } },
    { id: 'm-am-aver', name: 'Averna', category: 'Spirit', subCategory: 'Amaro', abv: 29, isGeneric: false, defaultFlavorNotes: 'Cola, citrus, caramel.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 10 } },
    { id: 'm-am-cyn', name: 'Cynar', category: 'Spirit', subCategory: 'Amaro', abv: 16.5, isGeneric: false, defaultFlavorNotes: 'Artichoke, savory, vegetal.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 8 } },
    { id: 'm-am-suze', name: 'Suze', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: false, defaultFlavorNotes: 'Gentian, earthy, bitter.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 5 } },
    { id: 'm-am-na', name: 'NA Amaro', category: 'Spirit', subCategory: 'Non-Alcoholic', abv: 0, isGeneric: true, defaultFlavorNotes: 'Bitter herbs without alcohol.', nutritionEstimate: { caloriesPerOz: 20, carbsPerOz: 5 } },

    { id: 'm-liq-coint', name: 'Cointreau', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Clean orange triple sec.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 7 } },
    { id: 'm-liq-mar', name: 'Maraschino Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 32, isGeneric: true, defaultFlavorNotes: 'Funky cherry, almond.', nutritionEstimate: { caloriesPerOz: 105, carbsPerOz: 10 } },
    { id: 'm-liq-chart', name: 'Green Chartreuse', category: 'Spirit', subCategory: 'Liqueur', abv: 55, isGeneric: false, defaultFlavorNotes: 'Complex herbs, high proof.', nutritionEstimate: { caloriesPerOz: 110, carbsPerOz: 10 } },
    { id: 'm-liq-chart-y', name: 'Yellow Chartreuse', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Honey, saffron, softer herbs.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 11 } },
    { id: 'm-liq-kahl', name: 'Coffee Liqueur', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: true, defaultFlavorNotes: 'Sweet coffee, vanilla.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 11 } },
    { id: 'm-liq-stger', name: 'St. Germain', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: false, defaultFlavorNotes: 'Elderflower, lychee.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 11 } },
    { id: 'm-liq-bene', name: 'Benedictine', category: 'Spirit', subCategory: 'Liqueur', abv: 40, isGeneric: false, defaultFlavorNotes: 'Honey, herbs, spice.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 10 } },
    { id: 'm-liq-fal', name: 'Falernum', category: 'Spirit', subCategory: 'Liqueur', abv: 11, isGeneric: true, defaultFlavorNotes: 'Lime, ginger, clove, almond.', nutritionEstimate: { caloriesPerOz: 85, carbsPerOz: 12 } },
    { id: 'm-liq-abs', name: 'Absinthe', category: 'Spirit', subCategory: 'Liqueur', abv: 60, isGeneric: true, defaultFlavorNotes: 'Anise, fennel, wormwood.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 2 } },
    { id: 'm-liq-all', name: 'Allspice Dram', category: 'Spirit', subCategory: 'Liqueur', abv: 22, isGeneric: true, defaultFlavorNotes: 'Intense allspice berry.', nutritionEstimate: { caloriesPerOz: 90, carbsPerOz: 9 } },
    { id: 'm-liq-blue', name: 'Blue Curacao', category: 'Spirit', subCategory: 'Liqueur', abv: 25, isGeneric: true, defaultFlavorNotes: 'Orange, blue color.', nutritionEstimate: { caloriesPerOz: 95, carbsPerOz: 9 } },
    { id: 'm-liq-creme', name: 'Crème de Cacao', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: true, defaultFlavorNotes: 'Sweet chocolate.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 12 } },
    { id: 'm-liq-ment', name: 'Crème de Menthe', category: 'Spirit', subCategory: 'Liqueur', abv: 20, isGeneric: true, defaultFlavorNotes: 'Sweet mint.', nutritionEstimate: { caloriesPerOz: 100, carbsPerOz: 12 } },

    // --- VERMOUTH & WINE ---
    { id: 'm-ver-sweet', name: 'Sweet Vermouth', category: 'Spirit', subCategory: 'Vermouth', abv: 16, isGeneric: true, defaultFlavorNotes: 'Spiced wine, caramel.', nutritionEstimate: { caloriesPerOz: 45, carbsPerOz: 4 } },
    { id: 'm-ver-dry', name: 'Dry Vermouth', category: 'Spirit', subCategory: 'Vermouth', abv: 16, isGeneric: true, defaultFlavorNotes: 'Crisp, herbal, dry.', nutritionEstimate: { caloriesPerOz: 35, carbsPerOz: 1 } },
    { id: 'm-ver-lill', name: 'Lillet Blanc', category: 'Spirit', subCategory: 'Vermouth', abv: 17, isGeneric: false, defaultFlavorNotes: 'Honey, orange, quinine.', nutritionEstimate: { caloriesPerOz: 45, carbsPerOz: 4 } },
    { id: 'm-sherry', name: 'Sherry', category: 'Spirit', subCategory: 'Wine', abv: 15, isGeneric: true, defaultFlavorNotes: 'Nutty, oxidative.', nutritionEstimate: { caloriesPerOz: 40, carbsPerOz: 2 } },
    { id: 'm-port', name: 'Port', category: 'Spirit', subCategory: 'Wine', abv: 20, isGeneric: true, defaultFlavorNotes: 'Sweet red fruit.', nutritionEstimate: { caloriesPerOz: 50, carbsPerOz: 4 } },
    { id: 'm-ver-na', name: 'NA Vermouth', category: 'Spirit', subCategory: 'Non-Alcoholic', abv: 0, isGeneric: true, defaultFlavorNotes: 'Spiced juice blend.', nutritionEstimate: { caloriesPerOz: 15, carbsPerOz: 4 } },

    // --- MIXERS ---
    { id: 'm-mix-simp', name: 'Simple Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Pure sweetness.', nutritionEstimate: { caloriesPerOz: 50, carbsPerOz: 14 } },
    { id: 'm-mix-rich', name: 'Rich Simple Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Thick sweetness (2:1).', nutritionEstimate: { caloriesPerOz: 80, carbsPerOz: 20 } },
    { id: 'm-mix-honey', name: 'Honey Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Floral honey.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 17 } },
    { id: 'm-mix-agave', name: 'Agave Nectar', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Earthy sweetness.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 16 } },
    { id: 'm-mix-orgeat', name: 'Orgeat', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Almond, rose water.', nutritionEstimate: { caloriesPerOz: 65, carbsPerOz: 16 } },
    { id: 'm-mix-gren', name: 'Grenadine', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Pomegranate tartness.', nutritionEstimate: { caloriesPerOz: 55, carbsPerOz: 14 } },
    { id: 'm-mix-pass', name: 'Passion Fruit Syrup', category: 'Mixer', subCategory: 'Syrup', abv: 0, isGeneric: true, defaultFlavorNotes: 'Tropical tang.', nutritionEstimate: { caloriesPerOz: 60, carbsPerOz: 15 } },
    { id: 'm-mix-lem', name: 'Lemon Juice', category: 'Mixer', subCategory: 'Citrus', abv: 0, isGeneric: true, defaultFlavorNotes: 'Sour acidity.', nutritionEstimate: { caloriesPerOz: 8, carbsPerOz: 2 } },
    { id: 'm-mix-lim', name: 'Lime Juice', category: 'Mixer', subCategory: 'Citrus', abv: 0, isGeneric: true, defaultFlavorNotes: 'Tart, tropical.', nutritionEstimate: { caloriesPerOz: 8, carbsPerOz: 2 } },
    { id: 'm-mix-grap', name: 'Grapefruit Juice', category: 'Mixer', subCategory: 'Citrus', abv: 0, isGeneric: true, defaultFlavorNotes: 'Bitter, sour.', nutritionEstimate: { caloriesPerOz: 12, carbsPerOz: 3 } },
    { id: 'm-mix-pine', name: 'Pineapple Juice', category: 'Mixer', subCategory: 'Juice', abv: 0, isGeneric: true, defaultFlavorNotes: 'Sweet, foaming.', nutritionEstimate: { caloriesPerOz: 16, carbsPerOz: 4 } },
    { id: 'm-mix-ging', name: 'Ginger Beer', category: 'Mixer', subCategory: 'Soda', abv: 0, isGeneric: true, defaultFlavorNotes: 'Spicy carbonation.', nutritionEstimate: { caloriesPerOz: 12, carbsPerOz: 3 } },
    { id: 'm-mix-soda', name: 'Soda Water', category: 'Mixer', subCategory: 'Soda', abv: 0, isGeneric: true, defaultFlavorNotes: 'Bubbles.', nutritionEstimate: { caloriesPerOz: 0, carbsPerOz: 0 } },
    { id: 'm-mix-tonic', name: 'Tonic Water', category: 'Mixer', subCategory: 'Soda', abv: 0, isGeneric: true, defaultFlavorNotes: 'Bitter quinine.', nutritionEstimate: { caloriesPerOz: 11, carbsPerOz: 3 } },
];

export const INITIAL_RECIPES_DATA: Cocktail[] = [
    // === ANCESTRALS ===
    { id: 'old-fashioned', name: 'Old Fashioned', category: 'Ancestrals', ingredients: ['2 oz Bourbon or Rye', '0.25 oz Simple Syrup', '2 dashes Angostura Bitters'], instructions: ['Stir ingredients in rocks glass.', 'Add large ice cube.', 'Garnish with orange peel.'], description: 'The definition of a cocktail.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 0, Bitter: 4, Boozy: 8, Herbal: 2, Fruity: 1, Spicy: 2, Smoky: 0 } },
    { id: 'sazerac', name: 'Sazerac', category: 'Ancestrals', ingredients: ['2 oz Rye Whiskey', '0.25 oz Simple Syrup', '4 dashes Peychaud\'s Bitters', 'Absinthe (Rinse)'], instructions: ['Rinse glass with absinthe.', 'Stir rye, sugar, bitters with ice.', 'Strain into rinsed glass.', 'Express lemon peel.'], description: 'New Orleans classic.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 5, Fruity: 0, Spicy: 4, Smoky: 0 } },
    { id: 'improved-whiskey', name: 'Improved Whiskey Cocktail', category: 'Ancestrals', ingredients: ['2 oz Rye Whiskey', '0.25 oz Maraschino Liqueur', '1 dash Angostura Bitters', '1 dash Absinthe'], instructions: ['Stir with ice.', 'Strain into rocks glass with ice.', 'Lemon peel.'], description: 'An evolved Old Fashioned.', creator: 'Jerry Thomas', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 3, Fruity: 1, Spicy: 2, Smoky: 0 } },
    { id: 'monte-carlo', name: 'Monte Carlo', category: 'Ancestrals', ingredients: ['2 oz Rye Whiskey', '0.5 oz Benedictine', '2 dashes Angostura Bitters'], instructions: ['Stir with ice.', 'Strain into coupe or over large rock.', 'Lemon twist.'], description: 'Rye sweetened with herbal Benedictine.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 6, Fruity: 0, Spicy: 2, Smoky: 0 } },
    { id: 'oaxacan-old-fashioned', name: 'Oaxacan Old Fashioned', category: 'Modern Classics', ingredients: ['1.5 oz Reposado Tequila', '0.5 oz Mezcal', '1 tsp Agave Nectar', '2 dashes Angostura Bitters'], instructions: ['Stir ingredients with ice.', 'Strain over large rock.', 'Flamed orange peel.'], description: 'Smoky modern classic.', creator: 'Phil Ward', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 0, Bitter: 2, Boozy: 8, Herbal: 2, Fruity: 0, Spicy: 1, Smoky: 6 } },
    { id: 'bentons-old-fashioned', name: 'Benton\'s Old Fashioned', category: 'Modern Classics', ingredients: ['2 oz Bacon-Washed Bourbon', '0.25 oz Maple Syrup', '2 dashes Angostura Bitters'], instructions: ['Stir with ice.', 'Strain over large rock.', 'Orange twist.'], description: 'Savory, smoky, breakfast-in-a-glass.', creator: 'Don Lee', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 1, Fruity: 0, Spicy: 1, Smoky: 3 } },
    { id: 'revolver', name: 'Revolver', category: 'Modern Classics', ingredients: ['2 oz Bourbon', '0.5 oz Coffee Liqueur', '2 dashes Orange Bitters'], instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Flamed orange peel.'], description: 'Coffee-spiked Manhattan riff.', creator: 'San Francisco', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 3, Boozy: 7, Herbal: 0, Fruity: 0, Spicy: 1, Smoky: 0 } },

    // === SPIRIT-FORWARD (Vermouth/Amaro Based) ===
    { id: 'martini', name: 'Dry Martini', category: 'Spirit-Forward', ingredients: ['2.5 oz Gin', '0.5 oz Dry Vermouth', '1 dash Orange Bitters'], instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Lemon twist or olive.'], description: 'The king of cocktails.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 0, Sour: 0, Bitter: 2, Boozy: 9, Herbal: 5, Fruity: 0, Spicy: 0, Smoky: 0 } },
    { id: 'manhattan', name: 'Manhattan', category: 'Spirit-Forward', ingredients: ['2 oz Rye Whiskey', '1 oz Sweet Vermouth', '2 dashes Angostura Bitters'], instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Cherry garnish.'], description: 'Rich, spicy, and elegant.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 3, Boozy: 7, Herbal: 2, Fruity: 1, Spicy: 2, Smoky: 0 } },
    { id: 'negroni', name: 'Negroni', category: 'Spirit-Forward', ingredients: ['1 oz Gin', '1 oz Campari', '1 oz Sweet Vermouth'], instructions: ['Stir with ice.', 'Strain over large rock.', 'Orange peel.'], description: 'The perfect balance of bitter and sweet.', creator: 'Count Negroni', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 0, Bitter: 8, Boozy: 6, Herbal: 6, Fruity: 2, Spicy: 0, Smoky: 0 } },
    { id: 'boulevardier', name: 'Boulevardier', category: 'Spirit-Forward', ingredients: ['1.5 oz Bourbon', '1 oz Sweet Vermouth', '1 oz Campari'], instructions: ['Stir with ice.', 'Strain over large rock.', 'Orange twist.'], description: 'A whiskey Negroni.', creator: 'Harry\'s New York Bar', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 0, Bitter: 7, Boozy: 7, Herbal: 5, Fruity: 2, Spicy: 1, Smoky: 0 } },
    { id: 'vieux-carre', name: 'Vieux Carré', category: 'Spirit-Forward', ingredients: ['1 oz Rye Whiskey', '1 oz Cognac', '1 oz Sweet Vermouth', '1 tsp Benedictine', '2 dashes Peychaud\'s', '2 dashes Angostura'], instructions: ['Stir with ice.', 'Strain over ice in rocks glass.', 'Lemon twist.'], description: 'Complex New Orleans masterpiece.', creator: 'Hotel Monteleone', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 0, Bitter: 3, Boozy: 7, Herbal: 5, Fruity: 2, Spicy: 2, Smoky: 0 } },
    { id: 'martinez', name: 'Martinez', category: 'Spirit-Forward', ingredients: ['1.5 oz Old Tom Gin', '1.5 oz Sweet Vermouth', '1 tsp Maraschino Liqueur', '2 dashes Orange Bitters'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Orange twist.'], description: 'The missing link between Martini and Manhattan.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 4, Fruity: 2, Spicy: 0, Smoky: 0 } },
    { id: 'brooklyn', name: 'Brooklyn', category: 'Spirit-Forward', ingredients: ['2 oz Rye Whiskey', '1 oz Dry Vermouth', '0.25 oz Maraschino Liqueur', '0.25 oz Amer Picon (or substitute)'], instructions: ['Stir with ice.', 'Strain into chilled coupe.'], description: 'Dry and complex Manhattan variation.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 2, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 3, Fruity: 1, Spicy: 2, Smoky: 0 } },
    { id: 'red-hook', name: 'Red Hook', category: 'Modern Classics', ingredients: ['2 oz Rye Whiskey', '0.5 oz Punt e Mes', '0.5 oz Maraschino Liqueur'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Cherry.'], description: 'A modern classic Brooklyn riff.', creator: 'Enzo Errico', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 4, Boozy: 8, Herbal: 3, Fruity: 2, Spicy: 2, Smoky: 0 } },
    { id: 'greenpoint', name: 'Greenpoint', category: 'Modern Classics', ingredients: ['2 oz Rye Whiskey', '0.5 oz Yellow Chartreuse', '0.5 oz Sweet Vermouth', '1 dash Angostura Bitters', '1 dash Orange Bitters'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Lemon twist.'], description: 'Herbal and sweet Brooklyn variation.', creator: 'Milk & Honey', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 0, Bitter: 2, Boozy: 8, Herbal: 6, Fruity: 1, Spicy: 2, Smoky: 0 } },
    { id: 'toronto', name: 'Toronto', category: 'Spirit-Forward', ingredients: ['2 oz Canadian Whisky (or Rye)', '0.25 oz Fernet-Branca', '0.25 oz Simple Syrup', '2 dashes Angostura'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Orange twist.'], description: 'Whiskey with a bitter menthol kick.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 0, Bitter: 6, Boozy: 8, Herbal: 5, Fruity: 0, Spicy: 1, Smoky: 0 } },
    { id: 'white-negroni', name: 'White Negroni', category: 'Modern Classics', ingredients: ['1.5 oz Gin', '1 oz Lillet Blanc', '0.75 oz Suze'], instructions: ['Stir with ice.', 'Strain over large rock.', 'Lemon twist.'], description: 'Floral, bitter, and clear.', creator: 'Wayne Collins', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 7, Boozy: 6, Herbal: 6, Fruity: 2, Spicy: 0, Smoky: 0 } },
    { id: 'black-manhattan', name: 'Black Manhattan', category: 'Modern Classics', ingredients: ['2 oz Rye Whiskey', '1 oz Averna', '1 dash Angostura Bitters', '1 dash Orange Bitters'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Cherry.'], description: 'Substituting vermouth for amaro.', creator: 'Todd Smith', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 0, Bitter: 4, Boozy: 7, Herbal: 4, Fruity: 1, Spicy: 1, Smoky: 0 } },
    { id: 'hanky-panky', name: 'Hanky Panky', category: 'Spirit-Forward', ingredients: ['1.5 oz Gin', '1.5 oz Sweet Vermouth', '2 dashes Fernet-Branca'], instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Orange twist.'], description: 'A Savoy Hotel classic.', creator: 'Ada Coleman', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 5, Boozy: 7, Herbal: 5, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'bijou', name: 'Bijou', category: 'Spirit-Forward', ingredients: ['1 oz Gin', '1 oz Sweet Vermouth', '1 oz Green Chartreuse', '1 dash Orange Bitters'], instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Cherry and lemon twist.'], description: 'Jewel-toned and herbal.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 8, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'tipperary', name: 'Tipperary', category: 'Spirit-Forward', ingredients: ['1.5 oz Irish Whiskey', '1 oz Sweet Vermouth', '0.5 oz Green Chartreuse'], instructions: ['Stir with ice.', 'Strain into chilled coupe.', 'Orange twist.'], description: 'Irish Whiskey Bijou.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 0, Bitter: 2, Boozy: 7, Herbal: 6, Fruity: 1, Spicy: 1, Smoky: 0 } },
    { id: 'vesper', name: 'Vesper', category: 'Spirit-Forward', ingredients: ['3 oz Gin', '1 oz Vodka', '0.5 oz Lillet Blanc'], instructions: ['Shake (per Bond) or Stir (per quality) with ice.', 'Strain into goblet.', 'Lemon peel.'], description: 'Bond\'s invention.', creator: 'Ian Fleming', dateAdded: '2025-01-01', flavorProfile: { Sweet: 2, Sour: 0, Bitter: 2, Boozy: 9, Herbal: 3, Fruity: 1, Spicy: 0, Smoky: 0 } },

    // === SOURS & DAISIES ===
    { id: 'whiskey-sour', name: 'Whiskey Sour', category: 'Sours & Daisies', ingredients: ['2 oz Bourbon', '0.75 oz Lemon Juice', '0.75 oz Simple Syrup', '1 Egg White (optional)'], instructions: ['Dry shake (if egg).', 'Shake with ice.', 'Strain into rocks glass.', 'Angostura drops.'], description: 'Silky texture, perfect balance.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 1, Boozy: 5, Herbal: 0, Fruity: 1, Spicy: 1, Smoky: 0 } },
    { id: 'daiquiri', name: 'Daiquiri', category: 'Sours & Daisies', ingredients: ['2 oz White Rum', '1 oz Lime Juice', '0.75 oz Simple Syrup'], instructions: ['Shake with ice.', 'Double strain into coupe.'], description: 'The test of a bartender.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 7, Bitter: 0, Boozy: 5, Herbal: 0, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'margarita', name: 'Margarita', category: 'Sours & Daisies', ingredients: ['2 oz Blanco Tequila', '1 oz Lime Juice', '0.75 oz Cointreau', 'Salt Rim'], instructions: ['Shake with ice.', 'Strain into salt-rimmed rocks glass over ice.'], description: 'Most popular cocktail in the world.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 7, Bitter: 1, Boozy: 6, Herbal: 2, Fruity: 3, Spicy: 0, Smoky: 0 } },
    { id: 'tommys-margarita', name: 'Tommy\'s Margarita', category: 'Modern Classics', ingredients: ['2 oz Blanco Tequila', '1 oz Lime Juice', '0.5 oz Agave Nectar'], instructions: ['Shake with ice.', 'Strain over ice.', 'No salt rim (typically).'], description: 'Agave-forward modern standard.', creator: 'Julio Bermejo', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 7, Bitter: 0, Boozy: 6, Herbal: 3, Fruity: 2, Spicy: 0, Smoky: 0 } },
    { id: 'sidecar', name: 'Sidecar', category: 'Sours & Daisies', ingredients: ['2 oz Cognac', '0.75 oz Cointreau', '0.75 oz Lemon Juice', 'Sugared Rim'], instructions: ['Shake with ice.', 'Strain into sugar-rimmed coupe.'], description: 'Brandy sour classic.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 0, Fruity: 3, Spicy: 0, Smoky: 0 } },
    { id: 'gimlet', name: 'Gimlet', category: 'Sours & Daisies', ingredients: ['2 oz Gin', '0.75 oz Lime Juice', '0.75 oz Simple Syrup'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Sharp and refreshing.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 7, Bitter: 1, Boozy: 5, Herbal: 4, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'bees-knees', name: 'Bee\'s Knees', category: 'Sours & Daisies', ingredients: ['2 oz Gin', '0.75 oz Lemon Juice', '0.75 oz Honey Syrup'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Prohibition classic.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 3, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'gold-rush', name: 'Gold Rush', category: 'Modern Classics', ingredients: ['2 oz Bourbon', '0.75 oz Lemon Juice', '0.75 oz Honey Syrup'], instructions: ['Shake with ice.', 'Strain into rocks glass with ice.'], description: 'Whiskey Bee\'s Knees.', creator: 'Milk & Honey', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 1, Fruity: 1, Spicy: 1, Smoky: 0 } },
    { id: 'penicillin', name: 'Penicillin', category: 'Modern Classics', ingredients: ['2 oz Blended Scotch', '0.75 oz Lemon Juice', '0.75 oz Honey-Ginger Syrup', '0.25 oz Islay Scotch (Float)'], instructions: ['Shake first 3 ingredients.', 'Strain over ice.', 'Float Islay scotch on top.', 'Candied ginger.'], description: 'Smoky, spicy, medicinal masterpiece.', creator: 'Sam Ross', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 1, Fruity: 0, Spicy: 4, Smoky: 5 } },
    { id: 'paper-plane', name: 'Paper Plane', category: 'Modern Classics', ingredients: ['0.75 oz Bourbon', '0.75 oz Aperol', '0.75 oz Amaro Nonino', '0.75 oz Lemon Juice'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Perfectly balanced equal parts.', creator: 'Sam Ross', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 5, Bitter: 3, Boozy: 5, Herbal: 2, Fruity: 4, Spicy: 0, Smoky: 0 } },
    { id: 'naked-and-famous', name: 'Naked and Famous', category: 'Modern Classics', ingredients: ['0.75 oz Mezcal', '0.75 oz Yellow Chartreuse', '0.75 oz Aperol', '0.75 oz Lime Juice'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Smoky Last Word variation.', creator: 'Joaquin Simo', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 5, Bitter: 3, Boozy: 5, Herbal: 5, Fruity: 2, Spicy: 0, Smoky: 5 } },
    { id: 'last-word', name: 'The Last Word', category: 'Sours & Daisies', ingredients: ['0.75 oz Gin', '0.75 oz Green Chartreuse', '0.75 oz Maraschino Liqueur', '0.75 oz Lime Juice'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Pungent, herbal, sweet, and sour.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 5, Bitter: 1, Boozy: 6, Herbal: 8, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'corpse-reviver-2', name: 'Corpse Reviver #2', category: 'Sours & Daisies', ingredients: ['0.75 oz Gin', '0.75 oz Lillet Blanc', '0.75 oz Cointreau', '0.75 oz Lemon Juice', 'Absinthe (Rinse)'], instructions: ['Shake with ice.', 'Strain into rinsed coupe.'], description: 'Hair of the dog.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 3, Fruity: 3, Spicy: 0, Smoky: 0 } },
    { id: 'aviation', name: 'Aviation', category: 'Sours & Daisies', ingredients: ['2 oz Gin', '0.5 oz Maraschino Liqueur', '0.25 oz Crème de Violette', '0.75 oz Lemon Juice'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Floral and sky blue.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 2, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'pisco-sour', name: 'Pisco Sour', category: 'Sours & Daisies', ingredients: ['2 oz Pisco', '1 oz Lime Juice', '0.75 oz Simple Syrup', '1 Egg White', 'Angostura Bitters'], instructions: ['Dry shake.', 'Shake with ice.', 'Strain into coupe.', 'Bitters on foam.'], description: 'Peruvian national drink.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 7, Bitter: 1, Boozy: 5, Herbal: 1, Fruity: 4, Spicy: 0, Smoky: 0 } },
    { id: 'clover-club', name: 'Clover Club', category: 'Sours & Daisies', ingredients: ['2 oz Gin', '0.75 oz Lemon Juice', '0.5 oz Raspberry Syrup', '1 Egg White'], instructions: ['Dry shake.', 'Shake with ice.', 'Strain into coupe.'], description: 'Fruity and fluffy pre-prohibition.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 5, Bitter: 0, Boozy: 5, Herbal: 2, Fruity: 6, Spicy: 0, Smoky: 0 } },
    { id: 'white-lady', name: 'White Lady', category: 'Sours & Daisies', ingredients: ['2 oz Gin', '0.75 oz Cointreau', '0.75 oz Lemon Juice', 'Egg White (optional)'], instructions: ['Shake with ice.', 'Strain into coupe.'], description: 'Gin sidecar.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 6, Herbal: 2, Fruity: 3, Spicy: 0, Smoky: 0 } },
    { id: 'division-bell', name: 'Division Bell', category: 'Modern Classics', ingredients: ['1 oz Mezcal', '0.75 oz Aperol', '0.5 oz Maraschino Liqueur', '0.75 oz Lime Juice'], instructions: ['Shake with ice.', 'Strain into coupe.', 'Grapefruit twist.'], description: 'Smoky, bitter, red.', creator: 'Phil Ward', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 3, Boozy: 6, Herbal: 2, Fruity: 2, Spicy: 0, Smoky: 6 } },
    { id: 'southside', name: 'Southside', category: 'Sours & Daisies', ingredients: ['2 oz Gin', '0.75 oz Lime Juice', '0.75 oz Simple Syrup', '6 Mint Leaves'], instructions: ['Shake with ice.', 'Double strain into coupe.', 'Mint leaf.'], description: 'A gin Mojito, served up.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 5, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'eastside', name: 'Eastside', category: 'Modern Classics', ingredients: ['2 oz Gin', '0.75 oz Lime Juice', '0.75 oz Simple Syrup', '2 Cucumber slices', '6 Mint Leaves'], instructions: ['Muddle cucumber and mint.', 'Shake with ice.', 'Double strain.'], description: 'Fresh spa water with a kick.', creator: 'Christy Pope', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 6, Fruity: 0, Spicy: 0, Smoky: 0 } },
    { id: 'gin-basil-smash', name: 'Gin Basil Smash', category: 'Modern Classics', ingredients: ['2 oz Gin', '0.75 oz Lemon Juice', '0.75 oz Simple Syrup', '12 Basil Leaves'], instructions: ['Muddle basil aggressively.', 'Shake with ice.', 'Double strain over ice.'], description: 'Bright green and peppery.', creator: 'Joerg Meyer', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 8, Fruity: 0, Spicy: 1, Smoky: 0 } },

    // === HIGHBALLS & FIZZES ===
    { id: 'tom-collins', name: 'Tom Collins', category: 'Highballs & Fizzes', ingredients: ['2 oz Old Tom Gin (or London Dry)', '1 oz Lemon Juice', '0.5 oz Simple Syrup', 'Soda Water'], instructions: ['Build in highball glass with ice.', 'Top with soda.', 'Stir.'], description: 'The original hard lemonade.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 5, Bitter: 0, Boozy: 4, Herbal: 2, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'gin-tonic', name: 'Gin & Tonic', category: 'Highballs & Fizzes', ingredients: ['2 oz Gin', '4 oz Tonic Water'], instructions: ['Build in glass with ice.', 'Squeeze lime wedge.'], description: 'Simple perfection.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 2, Bitter: 5, Boozy: 4, Herbal: 4, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'moscow-mule', name: 'Moscow Mule', category: 'Highballs & Fizzes', ingredients: ['2 oz Vodka', '0.5 oz Lime Juice', '4 oz Ginger Beer'], instructions: ['Build in copper mug with ice.', 'Garnish with lime.'], description: 'Spicy ginger kick.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 4, Bitter: 0, Boozy: 4, Herbal: 0, Fruity: 1, Spicy: 6, Smoky: 0 } },
    { id: 'dark-n-stormy', name: 'Dark \'n\' Stormy', category: 'Highballs & Fizzes', ingredients: ['2 oz Black Rum (Goslings)', '0.5 oz Lime Juice', '4 oz Ginger Beer'], instructions: ['Build in highball.', 'Float rum on top.'], description: 'Bermuda\'s national drink.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 4, Bitter: 0, Boozy: 5, Herbal: 0, Fruity: 1, Spicy: 6, Smoky: 0 } },
    { id: 'paloma', name: 'Paloma', category: 'Highballs & Fizzes', ingredients: ['2 oz Blanco Tequila', '0.5 oz Lime Juice', '4 oz Grapefruit Soda', 'Salt Rim'], instructions: ['Build in salt-rimmed glass with ice.', 'Top with soda.'], description: 'Mexico\'s favorite.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 5, Bitter: 2, Boozy: 5, Herbal: 2, Fruity: 4, Spicy: 0, Smoky: 0 } },
    { id: 'french-75', name: 'French 75', category: 'Highballs & Fizzes', ingredients: ['1 oz Gin', '0.5 oz Lemon Juice', '0.5 oz Simple Syrup', 'Champagne'], instructions: ['Shake gin, lemon, syrup.', 'Strain into flute.', 'Top with champagne.'], description: 'Hits like a 75mm field gun.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 5, Bitter: 0, Boozy: 6, Herbal: 2, Fruity: 2, Spicy: 0, Smoky: 0 } },
    { id: 'mojito', name: 'Mojito', category: 'Highballs & Fizzes', ingredients: ['2 oz White Rum', '0.75 oz Lime Juice', '0.75 oz Simple Syrup', '8 Mint Leaves', 'Soda Water'], instructions: ['Muddle mint gently.', 'Add liquids and ice.', 'Top with soda.', 'Stir.'], description: 'Cuban highball.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 4, Bitter: 0, Boozy: 4, Herbal: 6, Fruity: 1, Spicy: 0, Smoky: 0 } },
    { id: 'american-trilogy', name: 'American Trilogy', category: 'Modern Classics', ingredients: ['1 oz Rye Whiskey', '1 oz Applejack', '1 dash Orange Bitters', '1 cube Sugar'], instructions: ['Muddle sugar and bitters.', 'Add spirits and ice.', 'Stir.'], description: 'Old Fashioned variation.', creator: 'Little Branch', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 0, Bitter: 3, Boozy: 8, Herbal: 1, Fruity: 3, Spicy: 2, Smoky: 0 } },
    { id: 'ramos-gin-fizz', name: 'Ramos Gin Fizz', category: 'Highballs & Fizzes', ingredients: ['2 oz Gin', '0.5 oz Lemon Juice', '0.5 oz Lime Juice', '1 oz Simple Syrup', '1 oz Heavy Cream', '1 Egg White', '3 drops Orange Flower Water', 'Soda Water'], instructions: ['Dry shake vigorously (2 mins).', 'Add ice, shake again.', 'Strain into tall glass.', 'Top with soda.'], description: 'Like drinking a cloud.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 4, Bitter: 0, Boozy: 4, Herbal: 3, Fruity: 2, Spicy: 0, Smoky: 0 } },
    { id: 'morning-glory-fizz', name: 'Morning Glory Fizz', category: 'Highballs & Fizzes', ingredients: ['2 oz Blended Scotch', '0.75 oz Lemon Juice', '0.5 oz Simple Syrup', '1 Egg White', 'Absinthe (Rinse)', 'Soda Water'], instructions: ['Dry shake.', 'Shake with ice.', 'Strain into absinthe-rinsed glass.', 'Top with soda.'], description: 'Scotch breakfast fizz.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 5, Bitter: 1, Boozy: 5, Herbal: 3, Fruity: 0, Spicy: 1, Smoky: 2 } },
    
    // === TIKI & TROPICAL ===
    { id: 'mai-tai', name: 'Mai Tai', category: 'Tiki & Tropical', ingredients: ['2 oz Aged Rum (Jamaican/Agricole Blend)', '0.75 oz Lime Juice', '0.5 oz Orange Curacao', '0.25 oz Orgeat', '0.25 oz Rich Syrup'], instructions: ['Shake with crushed ice.', 'Pour unstrained into glass.', 'Float mint sprig and spent lime shell.'], description: 'The quintessential Tiki drink.', creator: 'Trader Vic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 6, Bitter: 0, Boozy: 7, Herbal: 1, Fruity: 4, Spicy: 1, Smoky: 0 } },
    { id: 'jungle-bird', name: 'Jungle Bird', category: 'Tiki & Tropical', ingredients: ['1.5 oz Black Strap Rum', '0.75 oz Campari', '1.5 oz Pineapple Juice', '0.5 oz Lime Juice', '0.5 oz Demerara Syrup'], instructions: ['Shake with ice.', 'Strain over fresh ice.'], description: 'Bitter tiki masterpiece.', creator: 'Aviary Bar', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 4, Bitter: 5, Boozy: 6, Herbal: 2, Fruity: 7, Spicy: 0, Smoky: 0 } },
    { id: 'zombie', name: 'Zombie', category: 'Tiki & Tropical', ingredients: ['1.5 oz Gold Rum', '1.5 oz Dark Rum', '1 oz 151 Proof Rum', '0.75 oz Lime Juice', '0.5 oz Falernum', '0.5 oz Grapefruit Juice', '1 tsp Cinnamon Syrup', '1 tsp Grenadine', '1 dash Angostura'], instructions: ['Blend with 6oz crushed ice.', 'Pour into tall glass.'], description: 'Limit 2 per customer.', creator: 'Donn Beach', dateAdded: '2025-01-01', flavorProfile: { Sweet: 7, Sour: 5, Bitter: 2, Boozy: 10, Herbal: 3, Fruity: 5, Spicy: 4, Smoky: 0 } },
    { id: 'painkiller', name: 'Painkiller', category: 'Tiki & Tropical', ingredients: ['2 oz Pusser\'s Rum', '4 oz Pineapple Juice', '1 oz Orange Juice', '1 oz Cream of Coconut'], instructions: ['Shake with ice.', 'Pour over crushed ice.', 'Grate nutmeg on top.'], description: 'Rich tropical comfort.', creator: 'Soggy Dollar Bar', dateAdded: '2025-01-01', flavorProfile: { Sweet: 8, Sour: 2, Bitter: 0, Boozy: 5, Herbal: 0, Fruity: 9, Spicy: 1, Smoky: 0 } },
    { id: 'jet-pilot', name: 'Jet Pilot', category: 'Tiki & Tropical', ingredients: ['1 oz Jamaican Rum', '0.75 oz Gold Rum', '0.75 oz 151 Rum', '0.5 oz Lime Juice', '0.5 oz Grapefruit Juice', '0.5 oz Cinnamon Syrup', '0.5 oz Falernum', '1 dash Angostura', 'Absinthe (Rinse/Dash)'], instructions: ['Blend with crushed ice.', 'Garnish with cherry and mint.'], description: 'Spicy, boozy test pilot riff.', creator: 'Steve Crane', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 5, Bitter: 2, Boozy: 9, Herbal: 4, Fruity: 4, Spicy: 6, Smoky: 0 } },
    { id: 'three-dots', name: 'Three Dots and a Dash', category: 'Tiki & Tropical', ingredients: ['1.5 oz Rhum Agricole', '0.5 oz Blended Aged Rum', '0.5 oz Lime Juice', '0.5 oz Orange Juice', '0.5 oz Honey Syrup', '0.25 oz Falernum', '0.25 oz Allspice Dram', 'Angostura'], instructions: ['Flash blend with crushed ice.', 'Garnish with 3 cherries and a pineapple stick.'], description: 'Victory in a glass.', creator: 'Donn Beach', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 5, Bitter: 2, Boozy: 7, Herbal: 3, Fruity: 5, Spicy: 7, Smoky: 0 } },
    { id: 'chartreuse-swizzle', name: 'Chartreuse Swizzle', category: 'Modern Classics', ingredients: ['1.5 oz Green Chartreuse', '1 oz Pineapple Juice', '0.75 oz Lime Juice', '0.5 oz Falernum'], instructions: ['Build in glass with crushed ice.', 'Swizzle vigorously.', 'Top with more ice and mint.'], description: 'Vegetal tiki.', creator: 'Marco Dionysos', dateAdded: '2025-01-01', flavorProfile: { Sweet: 6, Sour: 5, Bitter: 1, Boozy: 7, Herbal: 9, Fruity: 5, Spicy: 2, Smoky: 0 } },
    { id: 'saturn', name: 'Saturn', category: 'Tiki & Tropical', ingredients: ['1.5 oz Gin', '0.5 oz Lemon Juice', '0.5 oz Passion Fruit Syrup', '0.25 oz Orgeat', '0.25 oz Falernum'], instructions: ['Flash blend with crushed ice.', 'Pour into coupe.'], description: 'Rare Gin tiki classic.', creator: 'J. Popo Galsini', dateAdded: '2025-01-01', flavorProfile: { Sweet: 7, Sour: 6, Bitter: 0, Boozy: 5, Herbal: 3, Fruity: 7, Spicy: 2, Smoky: 0 } },
    { id: 'singapore-sling', name: 'Singapore Sling', category: 'Tiki & Tropical', ingredients: ['1.5 oz Gin', '0.5 oz Cherry Heering', '0.25 oz Cointreau', '0.25 oz Benedictine', '4 oz Pineapple Juice', '0.5 oz Lime Juice', 'Grenadine', 'Angostura'], instructions: ['Shake with ice.', 'Strain into tall glass.'], description: 'Complex fruit punch.', creator: 'Raffles Hotel', dateAdded: '2025-01-01', flavorProfile: { Sweet: 7, Sour: 4, Bitter: 1, Boozy: 5, Herbal: 3, Fruity: 8, Spicy: 1, Smoky: 0 } },
    { id: 'hurricane', name: 'Hurricane', category: 'Tiki & Tropical', ingredients: ['2 oz Dark Rum', '2 oz White Rum', '1 oz Passion Fruit Syrup', '1 oz Lemon Juice'], instructions: ['Shake with ice.', 'Pour into Hurricane glass.'], description: 'Pat O\'Brien\'s storm.', creator: 'New Orleans', dateAdded: '2025-01-01', flavorProfile: { Sweet: 7, Sour: 5, Bitter: 0, Boozy: 8, Herbal: 0, Fruity: 8, Spicy: 0, Smoky: 0 } },
    { id: 'navy-grog', name: 'Navy Grog', category: 'Tiki & Tropical', ingredients: ['1 oz Light Rum', '1 oz Gold Rum', '1 oz Dark Rum', '0.75 oz Lime Juice', '0.75 oz Grapefruit Juice', '1 oz Honey Syrup', 'Soda Water'], instructions: ['Shake with ice.', 'Strain over ice cone.'], description: 'Donn Beach powerful grog.', creator: 'Donn Beach', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 6, Bitter: 1, Boozy: 9, Herbal: 1, Fruity: 3, Spicy: 0, Smoky: 0 } },

    // === ZERO-PROOF ===
    { id: 'virgin-mojito', name: 'Virgin Mojito', category: 'Zero-Proof', ingredients: ['8 Mint Leaves', '0.75 oz Lime Juice', '0.75 oz Simple Syrup', '4 oz Soda Water'], instructions: ['Muddle mint lightly with syrup.', 'Add lime and ice.', 'Top with soda.', 'Stir.'], description: 'All the refreshment, none of the buzz.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 4, Bitter: 0, Boozy: 0, Herbal: 6, Fruity: 1, Spicy: 0, Smoky: 0 }, nutrition: { calories: 60, carbs: 15, abv: 0 } },
    { id: 'shirley-temple', name: 'Shirley Temple', category: 'Zero-Proof', ingredients: ['4 oz Ginger Ale', '0.5 oz Grenadine', '0.25 oz Lime Juice'], instructions: ['Build in tall glass over ice.', 'Stir.', 'Garnish with cherry.'], description: 'The original mocktail.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 7, Sour: 2, Bitter: 0, Boozy: 0, Herbal: 0, Fruity: 4, Spicy: 2, Smoky: 0 }, nutrition: { calories: 90, carbs: 22, abv: 0 } },
    { id: 'phony-negroni', name: 'Phony Negroni', category: 'Zero-Proof', ingredients: ['1 oz NA Gin', '1 oz NA Bitter (e.g. Giffard)', '1 oz NA Sweet Vermouth'], instructions: ['Stir with ice.', 'Strain over rock.', 'Orange peel.'], description: 'Convincing alcohol-free aperitif.', creator: 'Modern Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 0, Bitter: 6, Boozy: 0, Herbal: 5, Fruity: 2, Spicy: 0, Smoky: 0 }, nutrition: { calories: 45, carbs: 10, abv: 0 } },
    { id: 'arnold-palmer', name: 'Arnold Palmer', category: 'Zero-Proof', ingredients: ['3 oz Iced Tea', '3 oz Lemonade'], instructions: ['Build in tall glass over ice.', 'Stir.'], description: 'Golf course classic.', creator: 'Arnold Palmer', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 4, Bitter: 2, Boozy: 0, Herbal: 3, Fruity: 1, Spicy: 0, Smoky: 0 }, nutrition: { calories: 50, carbs: 12, abv: 0 } },
    { id: 'nada-colada', name: 'Nada Colada', category: 'Zero-Proof', ingredients: ['2 oz Pineapple Juice', '1.5 oz Cream of Coconut', '0.5 oz Lime Juice', '4 oz Crushed Ice'], instructions: ['Blend until smooth.', 'Pour into hurricane glass.'], description: 'Virgin Piña Colada.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 8, Sour: 2, Bitter: 0, Boozy: 0, Herbal: 0, Fruity: 8, Spicy: 0, Smoky: 0 }, nutrition: { calories: 250, carbs: 30, abv: 0 } },
    { id: 'virgin-mary', name: 'Virgin Mary', category: 'Zero-Proof', ingredients: ['4 oz Tomato Juice', '0.5 oz Lemon Juice', '2 dashes Worcestershire', '2 dashes Hot Sauce', 'Pinch Salt/Pepper'], instructions: ['Roll with ice.', 'Strain into tall glass.', 'Celery stick.'], description: 'Savory and spicy brunch standard.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 2, Sour: 3, Bitter: 1, Boozy: 0, Herbal: 4, Fruity: 3, Spicy: 6, Smoky: 0 }, nutrition: { calories: 40, carbs: 8, abv: 0 } },
    { id: 'roy-rogers', name: 'Roy Rogers', category: 'Zero-Proof', ingredients: ['4 oz Cola', '0.5 oz Grenadine'], instructions: ['Build in tall glass over ice.', 'Cherry garnish.'], description: 'Cola with a sweet cherry kick.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 8, Sour: 2, Bitter: 0, Boozy: 0, Herbal: 1, Fruity: 2, Spicy: 1, Smoky: 0 }, nutrition: { calories: 110, carbs: 28, abv: 0 } },
    { id: 'cucumber-cooler', name: 'Cucumber Cooler', category: 'Zero-Proof', ingredients: ['4 slices Cucumber', '0.75 oz Lime Juice', '0.5 oz Simple Syrup', 'Soda Water'], instructions: ['Muddle cucumber.', 'Add lime/syrup, shake.', 'Strain over fresh ice.', 'Top soda.'], description: 'Spa water fizz.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 4, Bitter: 0, Boozy: 0, Herbal: 4, Fruity: 1, Spicy: 0, Smoky: 0 }, nutrition: { calories: 35, carbs: 9, abv: 0 } },

    // === LOW-PROOF / SESSION ===
    { id: 'garibaldi', name: 'Garibaldi', category: 'Low-Proof', ingredients: ['1.5 oz Campari', '4 oz Fluffy Orange Juice'], instructions: ['Build in highball glass.', 'Add ice.', 'Stir gently to keep foam.'], description: 'Italian session classic.', creator: 'Dante NYC', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 3, Bitter: 5, Boozy: 2, Herbal: 3, Fruity: 6, Spicy: 0, Smoky: 0 }, nutrition: { calories: 150, carbs: 15, abv: 6 } },
    { id: 'bicyclette', name: 'Bicyclette', category: 'Low-Proof', ingredients: ['2 oz Campari', '2 oz Dry White Wine', 'Soda Water'], instructions: ['Build in wine glass over ice.', 'Top with splash of soda.', 'Lemon twist.'], description: 'Afternoon cafe sipper.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 2, Bitter: 6, Boozy: 3, Herbal: 4, Fruity: 2, Spicy: 0, Smoky: 0 }, nutrition: { calories: 130, carbs: 8, abv: 9 } },
    { id: 'aperol-spritz', name: 'Aperol Spritz', category: 'Low-Proof', ingredients: ['2 oz Aperol', '3 oz Prosecco', '1 oz Soda Water'], instructions: ['Build in wine glass with ice.', 'Orange slice.'], description: 'Sunset in a glass.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 2, Bitter: 3, Boozy: 3, Herbal: 2, Fruity: 4, Spicy: 0, Smoky: 0 }, nutrition: { calories: 160, carbs: 12, abv: 9 } },
    { id: 'port-tonic', name: 'Port & Tonic', category: 'Low-Proof', ingredients: ['2 oz White Port', '4 oz Tonic Water'], instructions: ['Build in highball over ice.', 'Stir.', 'Lemon wheel and mint.'], description: 'Portuguese refresher.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 1, Bitter: 2, Boozy: 3, Herbal: 1, Fruity: 3, Spicy: 0, Smoky: 0 }, nutrition: { calories: 140, carbs: 12, abv: 6 } },
    { id: 'michelada', name: 'Michelada', category: 'Low-Proof', ingredients: ['12 oz Light Mexican Beer', '1 oz Lime Juice', '2 dashes Hot Sauce', '2 dashes Worcestershire', 'Tajin Rim'], instructions: ['Rim glass with Tajin.', 'Add lime and sauces.', 'Add ice and beer.', 'Stir.'], description: 'Savory beer cocktail.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 1, Sour: 5, Bitter: 2, Boozy: 2, Herbal: 0, Fruity: 1, Spicy: 6, Smoky: 0 }, nutrition: { calories: 140, carbs: 12, abv: 4 } },
    { id: 'bamboo', name: 'Bamboo', category: 'Low-Proof', ingredients: ['1.5 oz Dry Sherry', '1.5 oz Dry Vermouth', '1 dash Angostura', '1 dash Orange Bitters'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Lemon twist.'], description: 'Low ABV Martini alternative.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 2, Sour: 1, Bitter: 2, Boozy: 4, Herbal: 3, Fruity: 2, Spicy: 0, Smoky: 0 }, nutrition: { calories: 90, carbs: 4, abv: 15 } },
    { id: 'adonis', name: 'Adonis', category: 'Low-Proof', ingredients: ['1.5 oz Fino Sherry', '1.5 oz Sweet Vermouth', '2 dashes Orange Bitters'], instructions: ['Stir with ice.', 'Strain into coupe.', 'Orange peel.'], description: 'Low ABV Manhattan.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 1, Bitter: 2, Boozy: 4, Herbal: 3, Fruity: 2, Spicy: 1, Smoky: 0 }, nutrition: { calories: 100, carbs: 7, abv: 15 } },
    { id: 'sherry-cobbler', name: 'Sherry Cobbler', category: 'Low-Proof', ingredients: ['3 oz Amontillado Sherry', '0.5 oz Simple Syrup', '2 Orange Slices'], instructions: ['Muddle orange and syrup.', 'Add sherry and ice.', 'Shake.', 'Pour over crushed ice.'], description: 'Victorian era favorite.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 5, Sour: 2, Bitter: 1, Boozy: 4, Herbal: 1, Fruity: 5, Spicy: 0, Smoky: 0 }, nutrition: { calories: 130, carbs: 15, abv: 12 } },
    { id: 'americano', name: 'Americano', category: 'Low-Proof', ingredients: ['1.5 oz Campari', '1.5 oz Sweet Vermouth', 'Soda Water'], instructions: ['Build in rocks glass with ice.', 'Top with soda.', 'Orange twist.'], description: 'The precursor to the Negroni.', creator: 'Classic', dateAdded: '2025-01-01', flavorProfile: { Sweet: 4, Sour: 1, Bitter: 6, Boozy: 3, Herbal: 4, Fruity: 2, Spicy: 0, Smoky: 0 }, nutrition: { calories: 120, carbs: 12, abv: 10 } },
    { id: 'spaghett', name: 'Spaghett', category: 'Low-Proof', ingredients: ['1 bottle Miller High Life', '1 oz Aperol', 'Splash Lemon Juice'], instructions: ['Take sip of beer.', 'Pour Aperol and lemon into bottle.'], description: 'The champagne of beers cocktail.', creator: 'Wet City', dateAdded: '2025-01-01', flavorProfile: { Sweet: 3, Sour: 2, Bitter: 3, Boozy: 3, Herbal: 2, Fruity: 2, Spicy: 0, Smoky: 0 }, nutrition: { calories: 170, carbs: 16, abv: 6 } }
];
