import { db } from "./db";
import { globalRecipes } from "../shared/schema";

interface RecipeData {
  slug: string;
  name: string;
  description?: string;
  history?: string;
  category: string;
  ingredients: string[];
  instructions: string[];
  glassType?: string;
  garnish?: string;
  creator?: string;
  creatorType?: string;
  flavorProfile?: {
    Sweet: number;
    Sour: number;
    Bitter: number;
    Boozy: number;
    Herbal: number;
    Fruity: number;
    Spicy: number;
    Smoky: number;
  };
}

const MODERN_CRAFT_COCKTAILS: RecipeData[] = [
  // ========== DEATH AND COMPANY ==========
  {
    slug: "oaxaca-old-fashioned",
    name: "Oaxaca Old-Fashioned",
    description: "The iconic mezcal Old-Fashioned from Death & Co, one of the most influential modern cocktails.",
    history: "Created by Phil Ward at Death & Co in 2007. This drink pioneered the use of mezcal in craft cocktails and became one of the most ordered drinks in the bar's history.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Reposado Tequila", "0.5 oz Mezcal", "1 tsp Agave Nectar", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in an old-fashioned glass with one large ice cube.", "Stir until well-chilled.", "Flame an orange twist over the drink, then drop it in."],
    glassType: "Old Fashioned",
    garnish: "Flamed orange twist",
    creator: "Phil Ward",
    creatorType: "Death & Co"
  },
  {
    slug: "naked-and-famous",
    name: "Naked and Famous",
    description: "An equal-parts mezcal cocktail that's become a modern classic, riffing on the Last Word.",
    history: "Created by Joaquín Simó at Death & Co. Described as the love child of the Last Word and Paper Plane cocktails.",
    category: "Sour",
    ingredients: ["0.75 oz Mezcal", "0.75 oz Yellow Chartreuse", "0.75 oz Aperol", "0.75 oz Fresh Lime Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Joaquín Simó",
    creatorType: "Death & Co"
  },
  {
    slug: "the-conference",
    name: "The Conference",
    description: "A spirit-forward blend of four aged spirits, showcasing Death & Co's minimalist approach.",
    category: "Spirit-Forward",
    ingredients: ["0.5 oz Rye Whiskey", "0.5 oz Bourbon", "0.5 oz Calvados", "0.5 oz Cognac", "0.25 oz Simple Syrup", "2 dashes Angostura Bitters", "2 dashes Orange Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over a large ice cube."],
    glassType: "Old Fashioned",
    garnish: "Orange twist",
    creator: "Death & Co",
    creatorType: "Bar"
  },
  {
    slug: "wooden-ship",
    name: "Wooden Ship",
    description: "A sophisticated gin and genever cocktail with orange liqueur notes.",
    category: "Spirit-Forward",
    ingredients: ["1 oz Gin", "1 oz Genever", "0.5 oz Grand Marnier", "0.5 tsp Simple Syrup", "1 dash Fee Brothers Whiskey Barrel-Aged Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a chilled coupe."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Thomas Waugh",
    creatorType: "Death & Co"
  },
  {
    slug: "kingston-negroni",
    name: "Kingston Negroni",
    description: "A Jamaican rum variation on the classic Negroni.",
    category: "Spirit-Forward",
    ingredients: ["1 oz Jamaican Rum", "1 oz Campari", "1 oz Sweet Vermouth"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Orange slice",
    creator: "Death & Co",
    creatorType: "Bar"
  },

  // ========== DEAD RABBIT ==========
  {
    slug: "dead-rabbit-irish-coffee",
    name: "Dead Rabbit Irish Coffee",
    description: "The world-famous Irish Coffee perfected by the Dead Rabbit.",
    history: "The Dead Rabbit's meticulous take on the classic, featuring house techniques that have made it the benchmark for Irish coffees worldwide.",
    category: "Hot Drinks",
    ingredients: ["4 oz Hot Brewed Coffee", "1.5 oz Irish Whiskey", "0.5 oz Demerara Syrup", "Lightly Whipped Heavy Cream"],
    instructions: ["Warm an Irish coffee glass with hot water, then empty.", "Add hot coffee and Demerara syrup, stir.", "Add Irish whiskey.", "Float lightly whipped cream on top using the back of a spoon.", "Do not stir before drinking."],
    glassType: "Irish Coffee Mug",
    garnish: "Whipped cream float",
    creator: "Dead Rabbit",
    creatorType: "Bar"
  },
  {
    slug: "dead-rabbit-whiskey-cocktail",
    name: "The Whiskey Cocktail",
    description: "A complex, herbaceous whiskey drink from the Dead Rabbit's award-winning menu.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "0.25 oz Bénédictine", "0.25 oz Royal Combier", "2 dashes Aromatic Bitters", "2 dashes Orange Bitters", "Absinthe rinse"],
    instructions: ["Rinse a mixing glass with absinthe.", "Add all other ingredients with ice.", "Stir until well-chilled.", "Strain into a cocktail glass.", "Express orange oils over drink and discard peel."],
    glassType: "Coupe",
    garnish: "Orange peel expressed",
    creator: "Dead Rabbit",
    creatorType: "Bar"
  },
  {
    slug: "spell-spoke",
    name: "The Spell Spoke",
    description: "A modern, bright Irish whiskey cocktail with exotic notes.",
    category: "Refreshing",
    ingredients: ["2 oz Jameson Black Barrel", "0.5 oz Hibiscus Syrup", "0.5 oz Lime Juice", "Lime Leaf", "Ginger Beer"],
    instructions: ["Muddle lime leaf in shaker.", "Add whiskey, hibiscus syrup, and lime juice with ice.", "Shake and strain into a highball glass with ice.", "Top with ginger beer."],
    glassType: "Highball",
    garnish: "Lime leaf",
    creator: "Dead Rabbit",
    creatorType: "Bar"
  },

  // ========== EMPLOYEES ONLY ==========
  {
    slug: "employees-only-manhattan",
    name: "Employees Only Manhattan",
    description: "The signature Manhattan from NYC's legendary Employees Only bar.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "1 oz Sweet Vermouth", "0.5 oz Grand Marnier", "3 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until very cold.", "Strain into a chilled cocktail glass.", "Express lemon oils over the drink and drop the twist in."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Employees Only",
    creatorType: "Bar"
  },
  {
    slug: "billionaire-cocktail",
    name: "Billionaire Cocktail",
    description: "A bourbon-based sour with house-made grenadine and absinthe bitters.",
    category: "Sour",
    ingredients: ["2 oz Bourbon", "1 oz Fresh Lemon Juice", "0.5 oz House Grenadine", "0.5 oz Simple Syrup", "2 dashes Absinthe Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon wheel",
    creator: "Employees Only",
    creatorType: "Bar"
  },
  {
    slug: "amelia",
    name: "Amélia",
    description: "A fruity vodka cocktail with elderflower and blackberry.",
    category: "Fruity",
    ingredients: ["1.5 oz Vodka", "0.75 oz St-Germain", "3 Fresh Blackberries", "0.75 oz Fresh Lemon Juice"],
    instructions: ["Muddle blackberries in shaker.", "Add remaining ingredients with ice.", "Shake well.", "Double-strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Fresh blackberry",
    creator: "Employees Only",
    creatorType: "Bar"
  },
  {
    slug: "west-side",
    name: "West Side",
    description: "A refreshing vodka cocktail with fresh mint and citrus.",
    category: "Refreshing",
    ingredients: ["2 oz Citrus Vodka", "1 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "6 Fresh Mint Leaves", "Sparkling Water"],
    instructions: ["Muddle mint leaves in shaker.", "Add vodka, lemon juice, and syrup with ice.", "Shake well.", "Strain into a highball glass with ice.", "Top with sparkling water."],
    glassType: "Highball",
    garnish: "Mint sprig",
    creator: "Employees Only",
    creatorType: "Bar"
  },
  {
    slug: "ready-fire-aim",
    name: "Ready Fire Aim",
    description: "A spicy mezcal cocktail with honey and pineapple.",
    category: "Sour",
    ingredients: ["2 oz Mezcal", "1 oz Fresh Lime Juice", "0.75 oz Honey-Pineapple Syrup", "2 dashes Hellfire Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Pineapple frond",
    creator: "Employees Only",
    creatorType: "Bar"
  },

  // ========== ATTABOY / SAM ROSS ==========
  {
    slug: "penicillin",
    name: "Penicillin",
    description: "The iconic smoky, spicy whisky sour that became a modern classic.",
    history: "Created by Sam Ross at Milk & Honey in 2005. One of the most influential cocktails of the 21st century.",
    category: "Sour",
    ingredients: ["2 oz Blended Scotch Whisky", "0.75 oz Fresh Lemon Juice", "0.75 oz Honey-Ginger Syrup", "0.25 oz Islay Single Malt Scotch (float)"],
    instructions: ["Shake blended Scotch, lemon juice, and honey-ginger syrup with ice.", "Strain into a rocks glass over a large ice cube.", "Float the Islay whisky on top.", "Garnish with candied ginger."],
    glassType: "Old Fashioned",
    garnish: "Candied ginger",
    creator: "Sam Ross",
    creatorType: "Milk & Honey"
  },
  {
    slug: "paper-plane",
    name: "Paper Plane",
    description: "A perfect equal-parts cocktail featuring bourbon and amaro.",
    history: "Created by Sam Ross in 2007. Named after the M.I.A. song, it's become as famous as the Penicillin.",
    category: "Sour",
    ingredients: ["0.75 oz Bourbon", "0.75 oz Aperol", "0.75 oz Amaro Nonino", "0.75 oz Fresh Lemon Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Sam Ross",
    creatorType: "Milk & Honey"
  },
  {
    slug: "midnight-stinger",
    name: "Midnight Stinger",
    description: "A Fernet-laced whiskey sour with bold bitter notes.",
    category: "Sour",
    ingredients: ["2 oz Bourbon", "0.75 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "0.25 oz Fernet-Branca"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Lemon wheel",
    creator: "Sam Ross",
    creatorType: "Attaboy"
  },
  {
    slug: "too-soon",
    name: "Too Soon?",
    description: "A bright gin-amaro sour with muddled orange.",
    category: "Sour",
    ingredients: ["1 oz Gin", "1 oz Cynar", "0.75 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "2 Orange Wedges"],
    instructions: ["Muddle orange wedges in shaker.", "Add remaining ingredients with ice.", "Shake well.", "Double-strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange wheel",
    creator: "Sam Ross",
    creatorType: "Attaboy"
  },
  {
    slug: "mosquito",
    name: "Mosquito",
    description: "An equal-parts mezcal cocktail from the Attaboy 'Bug' family.",
    category: "Sour",
    ingredients: ["1 oz Mezcal", "1 oz Fresh Lemon Juice", "1 oz Sweetened Ginger Juice", "1 oz Campari"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "None",
    creator: "Attaboy",
    creatorType: "Bar"
  },

  // ========== PDT ==========
  {
    slug: "bentons-old-fashioned",
    name: "Benton's Old-Fashioned",
    description: "PDT's legendary bacon fat-washed bourbon cocktail.",
    history: "Created by Don Lee at PDT in 2008. This drink pioneered the fat-washing technique and became the most ordered cocktail at PDT.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Bacon Fat-Infused Bourbon", "0.25 oz Grade B Maple Syrup", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until cold.", "Strain into a rocks glass with a large ice cube.", "Garnish with an orange twist."],
    glassType: "Old Fashioned",
    garnish: "Orange twist",
    creator: "Don Lee",
    creatorType: "PDT"
  },

  // ========== SMUGGLER'S COVE / TIKI ==========
  {
    slug: "smugglers-cove-zombie",
    name: "Smuggler's Cove Zombie",
    description: "The definitive modern version of Don the Beachcomber's legendary cocktail.",
    history: "Originally created by Don the Beachcomber in 1934. This Smuggler's Cove version represents years of research into the original recipe.",
    category: "Tiki",
    ingredients: ["1.5 oz Jamaican Rum", "1.5 oz Puerto Rican Rum", "1 oz 151 Demerara Rum", "0.75 oz Fresh Lime Juice", "0.5 oz Fresh Grapefruit Juice", "1 tsp Cinnamon Syrup", "1 tsp Grenadine", "1 tsp Falernum", "1 dash Angostura Bitters", "1 dash Herbstura"],
    instructions: ["Combine all ingredients in a drink mixer with ice.", "Flash blend for 3-4 seconds.", "Pour into a zombie glass."],
    glassType: "Zombie",
    garnish: "Mint sprig",
    creator: "Martin Cate",
    creatorType: "Smuggler's Cove"
  },
  {
    slug: "smugglers-cove-mai-tai",
    name: "Smuggler's Cove Mai Tai",
    description: "The authentic Mai Tai recipe as perfected by Smuggler's Cove.",
    history: "Based on Trader Vic's original 1944 recipe, refined by Martin Cate.",
    category: "Tiki",
    ingredients: ["2 oz Aged Jamaican Rum", "0.75 oz Fresh Lime Juice", "0.5 oz Dry Curaçao", "0.25 oz Orgeat", "0.25 oz Rich Simple Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a double rocks glass over crushed ice."],
    glassType: "Old Fashioned",
    garnish: "Spent lime shell and mint sprig",
    creator: "Martin Cate",
    creatorType: "Smuggler's Cove"
  },
  {
    slug: "painkiller",
    name: "Painkiller",
    description: "The tropical rum cocktail that became the signature drink of the British Virgin Islands.",
    category: "Tiki",
    ingredients: ["2 oz Dark Rum", "4 oz Pineapple Juice", "1 oz Fresh Orange Juice", "1 oz Coconut Cream"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a highball glass over ice.", "Top with freshly grated nutmeg."],
    glassType: "Highball",
    garnish: "Fresh grated nutmeg",
    creator: "Pusser's Rum",
    creatorType: "Brand"
  },
  {
    slug: "jungle-bird",
    name: "Jungle Bird",
    description: "A tropical classic featuring rum and Campari.",
    history: "Created at the Kuala Lumpur Hilton in 1978, rediscovered and popularized by modern tiki revival.",
    category: "Tiki",
    ingredients: ["1.5 oz Dark Jamaican Rum", "0.75 oz Campari", "1.5 oz Fresh Pineapple Juice", "0.5 oz Fresh Lime Juice", "0.5 oz Demerara Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Pineapple frond",
    creator: "Kuala Lumpur Hilton",
    creatorType: "Hotel"
  },

  // ========== MODERN CLASSICS 2020s ==========
  {
    slug: "gold-rush",
    name: "Gold Rush",
    description: "A modern whiskey sour sweetened with honey.",
    history: "Created at Milk & Honey in the early 2000s. A simple but perfect template drink.",
    category: "Sour",
    ingredients: ["2 oz Bourbon", "0.75 oz Fresh Lemon Juice", "0.75 oz Honey Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Lemon wheel",
    creator: "Milk & Honey",
    creatorType: "Bar"
  },
  {
    slug: "division-bell",
    name: "Division Bell",
    description: "A mezcal variation on the Last Word.",
    category: "Sour",
    ingredients: ["0.75 oz Mezcal", "0.75 oz Aperol", "0.75 oz Maraschino Liqueur", "0.75 oz Fresh Lime Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lime wheel",
    creator: "Phil Ward",
    creatorType: "Mayahuel"
  },
  {
    slug: "final-ward",
    name: "Final Ward",
    description: "A whiskey variation on the Last Word.",
    category: "Sour",
    ingredients: ["0.75 oz Rye Whiskey", "0.75 oz Green Chartreuse", "0.75 oz Maraschino Liqueur", "0.75 oz Fresh Lemon Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Phil Ward",
    creatorType: "Death & Co"
  },
  {
    slug: "east-side",
    name: "Eastside",
    description: "A refreshing gin cocktail with cucumber and mint.",
    category: "Refreshing",
    ingredients: ["2 oz Gin", "1 oz Fresh Lime Juice", "0.75 oz Simple Syrup", "3 Cucumber Slices", "6 Mint Leaves"],
    instructions: ["Muddle cucumber and mint in shaker.", "Add remaining ingredients with ice.", "Shake well.", "Double-strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Cucumber slice",
    creator: "Milk & Honey",
    creatorType: "Bar"
  },
  {
    slug: "tommy-s-margarita",
    name: "Tommy's Margarita",
    description: "The agave-forward margarita that changed how we drink tequila.",
    history: "Created by Julio Bermejo at Tommy's Mexican Restaurant in San Francisco in the 1990s.",
    category: "Sour",
    ingredients: ["2 oz Blanco Tequila", "1 oz Fresh Lime Juice", "0.5 oz Agave Nectar"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Lime wheel",
    creator: "Julio Bermejo",
    creatorType: "Tommy's Mexican Restaurant"
  },
  {
    slug: "white-negroni",
    name: "White Negroni",
    description: "A pale, aromatic variation on the classic Negroni.",
    category: "Spirit-Forward",
    ingredients: ["1 oz Gin", "1 oz Lillet Blanc", "1 oz Suze"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Grapefruit twist",
    creator: "Wayne Collins",
    creatorType: "Bartender"
  },
  {
    slug: "black-manhattan",
    name: "Black Manhattan",
    description: "A Manhattan made with Averna instead of sweet vermouth.",
    history: "Created by Todd Smith at Bourbon & Branch in San Francisco in 2005.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "1 oz Averna", "1 dash Angostura Bitters", "1 dash Orange Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Brandied cherry",
    creator: "Todd Smith",
    creatorType: "Bourbon & Branch"
  },
  {
    slug: "mezcal-mule",
    name: "Mezcal Mule",
    description: "A smoky twist on the Moscow Mule.",
    category: "Refreshing",
    ingredients: ["2 oz Mezcal", "0.75 oz Fresh Lime Juice", "0.5 oz Simple Syrup", "3 oz Ginger Beer"],
    instructions: ["Combine mezcal, lime juice, and syrup in a copper mug with ice.", "Top with ginger beer.", "Stir gently."],
    glassType: "Copper Mug",
    garnish: "Lime wheel and candied ginger",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "mexican-firing-squad",
    name: "Mexican Firing Squad",
    description: "A citrusy tequila drink with grenadine and bitters.",
    history: "Created by Charles H. Baker Jr. in the 1930s, rediscovered by modern bartenders.",
    category: "Sour",
    ingredients: ["2 oz Blanco Tequila", "0.75 oz Fresh Lime Juice", "0.75 oz Grenadine", "4 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a highball glass over ice."],
    glassType: "Highball",
    garnish: "Lime wheel",
    creator: "Charles H. Baker Jr.",
    creatorType: "Author"
  },
  {
    slug: "nuclear-daiquiri",
    name: "Nuclear Daiquiri",
    description: "An intense, chartreuse-forward daiquiri variation.",
    history: "Created by Gregor de Gruyther at LAB bar in London.",
    category: "Sour",
    ingredients: ["1 oz White Rum", "0.75 oz Green Chartreuse", "0.75 oz Fresh Lime Juice", "0.75 oz Velvet Falernum"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Gregor de Gruyther",
    creatorType: "LAB Bar"
  },
  {
    slug: "kentucky-buck",
    name: "Kentucky Buck",
    description: "A bourbon-based buck with strawberry and ginger.",
    category: "Refreshing",
    ingredients: ["2 oz Bourbon", "0.75 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "2 Strawberries", "2 dashes Angostura Bitters", "2 oz Ginger Beer"],
    instructions: ["Muddle strawberries in shaker.", "Add bourbon, lemon juice, syrup, and bitters with ice.", "Shake well.", "Strain into a highball glass with ice.", "Top with ginger beer."],
    glassType: "Highball",
    garnish: "Strawberry slice",
    creator: "Erick Castro",
    creatorType: "Bartender"
  },
  {
    slug: "saturn",
    name: "Saturn",
    description: "A tropical gin cocktail with passion fruit and orgeat.",
    history: "Created by J. 'Popo' Galsini in 1967, winner of the IBA World Cocktail Championship.",
    category: "Tiki",
    ingredients: ["1.25 oz Gin", "0.5 oz Fresh Lemon Juice", "0.25 oz Passion Fruit Syrup", "0.25 oz Orgeat", "0.25 oz Velvet Falernum"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon peel",
    creator: "J. 'Popo' Galsini",
    creatorType: "Bartender"
  },
  {
    slug: "port-light",
    name: "Port Light",
    description: "A bourbon and passion fruit cocktail with egg white.",
    category: "Sour",
    ingredients: ["1.5 oz Bourbon", "1 oz Fresh Lemon Juice", "0.5 oz Passion Fruit Syrup", "0.5 oz Honey Syrup", "1 Egg White", "0.5 oz Ruby Port (float)"],
    instructions: ["Dry shake all ingredients except port.", "Add ice and shake again.", "Strain into a coupe glass.", "Float port on top."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "elder-fashion",
    name: "Elder Fashion",
    description: "An Old Fashioned variation with elderflower liqueur.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Bourbon", "0.5 oz St-Germain", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over a large ice cube."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "trinidad-sour",
    name: "Trinidad Sour",
    description: "An Angostura bitters-forward sour that defies convention.",
    history: "Created by Giuseppe González at Clover Club in Brooklyn. Uses an unconventional amount of bitters.",
    category: "Sour",
    ingredients: ["1.5 oz Angostura Bitters", "0.5 oz Rye Whiskey", "1 oz Orgeat", "0.75 oz Fresh Lemon Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Giuseppe González",
    creatorType: "Clover Club"
  },
  {
    slug: "greenpoint",
    name: "Greenpoint",
    description: "A Brooklyn riff on the classic Brooklyn cocktail.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "0.5 oz Yellow Chartreuse", "0.5 oz Sweet Vermouth", "1 dash Angostura Bitters", "1 dash Orange Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Michael McIlroy",
    creatorType: "Milk & Honey"
  },
  {
    slug: "red-hook",
    name: "Red Hook",
    description: "A Brooklyn cocktail variation with maraschino.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "0.5 oz Maraschino Liqueur", "0.5 oz Punt e Mes"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Brandied cherry",
    creator: "Vincenzo Errico",
    creatorType: "Milk & Honey"
  },
  {
    slug: "little-italy",
    name: "Little Italy",
    description: "A rye whiskey cocktail with Cynar and sweet vermouth.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "0.75 oz Cynar", "0.75 oz Sweet Vermouth"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Brandied cherry",
    creator: "Audrey Saunders",
    creatorType: "Pegu Club"
  },
  {
    slug: "gin-basil-smash",
    name: "Gin Basil Smash",
    description: "A refreshing gin cocktail with fresh basil.",
    history: "Created by Jörg Meyer at Le Lion in Hamburg, Germany in 2008.",
    category: "Refreshing",
    ingredients: ["2 oz Gin", "1 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "Handful Fresh Basil Leaves"],
    instructions: ["Muddle basil leaves in shaker.", "Add remaining ingredients with ice.", "Shake well.", "Double-strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Basil sprig",
    creator: "Jörg Meyer",
    creatorType: "Le Lion"
  },
  {
    slug: "bee-s-knees",
    name: "Bee's Knees",
    description: "A Prohibition-era cocktail with honey and gin.",
    history: "Originally created to mask the taste of bathtub gin during Prohibition.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.75 oz Fresh Lemon Juice", "0.75 oz Honey Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Prohibition Era",
    creatorType: "Historical"
  },
  {
    slug: "lions-tail",
    name: "Lion's Tail",
    description: "A bourbon cocktail with allspice dram and lime.",
    category: "Sour",
    ingredients: ["2 oz Bourbon", "0.5 oz Allspice Dram", "0.5 oz Fresh Lime Juice", "0.5 oz Simple Syrup", "1 dash Angostura Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Café Royal Cocktail Book",
    creatorType: "Historical"
  },
  {
    slug: "suffering-bastard",
    name: "Suffering Bastard",
    description: "A ginger-forward tropical cocktail with bourbon and gin.",
    history: "Created by Joe Scialom at the Shepheard Hotel in Cairo during WWII as a hangover cure.",
    category: "Refreshing",
    ingredients: ["1 oz Bourbon", "1 oz Gin", "0.5 oz Fresh Lime Juice", "1 dash Angostura Bitters", "4 oz Ginger Beer"],
    instructions: ["Combine bourbon, gin, lime juice, and bitters in a Collins glass with ice.", "Top with ginger beer.", "Stir gently."],
    glassType: "Collins",
    garnish: "Mint sprig and orange slice",
    creator: "Joe Scialom",
    creatorType: "Shepheard Hotel"
  },
  {
    slug: "chartreuse-swizzle",
    name: "Chartreuse Swizzle",
    description: "A tropical take on the herbal liqueur.",
    category: "Tiki",
    ingredients: ["1.5 oz Green Chartreuse", "0.5 oz Velvet Falernum", "1 oz Pineapple Juice", "0.75 oz Fresh Lime Juice"],
    instructions: ["Combine all ingredients in a Collins glass.", "Fill with crushed ice.", "Swizzle until the glass frosts.", "Top with more crushed ice."],
    glassType: "Collins",
    garnish: "Mint sprig and grated nutmeg",
    creator: "Marco Dionysos",
    creatorType: "Smuggler's Cove"
  },
  {
    slug: "hotel-nacional-special",
    name: "Hotel Nacional Special",
    description: "A pineapple daiquiri with apricot from Havana's famous hotel.",
    history: "Created at the Hotel Nacional de Cuba in the 1930s.",
    category: "Sour",
    ingredients: ["1.5 oz White Rum", "0.5 oz Apricot Brandy", "1 oz Pineapple Juice", "0.5 oz Fresh Lime Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Pineapple wedge",
    creator: "Hotel Nacional de Cuba",
    creatorType: "Hotel"
  },
  {
    slug: "blood-and-sand",
    name: "Blood and Sand",
    description: "A classic Scotch cocktail with cherry and orange.",
    history: "Named after the 1922 Rudolph Valentino film. An equal-parts cocktail.",
    category: "Fruity",
    ingredients: ["0.75 oz Scotch Whisky", "0.75 oz Cherry Heering", "0.75 oz Sweet Vermouth", "0.75 oz Fresh Orange Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange peel",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "improved-whiskey-cocktail",
    name: "Improved Whiskey Cocktail",
    description: "A 19th-century cocktail with absinthe and maraschino.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "0.25 oz Maraschino Liqueur", "1 tsp Simple Syrup", "2 dashes Angostura Bitters", "Absinthe rinse"],
    instructions: ["Rinse a rocks glass with absinthe.", "Combine remaining ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into the prepared glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist",
    creator: "Jerry Thomas",
    creatorType: "Historical"
  },
  {
    slug: "industry-sour",
    name: "Industry Sour",
    description: "A Fernet sour popular among bartenders.",
    category: "Sour",
    ingredients: ["1 oz Fernet-Branca", "1 oz Green Chartreuse", "1 oz Fresh Lime Juice", "1 oz Simple Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Lime wheel",
    creator: "Ted Kilgore",
    creatorType: "Planter's House"
  },
  {
    slug: "toronto-cocktail",
    name: "Toronto",
    description: "A Canadian rye cocktail with Fernet-Branca.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Canadian Rye Whiskey", "0.25 oz Fernet-Branca", "0.25 oz Simple Syrup", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "corn-n-oil",
    name: "Corn 'n' Oil",
    description: "A Bajan rum cocktail with falernum and bitters.",
    category: "Tiki",
    ingredients: ["2 oz Blackstrap Rum", "0.5 oz Velvet Falernum", "0.5 oz Fresh Lime Juice", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a rocks glass.", "Add ice and stir.", "No shaking needed."],
    glassType: "Old Fashioned",
    garnish: "Lime wheel",
    creator: "Barbados",
    creatorType: "Traditional"
  },
  {
    slug: "fancy-free",
    name: "Fancy Free",
    description: "A bourbon cocktail with maraschino and orange bitters.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Bourbon", "0.5 oz Maraschino Liqueur", "1 dash Angostura Bitters", "1 dash Orange Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Crosby Gaige",
    creatorType: "Historical"
  },
  {
    slug: "old-cuban",
    name: "Old Cuban",
    description: "A sophisticated mojito-champagne hybrid.",
    history: "Created by Audrey Saunders at Pegu Club.",
    category: "Sparkling",
    ingredients: ["1.5 oz Aged Rum", "0.75 oz Fresh Lime Juice", "1 oz Simple Syrup", "6 Mint Leaves", "2 dashes Angostura Bitters", "2 oz Champagne"],
    instructions: ["Muddle mint leaves in shaker.", "Add rum, lime juice, syrup, and bitters with ice.", "Shake well.", "Double-strain into a coupe glass.", "Top with champagne."],
    glassType: "Coupe",
    garnish: "Mint leaf",
    creator: "Audrey Saunders",
    creatorType: "Pegu Club"
  },
  {
    slug: "new-york-sour",
    name: "New York Sour",
    description: "A whiskey sour topped with a red wine float.",
    category: "Sour",
    ingredients: ["2 oz Bourbon or Rye", "1 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "1 Egg White", "0.5 oz Dry Red Wine (float)"],
    instructions: ["Dry shake bourbon, lemon juice, syrup, and egg white.", "Add ice and shake again.", "Strain into a rocks glass over ice.", "Float red wine on top."],
    glassType: "Old Fashioned",
    garnish: "Cherry",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "corpse-reviver-no-2",
    name: "Corpse Reviver No. 2",
    description: "The classic morning-after cocktail.",
    history: "From the Savoy Cocktail Book by Harry Craddock, 1930.",
    category: "Sour",
    ingredients: ["0.75 oz Gin", "0.75 oz Cointreau", "0.75 oz Lillet Blanc", "0.75 oz Fresh Lemon Juice", "1 dash Absinthe"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Cherry",
    creator: "Harry Craddock",
    creatorType: "Savoy Hotel"
  },
  {
    slug: "jungle-juice",
    name: "Jungle Juice",
    description: "A tropical tequila cocktail with passion fruit.",
    category: "Tiki",
    ingredients: ["1.5 oz Tequila Blanco", "0.5 oz Mezcal", "1 oz Passion Fruit Puree", "0.75 oz Fresh Lime Juice", "0.5 oz Agave Nectar"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Lime wheel",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "gunshop-fizz",
    name: "Gunshop Fizz",
    description: "A fruity and fizzy gin cocktail with raspberry.",
    category: "Fizz",
    ingredients: ["2 oz Gin", "0.75 oz Fresh Lemon Juice", "0.5 oz Raspberry Syrup", "1 Egg White", "2 oz Club Soda"],
    instructions: ["Dry shake gin, lemon juice, raspberry syrup, and egg white.", "Add ice and shake again.", "Strain into a Collins glass.", "Top with club soda."],
    glassType: "Collins",
    garnish: "Raspberries",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "peaches-and-cream",
    name: "Peaches and Cream",
    description: "A creamy bourbon cocktail with peach.",
    category: "Creamy",
    ingredients: ["2 oz Bourbon", "1 oz Peach Puree", "0.5 oz Fresh Lemon Juice", "0.5 oz Honey Syrup", "1 oz Heavy Cream"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Peach slice",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "espresso-martini-v2",
    name: "Death & Co Espresso Martini",
    description: "A refined take on the coffee cocktail classic.",
    category: "Creamy",
    ingredients: ["1.5 oz Vodka", "0.5 oz Coffee Liqueur", "1 oz Fresh Espresso", "0.25 oz Demerara Syrup", "2 dashes Mole Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake vigorously.", "Double-strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Three coffee beans",
    creator: "Death & Co",
    creatorType: "Bar"
  },
  {
    slug: "banana-daiquiri-modern",
    name: "Modern Banana Daiquiri",
    description: "A craft cocktail take on the blended classic.",
    category: "Tiki",
    ingredients: ["2 oz White Rum", "0.75 oz Fresh Lime Juice", "0.5 oz Banana Liqueur", "0.5 oz Simple Syrup", "Half Ripe Banana"],
    instructions: ["Combine all ingredients in a blender with ice.", "Blend until smooth.", "Pour into a coupe glass."],
    glassType: "Coupe",
    garnish: "Banana chip",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "fogcutter",
    name: "Fog Cutter",
    description: "A potent tiki cocktail with multiple spirits.",
    history: "Created by Trader Vic in 1947.",
    category: "Tiki",
    ingredients: ["1.5 oz White Rum", "0.5 oz Cognac", "0.5 oz Gin", "2 oz Fresh Orange Juice", "1 oz Fresh Lemon Juice", "0.5 oz Orgeat", "0.5 oz Dry Sherry (float)"],
    instructions: ["Combine all ingredients except sherry in a shaker with ice.", "Shake well.", "Strain into a tiki mug or Collins glass with ice.", "Float sherry on top."],
    glassType: "Tiki Mug",
    garnish: "Mint sprig",
    creator: "Trader Vic",
    creatorType: "Trader Vic's"
  },
  {
    slug: "scotch-mist",
    name: "Scotch Mist",
    description: "A simple, refreshing Scotch cocktail served on crushed ice.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Scotch Whisky", "1 Lemon Twist"],
    instructions: ["Pour Scotch over crushed ice in a rocks glass.", "Express lemon oils over the drink and drop in the twist.", "Stir briefly."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "pisco-sour",
    name: "Pisco Sour",
    description: "The national cocktail of Peru and Chile.",
    category: "Sour",
    ingredients: ["2 oz Pisco", "1 oz Fresh Lime Juice", "0.75 oz Simple Syrup", "1 Egg White", "3 dashes Angostura Bitters"],
    instructions: ["Dry shake pisco, lime juice, syrup, and egg white.", "Add ice and shake again.", "Strain into a rocks glass.", "Dash bitters on top of the foam."],
    glassType: "Old Fashioned",
    garnish: "Angostura bitters drops on foam",
    creator: "Victor Vaughen Morris",
    creatorType: "Historical"
  },
  {
    slug: "caipirinha",
    name: "Caipirinha",
    description: "Brazil's national cocktail made with cachaça.",
    category: "Sour",
    ingredients: ["2 oz Cachaça", "1 Lime (cut into wedges)", "2 tsp Sugar"],
    instructions: ["Muddle lime wedges and sugar in a rocks glass.", "Fill with ice.", "Add cachaça.", "Stir well."],
    glassType: "Old Fashioned",
    garnish: "Lime wedge",
    creator: "Brazil",
    creatorType: "Traditional"
  },
  {
    slug: "ramos-gin-fizz",
    name: "Ramos Gin Fizz",
    description: "The legendary New Orleans cocktail requiring extensive shaking.",
    history: "Created by Henry C. Ramos in New Orleans in 1888.",
    category: "Fizz",
    ingredients: ["2 oz Gin", "0.5 oz Fresh Lemon Juice", "0.5 oz Fresh Lime Juice", "1 oz Simple Syrup", "1 oz Heavy Cream", "1 Egg White", "3 drops Orange Flower Water", "2 oz Club Soda"],
    instructions: ["Combine all ingredients except soda in a shaker.", "Dry shake vigorously for at least 1 minute.", "Add ice and shake again for 1 minute.", "Strain into a Collins glass.", "Top with club soda."],
    glassType: "Collins",
    garnish: "None",
    creator: "Henry C. Ramos",
    creatorType: "Historical"
  },
  {
    slug: "french-75",
    name: "French 75",
    description: "A classic champagne cocktail with gin and lemon.",
    history: "Named after the French 75mm field gun for its powerful kick.",
    category: "Sparkling",
    ingredients: ["1 oz Gin", "0.5 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "3 oz Champagne"],
    instructions: ["Combine gin, lemon juice, and syrup in a shaker with ice.", "Shake well.", "Strain into a champagne flute.", "Top with champagne."],
    glassType: "Champagne Flute",
    garnish: "Lemon twist",
    creator: "Harry MacElhone",
    creatorType: "Harry's New York Bar"
  },
  {
    slug: "death-flip",
    name: "Death Flip",
    description: "A decadent whole-egg cocktail with tequila and Chartreuse.",
    category: "Flip",
    ingredients: ["1 oz Tequila Blanco", "0.5 oz Yellow Chartreuse", "0.5 oz Jägermeister", "0.5 oz Simple Syrup", "1 Whole Egg"],
    instructions: ["Combine all ingredients in a shaker.", "Dry shake vigorously.", "Add ice and shake again.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Grated nutmeg",
    creator: "Chris Hysted-Adams",
    creatorType: "Black Pearl"
  },
  {
    slug: "mexican-el-diablo",
    name: "El Diablo",
    description: "A tequila cocktail with cassis and ginger.",
    category: "Refreshing",
    ingredients: ["1.5 oz Tequila Blanco", "0.5 oz Crème de Cassis", "0.5 oz Fresh Lime Juice", "3 oz Ginger Beer"],
    instructions: ["Combine tequila, cassis, and lime juice in a Collins glass with ice.", "Top with ginger beer.", "Stir gently."],
    glassType: "Collins",
    garnish: "Lime wheel",
    creator: "Trader Vic",
    creatorType: "Trader Vic's"
  },
  {
    slug: "latin-quarter",
    name: "Latin Quarter",
    description: "A cognac cocktail with Amer Picon and lemon.",
    category: "Sour",
    ingredients: ["1.5 oz Cognac", "0.75 oz Amer Picon (or substitute)", "0.75 oz Fresh Lemon Juice", "0.5 oz Simple Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "cynar-flip",
    name: "Cynar Flip",
    description: "A rich, velvety flip featuring artichoke amaro.",
    category: "Flip",
    ingredients: ["2 oz Cynar", "0.5 oz Simple Syrup", "1 Whole Egg"],
    instructions: ["Combine all ingredients in a shaker.", "Dry shake vigorously.", "Add ice and shake again.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Grated nutmeg",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "left-hand",
    name: "Left Hand",
    description: "A chocolate-bitter Negroni variation.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Bourbon", "0.75 oz Sweet Vermouth", "0.75 oz Campari", "2 dashes Chocolate Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Brandied cherry",
    creator: "Sam Ross",
    creatorType: "Milk & Honey"
  },
  {
    slug: "bitter-giuseppe",
    name: "Bitter Giuseppe",
    description: "A stirred amaro cocktail with citrus and vermouth.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Cynar", "1 oz Sweet Vermouth", "0.25 oz Fresh Lemon Juice", "6 dashes Orange Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over a large ice cube."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist",
    creator: "Stephen Cole",
    creatorType: "Amor y Amargo"
  },
  {
    slug: "strange-bedfellows",
    name: "Strange Bedfellows",
    description: "A rum and scotch cocktail with unique flavor combinations.",
    category: "Spirit-Forward",
    ingredients: ["1 oz Aged Rum", "1 oz Blended Scotch", "0.5 oz Bénédictine", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "queen-elizabeth",
    name: "Queen Elizabeth",
    description: "A gin cocktail with Bénédictine and dry vermouth.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Gin", "0.5 oz Dry Vermouth", "0.5 oz Bénédictine"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "la-rosita",
    name: "La Rosita",
    description: "A tequila Negroni variation with two vermouths.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Tequila Reposado", "0.5 oz Sweet Vermouth", "0.5 oz Dry Vermouth", "0.5 oz Campari", "1 dash Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Orange twist",
    creator: "Gary Regan",
    creatorType: "Author"
  },

  // ========== PROHIBITION ERA CLASSICS ==========
  {
    slug: "sidecar",
    name: "Sidecar",
    description: "A cognac-based sour that became a Prohibition staple.",
    history: "Created in Paris during World War I, this became one of the most popular speakeasy drinks.",
    category: "Sour",
    ingredients: ["2 oz Cognac", "0.75 oz Cointreau", "0.75 oz Fresh Lemon Juice"],
    instructions: ["Optionally rim glass with sugar.", "Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Harry MacElhone",
    creatorType: "Harry's New York Bar"
  },
  {
    slug: "the-last-word",
    name: "The Last Word",
    description: "An equal-parts cocktail that's become a bartender favorite.",
    history: "Created at the Detroit Athletic Club during Prohibition, rediscovered by Murray Stenson in Seattle.",
    category: "Sour",
    ingredients: ["0.75 oz Gin", "0.75 oz Green Chartreuse", "0.75 oz Maraschino Liqueur", "0.75 oz Fresh Lime Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Cherry",
    creator: "Detroit Athletic Club",
    creatorType: "Historical"
  },
  {
    slug: "white-lady",
    name: "White Lady",
    description: "An elegant gin sour with optional egg white.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.75 oz Cointreau", "0.75 oz Fresh Lemon Juice", "1 Egg White (optional)"],
    instructions: ["Dry shake all ingredients if using egg white.", "Add ice and shake again.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange peel",
    creator: "Harry MacElhone",
    creatorType: "Harry's New York Bar"
  },
  {
    slug: "mary-pickford",
    name: "Mary Pickford",
    description: "A tropical rum cocktail named after the silent film star.",
    history: "Created in Havana during Prohibition when Americans traveled to Cuba for legal drinks.",
    category: "Fruity",
    ingredients: ["2 oz White Rum", "2 oz Pineapple Juice", "1 tsp Grenadine", "1 tsp Maraschino Liqueur"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Cherry",
    creator: "Hotel Nacional de Cuba",
    creatorType: "Hotel"
  },
  {
    slug: "scofflaw",
    name: "Scofflaw",
    description: "A rye cocktail named after those who defied Prohibition.",
    history: "Created in 1924 at Harry's New York Bar in Paris, the term 'scofflaw' was coined for lawbreakers.",
    category: "Sour",
    ingredients: ["1.5 oz Rye Whiskey", "1 oz Dry Vermouth", "0.5 oz Fresh Lemon Juice", "0.5 oz Grenadine", "2 dashes Orange Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Jock Lauriston",
    creatorType: "Historical"
  },
  {
    slug: "hanky-panky",
    name: "Hanky Panky",
    description: "A gin and vermouth cocktail with a Fernet kick.",
    history: "Created by Ada Coleman at London's Savoy Hotel for actor Sir Charles Hawtrey.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Gin", "1.5 oz Sweet Vermouth", "2 dashes Fernet-Branca"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Ada Coleman",
    creatorType: "Savoy Hotel"
  },
  {
    slug: "southside",
    name: "Southside",
    description: "A minty gin cocktail from Chicago speakeasies.",
    history: "Believed to have originated in Chicago's South Side during Prohibition.",
    category: "Refreshing",
    ingredients: ["2 oz Gin", "0.75 oz Fresh Lime Juice", "0.75 oz Simple Syrup", "6 Mint Leaves"],
    instructions: ["Muddle mint leaves with syrup in shaker.", "Add gin and lime juice with ice.", "Shake well.", "Fine strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Mint leaf",
    creator: "Chicago Speakeasies",
    creatorType: "Historical"
  },
  {
    slug: "monkey-gland",
    name: "Monkey Gland",
    description: "A gin cocktail named after a bizarre 1920s medical fad.",
    category: "Fruity",
    ingredients: ["2 oz Gin", "1.5 oz Fresh Orange Juice", "1 tsp Grenadine", "0.5 tsp Absinthe"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Harry MacElhone",
    creatorType: "Harry's New York Bar"
  },
  {
    slug: "clover-club",
    name: "Clover Club",
    description: "A raspberry gin cocktail from a Philadelphia gentlemen's club.",
    history: "Named after the Clover Club of Philadelphia, a pre-Prohibition men's club.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.75 oz Fresh Lemon Juice", "0.5 oz Raspberry Syrup", "0.25 oz Dry Vermouth", "1 Egg White"],
    instructions: ["Dry shake all ingredients vigorously.", "Add ice and shake again.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Raspberries",
    creator: "Clover Club Philadelphia",
    creatorType: "Historical"
  },
  {
    slug: "pegu-club",
    name: "Pegu Club",
    description: "A colonial gin cocktail from British Burma.",
    history: "Originated at the Pegu Club in Rangoon (now Yangon), Myanmar, for British officers.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.75 oz Dry Curaçao", "0.75 oz Fresh Lime Juice", "1 dash Angostura Bitters", "1 dash Orange Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lime wheel",
    creator: "Pegu Club Burma",
    creatorType: "Historical"
  },
  {
    slug: "gin-rickey",
    name: "Gin Rickey",
    description: "F. Scott Fitzgerald's favorite cocktail, featured in The Great Gatsby.",
    category: "Refreshing",
    ingredients: ["2 oz Gin", "0.5 oz Fresh Lime Juice", "Club Soda"],
    instructions: ["Build in a highball glass over ice.", "Add gin and lime juice.", "Top with club soda.", "Stir gently."],
    glassType: "Highball",
    garnish: "Lime wheel",
    creator: "Historical",
    creatorType: "Classic"
  },

  // ========== MORE MODERN CLASSICS ==========
  {
    slug: "bramble",
    name: "Bramble",
    description: "A British gin classic with blackberry liqueur.",
    history: "Created by Dick Bradsell in London in 1984.",
    category: "Sour",
    ingredients: ["2 oz Gin", "1 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "0.5 oz Crème de Mûre (blackberry liqueur)"],
    instructions: ["Combine gin, lemon juice, and syrup in a shaker with ice.", "Shake well.", "Strain into a rocks glass filled with crushed ice.", "Drizzle crème de mûre over the top."],
    glassType: "Old Fashioned",
    garnish: "Blackberry and lemon slice",
    creator: "Dick Bradsell",
    creatorType: "London"
  },
  {
    slug: "breakfast-martini",
    name: "Breakfast Martini",
    description: "A gin cocktail featuring orange marmalade.",
    history: "Created by Salvatore Calabrese in London.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.5 oz Cointreau", "0.5 oz Fresh Lemon Juice", "1 tbsp Orange Marmalade"],
    instructions: ["Stir marmalade with gin until dissolved.", "Add remaining ingredients with ice.", "Shake well.", "Fine strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist and toast triangle",
    creator: "Salvatore Calabrese",
    creatorType: "London"
  },
  {
    slug: "tommy-gun",
    name: "Tommy Gun",
    description: "A modern whiskey cocktail with honey and chamomile.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Bourbon", "0.5 oz Chamomile Honey Syrup", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over a large ice cube."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "boulevardier",
    name: "Boulevardier",
    description: "A bourbon Negroni that predates its gin sibling in America.",
    history: "Created by Erskine Gwynne, an American writer in Paris, in the 1920s.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Bourbon", "1 oz Sweet Vermouth", "1 oz Campari"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Orange twist",
    creator: "Erskine Gwynne",
    creatorType: "Historical"
  },
  {
    slug: "vieux-carre",
    name: "Vieux Carré",
    description: "A complex New Orleans classic with rye, cognac, and two bitters.",
    history: "Created at the Carousel Bar in the Hotel Monteleone in New Orleans.",
    category: "Spirit-Forward",
    ingredients: ["0.75 oz Rye Whiskey", "0.75 oz Cognac", "0.75 oz Sweet Vermouth", "0.25 oz Bénédictine", "2 dashes Peychaud's Bitters", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a rocks glass over a large ice cube."],
    glassType: "Old Fashioned",
    garnish: "Cherry",
    creator: "Hotel Monteleone",
    creatorType: "Historical"
  },
  {
    slug: "aviation",
    name: "Aviation",
    description: "A floral gin cocktail with crème de violette.",
    history: "Created in the early 1900s, popularized by Hugo Ensslin.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.5 oz Maraschino Liqueur", "0.75 oz Fresh Lemon Juice", "0.25 oz Crème de Violette"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Cherry",
    creator: "Hugo Ensslin",
    creatorType: "Historical"
  },
  {
    slug: "hemingway-daiquiri",
    name: "Hemingway Daiquiri",
    description: "A grapefruit daiquiri variation created for Ernest Hemingway.",
    history: "Also called Papa Doble, made for Hemingway at El Floridita in Havana.",
    category: "Sour",
    ingredients: ["2 oz White Rum", "0.75 oz Fresh Lime Juice", "0.5 oz Fresh Grapefruit Juice", "0.5 oz Maraschino Liqueur"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Grapefruit twist",
    creator: "Constantino Ribalaigua",
    creatorType: "El Floridita"
  },
  {
    slug: "twelve-mile-limit",
    name: "Twelve Mile Limit",
    description: "A Prohibition-era cocktail named after the offshore limit for drinking.",
    category: "Sour",
    ingredients: ["1 oz White Rum", "0.5 oz Rye Whiskey", "0.5 oz Cognac", "0.5 oz Fresh Lemon Juice", "0.5 oz Grenadine"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Tommy Millard",
    creatorType: "Historical"
  },
  {
    slug: "queens-park-swizzle",
    name: "Queen's Park Swizzle",
    description: "A rum cocktail from Trinidad's Queen's Park Hotel.",
    category: "Refreshing",
    ingredients: ["2 oz Demerara Rum", "0.75 oz Fresh Lime Juice", "0.75 oz Simple Syrup", "6 Mint Leaves", "2 dashes Angostura Bitters"],
    instructions: ["Add mint, lime juice, and syrup to a Collins glass.", "Fill with crushed ice.", "Add rum.", "Swizzle until glass frosts.", "Top with more ice and dash bitters."],
    glassType: "Collins",
    garnish: "Mint sprig",
    creator: "Queen's Park Hotel",
    creatorType: "Trinidad"
  },
  {
    slug: "el-presidente",
    name: "El Presidente",
    description: "A Cuban rum cocktail from the pre-Prohibition era.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz White Rum", "0.75 oz Dry Vermouth", "0.75 oz Orange Curaçao", "1 tsp Grenadine"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Cuba",
    creatorType: "Historical"
  },
  {
    slug: "singapore-sling",
    name: "Singapore Sling",
    description: "The iconic cocktail from the Raffles Hotel.",
    history: "Created by Ngiam Tong Boon at the Long Bar in Singapore's Raffles Hotel around 1915.",
    category: "Fruity",
    ingredients: ["1 oz Gin", "0.5 oz Cherry Heering", "0.25 oz Cointreau", "0.25 oz Bénédictine", "4 oz Pineapple Juice", "0.5 oz Fresh Lime Juice", "0.25 oz Grenadine", "1 dash Angostura Bitters"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a hurricane or sling glass with ice."],
    glassType: "Hurricane",
    garnish: "Pineapple wedge and cherry",
    creator: "Ngiam Tong Boon",
    creatorType: "Raffles Hotel"
  },
  {
    slug: "brandy-alexander",
    name: "Brandy Alexander",
    description: "A creamy after-dinner cocktail with cognac and chocolate.",
    category: "Creamy",
    ingredients: ["1 oz Cognac", "1 oz Crème de Cacao (dark)", "1 oz Heavy Cream"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Grated nutmeg",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "grasshopper",
    name: "Grasshopper",
    description: "A minty green after-dinner cocktail.",
    history: "Created at Tujague's in New Orleans around 1918.",
    category: "Creamy",
    ingredients: ["1 oz Crème de Menthe (green)", "1 oz Crème de Cacao (white)", "1 oz Heavy Cream"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Mint leaf",
    creator: "Tujague's",
    creatorType: "New Orleans"
  },
  {
    slug: "rusty-nail",
    name: "Rusty Nail",
    description: "A simple Scotch and Drambuie cocktail.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Scotch Whisky", "0.75 oz Drambuie"],
    instructions: ["Combine ingredients in a rocks glass over ice.", "Stir briefly."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "godfather",
    name: "Godfather",
    description: "A smooth blend of Scotch and amaretto.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Scotch Whisky", "0.75 oz Amaretto"],
    instructions: ["Combine ingredients in a rocks glass over ice.", "Stir briefly."],
    glassType: "Old Fashioned",
    garnish: "None",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "stinger",
    name: "Stinger",
    description: "A cognac and crème de menthe after-dinner classic.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Cognac", "0.75 oz White Crème de Menthe"],
    instructions: ["Combine ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "None",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "between-the-sheets",
    name: "Between the Sheets",
    description: "A potent Prohibition-era cocktail with rum and cognac.",
    category: "Sour",
    ingredients: ["0.75 oz White Rum", "0.75 oz Cognac", "0.75 oz Cointreau", "0.5 oz Fresh Lemon Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Harry MacElhone",
    creatorType: "Harry's New York Bar"
  },
  {
    slug: "jack-rose",
    name: "Jack Rose",
    description: "An applejack cocktail with a beautiful pink hue.",
    category: "Sour",
    ingredients: ["2 oz Applejack", "0.75 oz Fresh Lime Juice", "0.5 oz Grenadine"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Apple slice",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "cable-car",
    name: "Cable Car",
    description: "A modern San Francisco classic with spiced rum.",
    history: "Created by Tony Abou-Ganim at the Starlight Room in San Francisco.",
    category: "Sour",
    ingredients: ["1.5 oz Spiced Rum", "0.75 oz Orange Curaçao", "1 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "Cinnamon sugar rim"],
    instructions: ["Rim glass with cinnamon sugar.", "Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into the prepared glass."],
    glassType: "Coupe",
    garnish: "Orange twist",
    creator: "Tony Abou-Ganim",
    creatorType: "Starlight Room"
  },
  {
    slug: "aperol-spritz",
    name: "Aperol Spritz",
    description: "Italy's beloved aperitivo cocktail.",
    category: "Sparkling",
    ingredients: ["3 oz Prosecco", "2 oz Aperol", "1 oz Club Soda"],
    instructions: ["Build in a wine glass over ice.", "Add prosecco, Aperol, and soda.", "Stir gently."],
    glassType: "Wine Glass",
    garnish: "Orange slice",
    creator: "Italy",
    creatorType: "Traditional"
  },
  {
    slug: "hugo-spritz",
    name: "Hugo Spritz",
    description: "A floral Italian spritz with elderflower.",
    category: "Sparkling",
    ingredients: ["3 oz Prosecco", "1 oz St-Germain", "2 oz Club Soda", "6 Mint Leaves"],
    instructions: ["Build in a wine glass over ice.", "Add prosecco, St-Germain, and soda.", "Add mint leaves.", "Stir gently."],
    glassType: "Wine Glass",
    garnish: "Mint sprig and lime wheel",
    creator: "Italy",
    creatorType: "Traditional"
  },
  {
    slug: "amaretto-sour",
    name: "Amaretto Sour",
    description: "A classic almond liqueur sour elevated with bourbon.",
    category: "Sour",
    ingredients: ["1.5 oz Amaretto", "0.75 oz Bourbon", "1 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "1 Egg White"],
    instructions: ["Dry shake all ingredients.", "Add ice and shake again.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Cherry",
    creator: "Jeffrey Morgenthaler",
    creatorType: "Modern Classic"
  },
  {
    slug: "dark-n-stormy",
    name: "Dark 'n' Stormy",
    description: "A Bermudian classic with dark rum and ginger beer.",
    category: "Refreshing",
    ingredients: ["2 oz Gosling's Black Seal Rum", "4 oz Ginger Beer", "0.5 oz Fresh Lime Juice"],
    instructions: ["Build in a highball glass over ice.", "Add lime juice and ginger beer.", "Float rum on top."],
    glassType: "Highball",
    garnish: "Lime wedge",
    creator: "Bermuda",
    creatorType: "Traditional"
  },
  {
    slug: "daiquiri-classic",
    name: "Classic Daiquiri",
    description: "The Cuban rum sour that defined a category.",
    history: "Named after a beach near Santiago, Cuba, where American mining engineers first mixed it.",
    category: "Sour",
    ingredients: ["2 oz White Rum", "1 oz Fresh Lime Juice", "0.75 oz Simple Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lime wheel",
    creator: "Cuba",
    creatorType: "Traditional"
  },
  {
    slug: "hurricane",
    name: "Hurricane",
    description: "The potent New Orleans tiki-style cocktail.",
    history: "Created by Pat O'Brien in New Orleans during World War II.",
    category: "Tiki",
    ingredients: ["2 oz Light Rum", "2 oz Dark Rum", "2 oz Passion Fruit Juice", "1 oz Fresh Orange Juice", "0.5 oz Fresh Lime Juice", "1 oz Simple Syrup", "1 tbsp Grenadine"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a hurricane glass with ice."],
    glassType: "Hurricane",
    garnish: "Orange slice and cherry",
    creator: "Pat O'Brien",
    creatorType: "Pat O'Brien's Bar"
  },
  {
    slug: "planter-s-punch",
    name: "Planter's Punch",
    description: "A classic rum punch following the traditional formula.",
    history: "The classic recipe follows 'One of sour, two of sweet, three of strong, four of weak.'",
    category: "Tiki",
    ingredients: ["3 oz Dark Jamaican Rum", "1 oz Fresh Lime Juice", "2 oz Simple Syrup", "4 oz Fresh Orange Juice", "2 dashes Angostura Bitters", "0.5 oz Grenadine"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a tall glass with ice."],
    glassType: "Collins",
    garnish: "Orange slice, cherry, and mint",
    creator: "Jamaica",
    creatorType: "Traditional"
  },
  {
    slug: "pina-colada",
    name: "Piña Colada",
    description: "Puerto Rico's national drink.",
    history: "Created at the Caribe Hilton in San Juan in 1954.",
    category: "Tiki",
    ingredients: ["2 oz White Rum", "2 oz Coconut Cream", "4 oz Pineapple Juice"],
    instructions: ["Combine all ingredients in a blender with ice.", "Blend until smooth.", "Pour into a hurricane or poco grande glass."],
    glassType: "Hurricane",
    garnish: "Pineapple wedge and cherry",
    creator: "Caribe Hilton",
    creatorType: "Hotel"
  },
  {
    slug: "long-island-iced-tea",
    name: "Long Island Iced Tea",
    description: "A potent multi-spirit cocktail disguised as iced tea.",
    category: "Refreshing",
    ingredients: ["0.5 oz Vodka", "0.5 oz Gin", "0.5 oz White Rum", "0.5 oz Tequila", "0.5 oz Triple Sec", "0.75 oz Fresh Lemon Juice", "0.5 oz Simple Syrup", "Cola"],
    instructions: ["Combine all spirits, lemon juice, and syrup in a shaker with ice.", "Shake well.", "Strain into a Collins glass with ice.", "Top with a splash of cola."],
    glassType: "Collins",
    garnish: "Lemon wedge",
    creator: "Robert Butt",
    creatorType: "Oak Beach Inn"
  },
  {
    slug: "cuba-libre",
    name: "Cuba Libre",
    description: "The classic rum and cola with lime.",
    history: "Created around 1900 in Havana after Coca-Cola arrived in Cuba.",
    category: "Refreshing",
    ingredients: ["2 oz White Rum", "4 oz Cola", "0.5 oz Fresh Lime Juice", "Lime wedge"],
    instructions: ["Build in a highball glass over ice.", "Add rum and lime juice.", "Top with cola.", "Stir gently.", "Squeeze lime wedge into drink."],
    glassType: "Highball",
    garnish: "Lime wedge",
    creator: "Cuba",
    creatorType: "Traditional"
  },
  {
    slug: "mojito",
    name: "Mojito",
    description: "Cuba's beloved mint and lime rum cocktail.",
    category: "Refreshing",
    ingredients: ["2 oz White Rum", "1 oz Fresh Lime Juice", "0.75 oz Simple Syrup", "6 Mint Leaves", "Club Soda"],
    instructions: ["Muddle mint with lime juice and syrup in a highball glass.", "Add rum and fill with ice.", "Top with club soda.", "Stir gently."],
    glassType: "Highball",
    garnish: "Mint sprig and lime wheel",
    creator: "Cuba",
    creatorType: "Traditional"
  },
  {
    slug: "irish-mule",
    name: "Irish Mule",
    description: "A whiskey variation on the Moscow Mule.",
    category: "Refreshing",
    ingredients: ["2 oz Irish Whiskey", "0.5 oz Fresh Lime Juice", "4 oz Ginger Beer"],
    instructions: ["Build in a copper mug or highball glass with ice.", "Add whiskey and lime juice.", "Top with ginger beer.", "Stir gently."],
    glassType: "Copper Mug",
    garnish: "Lime wheel",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "kentucky-mule",
    name: "Kentucky Mule",
    description: "A bourbon spin on the Moscow Mule.",
    category: "Refreshing",
    ingredients: ["2 oz Bourbon", "0.5 oz Fresh Lime Juice", "4 oz Ginger Beer"],
    instructions: ["Build in a copper mug or highball glass with ice.", "Add bourbon and lime juice.", "Top with ginger beer.", "Stir gently."],
    glassType: "Copper Mug",
    garnish: "Lime wheel",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "paloma",
    name: "Paloma",
    description: "Mexico's most popular tequila cocktail.",
    category: "Refreshing",
    ingredients: ["2 oz Tequila Blanco", "0.5 oz Fresh Lime Juice", "Grapefruit Soda", "Pinch of Salt"],
    instructions: ["Rim glass with salt if desired.", "Build in a highball glass over ice.", "Add tequila and lime juice.", "Top with grapefruit soda.", "Stir gently."],
    glassType: "Highball",
    garnish: "Grapefruit wedge",
    creator: "Mexico",
    creatorType: "Traditional"
  },
  {
    slug: "moscow-mule",
    name: "Moscow Mule",
    description: "The vodka, ginger beer, and lime classic served in a copper mug.",
    history: "Created in 1941 as a marketing effort to sell vodka in America.",
    category: "Refreshing",
    ingredients: ["2 oz Vodka", "0.5 oz Fresh Lime Juice", "4 oz Ginger Beer"],
    instructions: ["Build in a copper mug with ice.", "Add vodka and lime juice.", "Top with ginger beer.", "Stir gently."],
    glassType: "Copper Mug",
    garnish: "Lime wheel",
    creator: "John Martin & Jack Morgan",
    creatorType: "Historical"
  },
  {
    slug: "whiskey-sour",
    name: "Whiskey Sour",
    description: "The quintessential American whiskey cocktail.",
    category: "Sour",
    ingredients: ["2 oz Bourbon", "0.75 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "1 Egg White (optional)"],
    instructions: ["Dry shake all ingredients if using egg white.", "Add ice and shake again.", "Strain into a rocks glass over ice."],
    glassType: "Old Fashioned",
    garnish: "Cherry and orange slice",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "gimlet",
    name: "Gimlet",
    description: "A simple gin and lime classic.",
    history: "Originally made with Rose's lime cordial for British Navy sailors.",
    category: "Sour",
    ingredients: ["2 oz Gin", "0.75 oz Fresh Lime Juice", "0.75 oz Simple Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lime wheel",
    creator: "British Navy",
    creatorType: "Historical"
  },
  {
    slug: "vodka-gimlet",
    name: "Vodka Gimlet",
    description: "A vodka variation on the classic gimlet.",
    category: "Sour",
    ingredients: ["2 oz Vodka", "0.75 oz Fresh Lime Juice", "0.75 oz Simple Syrup"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lime wheel",
    creator: "Modern Classic",
    creatorType: "Contemporary"
  },
  {
    slug: "cosmopolitan",
    name: "Cosmopolitan",
    description: "The pink vodka cocktail that defined the 1990s.",
    history: "Popularized by Sex and the City, created by Toby Cecchini.",
    category: "Sour",
    ingredients: ["1.5 oz Citrus Vodka", "0.75 oz Cointreau", "0.75 oz Fresh Lime Juice", "1 oz Cranberry Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a martini glass."],
    glassType: "Martini",
    garnish: "Orange twist",
    creator: "Toby Cecchini",
    creatorType: "Modern Classic"
  },
  {
    slug: "lemon-drop-martini",
    name: "Lemon Drop Martini",
    description: "A sweet-tart vodka cocktail with sugar rim.",
    category: "Sour",
    ingredients: ["2 oz Vodka", "1 oz Fresh Lemon Juice", "0.5 oz Triple Sec", "0.5 oz Simple Syrup", "Sugar rim"],
    instructions: ["Rim glass with sugar.", "Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into the prepared glass."],
    glassType: "Martini",
    garnish: "Lemon twist",
    creator: "Norman Jay Hobday",
    creatorType: "Historical"
  },
  {
    slug: "appletini",
    name: "Appletini",
    description: "A sweet apple-flavored vodka martini.",
    category: "Fruity",
    ingredients: ["1.5 oz Vodka", "1 oz Sour Apple Schnapps", "0.5 oz Fresh Lemon Juice"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake well.", "Strain into a martini glass."],
    glassType: "Martini",
    garnish: "Apple slice",
    creator: "1990s",
    creatorType: "Historical"
  },
  {
    slug: "martinez",
    name: "Martinez",
    description: "The precursor to the modern Martini.",
    category: "Spirit-Forward",
    ingredients: ["1.5 oz Old Tom Gin", "1.5 oz Sweet Vermouth", "0.25 oz Maraschino Liqueur", "2 dashes Angostura Bitters"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a coupe glass."],
    glassType: "Coupe",
    garnish: "Lemon twist",
    creator: "Jerry Thomas",
    creatorType: "Historical"
  },
  {
    slug: "vesper",
    name: "Vesper",
    description: "James Bond's famous martini from Casino Royale.",
    history: "Created by Ian Fleming for the novel Casino Royale in 1953.",
    category: "Spirit-Forward",
    ingredients: ["3 oz Gin", "1 oz Vodka", "0.5 oz Lillet Blanc"],
    instructions: ["Combine all ingredients in a shaker with ice.", "Shake until ice cold.", "Strain into a martini glass."],
    glassType: "Martini",
    garnish: "Lemon twist",
    creator: "Ian Fleming",
    creatorType: "Author"
  },
  {
    slug: "gibson",
    name: "Gibson",
    description: "A classic martini garnished with cocktail onions.",
    category: "Spirit-Forward",
    ingredients: ["2.5 oz Gin", "0.5 oz Dry Vermouth"],
    instructions: ["Combine ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a martini glass."],
    glassType: "Martini",
    garnish: "Cocktail onions",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "dirty-martini",
    name: "Dirty Martini",
    description: "A martini with olive brine for extra savory depth.",
    category: "Spirit-Forward",
    ingredients: ["2.5 oz Gin or Vodka", "0.5 oz Dry Vermouth", "0.5 oz Olive Brine"],
    instructions: ["Combine all ingredients in a mixing glass with ice.", "Stir until well-chilled.", "Strain into a martini glass."],
    glassType: "Martini",
    garnish: "Olives",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "tom-collins",
    name: "Tom Collins",
    description: "A refreshing gin fizz served long.",
    category: "Fizz",
    ingredients: ["2 oz Gin", "1 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "Club Soda"],
    instructions: ["Combine gin, lemon juice, and syrup in a Collins glass.", "Add ice and top with club soda.", "Stir gently."],
    glassType: "Collins",
    garnish: "Lemon wheel and cherry",
    creator: "John Collins",
    creatorType: "Historical"
  },
  {
    slug: "john-collins",
    name: "John Collins",
    description: "A bourbon version of the classic Collins.",
    category: "Fizz",
    ingredients: ["2 oz Bourbon", "1 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "Club Soda"],
    instructions: ["Combine bourbon, lemon juice, and syrup in a Collins glass.", "Add ice and top with club soda.", "Stir gently."],
    glassType: "Collins",
    garnish: "Lemon wheel and cherry",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "gin-fizz",
    name: "Gin Fizz",
    description: "A frothy gin sour topped with soda.",
    category: "Fizz",
    ingredients: ["2 oz Gin", "1 oz Fresh Lemon Juice", "0.75 oz Simple Syrup", "1 Egg White", "Club Soda"],
    instructions: ["Dry shake gin, lemon juice, syrup, and egg white.", "Add ice and shake again.", "Strain into a Collins glass.", "Top with club soda."],
    glassType: "Collins",
    garnish: "None",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "presbyterian",
    name: "Presbyterian",
    description: "A simple whiskey highball with ginger ale and club soda.",
    category: "Refreshing",
    ingredients: ["2 oz Bourbon or Rye", "2 oz Ginger Ale", "2 oz Club Soda"],
    instructions: ["Build in a highball glass over ice.", "Add whiskey.", "Top with equal parts ginger ale and club soda.", "Stir gently."],
    glassType: "Highball",
    garnish: "Lemon twist",
    creator: "Historical",
    creatorType: "Classic"
  },
  {
    slug: "highball",
    name: "Highball",
    description: "The quintessential Japanese-style whisky and soda.",
    category: "Refreshing",
    ingredients: ["2 oz Japanese Whisky", "4 oz Club Soda"],
    instructions: ["Fill a highball glass with ice.", "Add whisky.", "Top with cold club soda.", "Stir once gently."],
    glassType: "Highball",
    garnish: "Lemon twist",
    creator: "Japan",
    creatorType: "Traditional"
  },
  {
    slug: "mint-julep",
    name: "Mint Julep",
    description: "The official drink of the Kentucky Derby.",
    history: "A Southern classic dating back to the 18th century.",
    category: "Spirit-Forward",
    ingredients: ["2.5 oz Bourbon", "0.5 oz Simple Syrup", "8 Mint Leaves"],
    instructions: ["Muddle mint with syrup in a julep cup.", "Add bourbon and pack with crushed ice.", "Stir until cup frosts.", "Top with more crushed ice."],
    glassType: "Julep Cup",
    garnish: "Mint bouquet",
    creator: "Southern United States",
    creatorType: "Traditional"
  },
  {
    slug: "sazerac",
    name: "Sazerac",
    description: "New Orleans' official cocktail.",
    history: "Created in New Orleans in the mid-1800s, America's first branded cocktail.",
    category: "Spirit-Forward",
    ingredients: ["2 oz Rye Whiskey", "0.25 oz Simple Syrup", "3 dashes Peychaud's Bitters", "Absinthe rinse"],
    instructions: ["Rinse a rocks glass with absinthe.", "Combine whiskey, syrup, and bitters in a mixing glass with ice.", "Stir until well-chilled.", "Strain into the prepared glass."],
    glassType: "Old Fashioned",
    garnish: "Lemon twist (expressed, discarded)",
    creator: "New Orleans",
    creatorType: "Historical"
  }
];

export async function seedModernRecipes(): Promise<{ added: number; skipped: number; total: number }> {
  console.log(`Starting to seed ${MODERN_CRAFT_COCKTAILS.length} modern craft cocktails...`);
  
  let added = 0;
  let skipped = 0;
  
  for (const recipe of MODERN_CRAFT_COCKTAILS) {
    try {
      await db.insert(globalRecipes).values({
        slug: recipe.slug,
        name: recipe.name,
        description: recipe.description,
        history: recipe.history,
        category: recipe.category,
        ingredients: recipe.ingredients,
        instructions: recipe.instructions,
        glassType: recipe.glassType,
        garnish: recipe.garnish,
        creator: recipe.creator,
        creatorType: recipe.creatorType,
        flavorProfile: recipe.flavorProfile,
        enrichmentStatus: "pending",
      }).onConflictDoNothing();
      
      added++;
      console.log(`Added: ${recipe.name}`);
    } catch (error: any) {
      if (error.code === '23505') {
        skipped++;
        console.log(`Skipped (already exists): ${recipe.name}`);
      } else {
        console.error(`Error adding ${recipe.name}:`, error.message);
        skipped++;
      }
    }
  }
  
  console.log(`\nSeeding complete: ${added} added, ${skipped} skipped`);
  
  return {
    added,
    skipped,
    total: MODERN_CRAFT_COCKTAILS.length
  };
}
